{
  "hash": "458949f45e3a756e8e961b4bf9ba1bac",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Describing What You Have\"\nsubtitle: \"Variable types, tidy data, centre, spread and shape\"\nbody-classes: \"wf-at-describe wf-at-visualise\"\naliases:\n  - describing-what-you-have.html\n---\n\n```{=html}\n<nav class=\"wf-strip\" aria-label=\"Where this page sits in the analytical workflow\">\n  <span class=\"wf-label\">Workflow</span>\n  <ol>\n    <li class=\"wf-step wf-ask\">Ask</li>\n    <li class=\"wf-step wf-collect\">Collect</li>\n    <li class=\"wf-step wf-clean\">Inspect &amp; clean</li>\n    <li class=\"wf-step wf-visualise\">Visualise</li>\n    <li class=\"wf-step wf-describe\">Describe</li>\n    <li class=\"wf-step wf-uncertainty\">Quantify uncertainty</li>\n    <li class=\"wf-step wf-test\">Test</li>\n    <li class=\"wf-step wf-confounds\">Confounds</li>\n    <li class=\"wf-step wf-interpret\">Interpret</li>\n    <li class=\"wf-step wf-report\">Report</li>\n  </ol>\n</nav>\n```\n\n\n## Learning Outcomes\n\nBy the end of these notes you can:\n\n- choose between mean and median, and read the gap between them as evidence of\n  skew;\n- describe spread with the standard deviation, quartiles and IQR, and say why the\n  range is rarely enough;\n- draw a histogram and a boxplot in base R and say what each shows that a summary\n  hides.\n\n---\n\n## Why This Matters for Playtesting\n\nBefore comparing anything to anything, you have to be able to say what a single\nvariable looks like. This section is the vocabulary for that, and it is the part\nstudents most often skip and most often get caught by.\n\n---\n\n## Before You Start\n\n\n\nThis page assumes you can already say what type a variable is and what one row of\nthe table represents. Both are covered in\n[Data, Variables and Types](03-data-and-types.qmd). Every summary below is for a\n**numerical** variable unless it says otherwise.\n\n---\n\n## Centre\n\nTwo summaries of \"the typical value\", and choosing between them is a real\ndecision, not a formality.\n\nThe **mean** adds everything and divides by the count. It uses every value, which\nis its strength, and it is dragged by extremes, which is its weakness.\n\nThe **median** is the middle value when sorted. Half above, half below. It ignores\nhow extreme the extremes are, which is its strength and its weakness.\n\n**When they disagree, the data is skewed, and the gap tells you which way.** If\nthe mean sits well above the median, a few large values are pulling it up: a long\nright tail. If it sits below, a group of small values is pulling it down.\n\nFor game data this is not an edge case, it is the norm. Completion times, session\nlengths and frame times are all skewed almost by construction — there is a floor\non how fast anyone can finish and no ceiling on how slow. **Default to the median\nfor anything time-like** and reach for the mean only when you have looked at the\nshape and satisfied yourself it is roughly symmetric.\n\nWhen you compare the two, compare them relative to the size of the variable. A gap\nof 40 points on a score in the thousands is nothing; a gap of 3 minutes on a median\nof 26 is a real skew.\n\n---\n\n## Spread\n\nThe centre alone is nearly useless. Two levels with identical average completion\ntimes, one where everybody takes four minutes and one where half take one minute\nand half take seven, are not the same level.\n\n**Range** is minimum to maximum. Easy to quote and almost always misleading, since\na single unusual value defines it entirely.\n\n**Standard deviation** is the typical distance from the mean. It is the right\nmeasure for roughly symmetric data and it inherits the mean's sensitivity to\nextremes.\n\n**Quartiles** split the sorted data into four. The first quartile has a quarter\nbelow it, the third has three quarters. The **interquartile range** — the distance\nbetween them — is the width of the middle half of your players, and it is the most\nrobust description of spread you have. For skewed game data, quote the median and\nthe IQR together.\n\n**Percentiles** generalise this: the 95th percentile has 95% of values below it.\n[Distributions and Variation](05-distributions-and-shape.qmd) will show you why\nthe 99th percentile of frame time is the single most\nimportant number in a performance capture.\n\n---\n\n## Look at the Shape First\n\nEvery summary statistic throws information away. That is what a summary is for.\nThe risk is that it throws away the finding.\n\nA **histogram** shows you the whole distribution: where the bulk sits, whether it\nis symmetric, whether there is a second hump, whether there are outliers. Draw one\nbefore quoting any average. It costs one line.\n\nThe number of bins changes what you see, sometimes dramatically. Too few and a\nsecond hump disappears; too many and noise looks like structure. Try several. That\na chart changes with its settings is not a flaw to hide — it is the first evidence\nthat a chart is an argument rather than a fact, and you are responsible for the\nargument you make.\n\nA **boxplot** compresses the same information into median, quartiles and outliers.\nIt is less informative than a histogram for one variable and much better for\ncomparing several groups side by side, which is what Section 4 is about.\n\n**Two humps are always worth chasing.** A distribution with two peaks usually means\ntwo populations have been mixed: players who found the key and players who did\nnot, sessions that completed and sessions that crashed. The average of a bimodal\ndistribution describes nobody at all — it names a value that sits in the valley\nbetween the two groups, where the fewest players actually are.\n\n---\n\n## Worked Examples\n\n\n\n**Is the Sentinel underpowered?** Sort the four archetypes by mean score and the\nSentinel comes last, at 1313 points. A balance pass\nbuilt on that number buffs the Sentinel.\n\nSort by median instead and the Sentinel is the second-highest, at\n1528. The mean and the median disagree by\n215 points, and the\nstandard deviation is 455 against\n225 to 259 for the other three. Something is\ndragging the mean down without moving the middle.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(sentinel,\n     breaks = 12,\n     main   = \"Sentinel score, one bar per band\",\n     xlab   = \"Score\",\n     col    = \"grey85\",\n     border = \"white\")\n```\n\n::: {.cell-output-display}\n![](04-describing-variables_files/figure-html/worked-sentinel-hist-1.png){width=768}\n:::\n:::\n\n\nThe histogram answers it. 7 of the 30\nSentinel sessions scored under 700 and sit in a clump of their own at the far left,\n274 points below the\nnext-lowest Sentinel game. The Sentinel either anchors the round or collapses early.\nIt is not underpowered; it is inconsistent. A flat buff raises the scores of the\nplayers already doing well, and the design question becomes what the collapsing\ngames have in common ([rule 4](ten-rules.qmd)).\n\nThe same mean-against-distribution argument for a survey rating is the worked\nexample in [Data, Variables and Types](03-data-and-types.qmd#worked-example).\n\n---\n\n## R Demonstrations\n\nAll base R. The variable here is `time_alive_s`, seconds survived in the match.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(sessions$time_alive_s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   60.0   105.0   133.0   130.4   155.5   180.0 \n```\n\n\n:::\n\n```{.r .cell-code}\nsd(sessions$time_alive_s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32.74505\n```\n\n\n:::\n\n```{.r .cell-code}\nIQR(sessions$time_alive_s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 50.5\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(sessions$time_alive_s, c(0.1, 0.9))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  10%   90% \n 82.0 175.2 \n```\n\n\n:::\n:::\n\n\n`summary()` gives centre and quartiles in one call; `sd()` and `IQR()` give the two\nmeasures of spread; `quantile()` with a vector of proportions gives any percentiles\nyou ask for, here the 10th and 90th.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(sessions$time_alive_s,\n     breaks = 15,\n     main   = \"Time alive per session\",\n     xlab   = \"Seconds\",\n     col    = \"grey85\",\n     border = \"white\")\n```\n\n::: {.cell-output-display}\n![](04-describing-variables_files/figure-html/demo-hist-1.png){width=768}\n:::\n:::\n\n\n`breaks` sets roughly how many bars. Change it and look again before believing any\nshape.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(sessions$cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Novice Regular Veteran \n     33      53      34 \n```\n\n\n:::\n:::\n\n\n`table()` counts a categorical variable. It is the only summary a nominal variable\nhas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(sessions$time_alive_s, sessions$cohort, median)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Novice Regular Veteran \n  127.0   137.0   143.5 \n```\n\n\n:::\n\n```{.r .cell-code}\nboxplot(time_alive_s ~ cohort,\n        data = sessions,\n        main = \"Time alive by cohort\",\n        ylab = \"Seconds\",\n        col  = \"grey85\")\n```\n\n::: {.cell-output-display}\n![](04-describing-variables_files/figure-html/demo-by-group-1.png){width=768}\n:::\n:::\n\n\n`tapply()` applies one function to one variable, split by a group. The boxplot\nshows the same split as a picture: the thick line is the median, the box is the\nmiddle half, and the whiskers and points show the rest.\n\n---\n\n## Interpretation Guidance\n\n**A description has four parts: centre, spread, shape and size.** One sentence can\nhold all four:\n\n> Median time alive was 133 seconds (IQR\n> 50.5, n = 120). The mean sits\n> 2.6\n> seconds from the median, so the centre is not being pulled by a tail.\n> 11 sessions sit at\n> exactly 180 seconds, the full match: those players\n> never died, and the tallest bar on the right is a ceiling, not a peak.\n\n**Pick the summary to fit the shape, and say why.** Median and IQR for anything\nskewed or with outliers; mean and standard deviation only when the histogram is\nroughly symmetric.\n\n**Keep what the data shows apart from what it suggests.** \"The Sentinel's scores\nfall into two groups\" is what the data shows. \"Some Sentinel players do not know\nhow to play the role\" is a suggestion, and it needs a different kind of evidence\nbefore it becomes a conclusion.\n\n---\n\n## Common Mistakes\n\n**Quoting a mean without looking.** The Sentinel's mean is a correct calculation\nthat describes no Sentinel game. Draw the histogram first\n([rule 4](ten-rules.qmd)).\n\n**Quoting the range as the spread.** One extreme player sets the range on their\nown. Quote the IQR.\n\n**Trusting one bin setting.** A histogram drawn once is one argument among several\nthe data could make. Redraw it with fewer and more bars.\n\n**Leaving out n.** \"Players rated it 2.6\" means nothing without \"out of how many\"\n([rule 8](ten-rules.qmd)).\n\n---\n\n## Short Practice Activities\n\nEach takes two or three minutes.\n\n**1.** Describe `distance_m` in one sentence with centre, spread and size. Does the\nmean sit above or below the median?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(sessions$distance_m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 381.5\n```\n\n\n:::\n\n```{.r .cell-code}\nIQR(sessions$distance_m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 176.5\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(sessions$distance_m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 387.8833\n```\n\n\n:::\n:::\n\n\nMedian distance was 381.5 m (IQR\n176.5, n = 120). The mean sits\nabove\nthe median by\n6.4 m, which\nis small against a spread of that size.\n:::\n\n**2.** Use `table()` to find the most common number of deaths in a session. Why is\n`table()` sensible for `deaths` but not for `distance_m`?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(sessions$deaths)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 0  1  2  3  4  5  6  7 \n 4 18 26 23 31 12  4  2 \n```\n\n\n:::\n:::\n\n\nThe most common count is 4 deaths. Deaths\nis discrete with only a handful of possible values, so counting each one is\ninformative. 110 of the 120\n`distance_m` values are different, so its table is mostly a list of ones; a\ncontinuous variable needs a histogram instead.\n:::\n\n---\n\n## Summary\n\n- Report n with every summary.\n- When mean and median disagree, the data is skewed. Default to the median for\n  anything time-like.\n- Describe spread with the IQR for skewed data and the standard deviation for\n  symmetric data. The range is rarely enough.\n- Look at the histogram before quoting any average. Two humps mean two groups.\n\n---\n\n## Links to Relevant Reference Material\n\n- [Data, Variables and Types](03-data-and-types.qmd): variable types, tidy data,\n  sample and population\n- [Ten Rules](ten-rules.qmd): rule 4 (look at the shape before you quote the average), rule 5 (the mean is the\n  wrong summary more often than you think) and rule 8 (small samples lie\n  confidently)\n- [R and Quarto Reference: describing one variable](../reference/r-quarto-reference.qmd#describing-one-variable),\n  [describing by group](../reference/r-quarto-reference.qmd#describing-by-group)\n  and [plots](../reference/r-quarto-reference.qmd#plots)\n- [Lab 01: exploring playtest data](../labs/reading-data.qmd), Part B\n\n---\n\n## Reflective Questions\n\n- Why is the median usually the right summary for completion time, but not for\n  something like accuracy percentage?\n- You draw a histogram of level completion times and see two clear humps. List\n  three things that could have caused that, and say how you would tell them apart.\n- A teammate reports \"average session length is 22 minutes\". What two further\n  numbers would you ask for before letting that into a report?\n\n---\n",
    "supporting": [
      "04-describing-variables_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}