{
  "hash": "a1bf92cf8c3b4f0f428241e199235e46",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 02 — Comparing Builds\"\nsubtitle: \"Stage 2: cleaning, t-tests, and whether a difference matters\"\n---\n\n::: {.callout-note appearance=\"simple\" icon=\"false\" title=\"Get the files\"}\n- **Data:** [tidebreak_sessions_raw.csv](../data/tidebreak_sessions_raw.csv){download=\"tidebreak_sessions_raw.csv\"}, [tidebreak_sessions.csv](../data/tidebreak_sessions.csv){download=\"tidebreak_sessions.csv\"}, [tidebreak_paired.csv](../data/tidebreak_paired.csv){download=\"tidebreak_paired.csv\"}, [tidebreak_frame_times.csv](../data/tidebreak_frame_times.csv){download=\"tidebreak_frame_times.csv\"}, [tidebreak_survey.csv](../data/tidebreak_survey.csv){download=\"tidebreak_survey.csv\"}. Save them in the `data/` folder of your project.\n:::\n\n# Overview\n\nBuild B added lighting and signage to guide players through *Tidebreak*. This lab\nasks the question the team built it to answer:\n\n> **Does improved environmental guidance help players navigate the level?**\n\nPart A takes the raw export the team received and gets it into a shape that can\nanswer that question, keeping a written record of every decision. Part B puts a\nsize, an interval and a p-value on the differences, and asks the question no\nfunction answers: does this difference matter? By the end you will have answered\nthe Stage 2 question, *did the change work?*, and written the recommendation.\n\n| Function | What it does |\n| :- | :- |\n| `distinct()` | Drop rows that repeat an earlier row exactly |\n| `is.na()` | Find missing values |\n| `trimws()`, `tolower()` | Make text labels consistent |\n| `\\|>` | Pass the result on its left into the function on its right |\n| `filter()`, `select()`, `mutate()`, `arrange()` | Keep rows, keep columns, change a column, sort |\n| `count()`, `group_by()`, `summarise()` | Counts, and one row of summaries per group |\n| `t.test()` | Independent-samples and paired t-tests, with confidence intervals |\n\n# Learning outcomes\n\nBy the end of this lab you can:\n\n- find duplicates, gaps and inconsistent labels in a raw export, and fix them in\n  one readable pipeline;\n- write a cleaning log that records every row dropped, why, and what it did to *n*;\n- explain a p-value by reading a shuffle of the build labels;\n- run an independent-samples and a paired t-test, and pull the estimate, interval\n  and p-value out of the result;\n- tell \"no meaningful difference\" apart from \"cannot tell\" using a confidence\n  interval;\n- decide whether a statistically significant difference justifies a design change,\n  and write the recommendation.\n\n# Ground rules\n\n- Clean before you describe. Every change you make to the data goes in your\n  cleaning log, including changes that remove no rows.\n- Look at the plot before running the test. Every Part B exercise assumes you have\n  looked at the data first.\n- Type the code. Open the solution **after** your attempt, even when your attempt\n  worked.\n- Every exercise ends with a short written answer. Write it. The Challenge is\n  judged on the writing, not the code.\n- When you report a difference, give its size and its interval, not only the\n  p-value.\n\n# Setup (run this first)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(dplyr)\n\nsessions <- read_csv(\"data/tidebreak_sessions.csv\", show_col_types = FALSE)\npaired   <- read_csv(\"data/tidebreak_paired.csv\", show_col_types = FALSE)\nframes   <- read_csv(\"data/tidebreak_frame_times.csv\", show_col_types = FALSE)\nraw      <- read_csv(\"data/tidebreak_sessions_raw.csv\",\n                     trim_ws = FALSE, show_col_types = FALSE)\n\nnrow(raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 124\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(paired)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30\n```\n\n\n:::\n:::\n\n\n`raw` is the export as delivered, and Part A cleans it. `trim_ws = FALSE` stops\n`read_csv()` quietly stripping spaces from text values, so you see the file the way\nExcel or a database import would. `sessions` has one row per player per session,\nwith each player on one build only. `paired` is a separate study in which every\nplayer played both builds.\n\n---\n\n# Part A — Clean the export\n\nNotes for this part: [Cleaning and Transforming](../notes/06-cleaning-and-transforming.qmd).\n\n`raw` is the export the team actually received. Every problem in it is silent:\nnothing throws an error, and every problem changes an answer. Part A finds them,\nfixes them, and ends with the cleaning log that goes in your report.\n\n## Exercise 01 — Rows exported twice `[Do]`\n\nHow many rows of `raw` are exact copies of an earlier row? Then list any\n`session_id` that appears more than once.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(raw) - nrow(distinct(raw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\nraw |> count(session_id) |> filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  session_id     n\n  <chr>      <int>\n1 S046           2\n2 S053           2\n3 S057           2\n4 S103           2\n```\n\n\n:::\n:::\n\n\n`distinct()` drops exact repeats, so the difference in rows is the number of\ncopies. Counting `session_id` and keeping counts above 1 finds every key that\nappears twice.\n:::\n\n**Write 2 sentences:** the number of repeated keys equals the number of exact\ncopies. What would it mean if there were more repeated keys, and why could you not\nsimply delete the extra rows?\n\n## Exercise 02 — Where the gaps are `[Do]`\n\nCount the missing values in every column of `raw` at once.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(raw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       session_id         player_id            cohort         archetype \n                0                 0                 0                 0 \n            build          accuracy          mobility     survivability \n                0                 0                 0                 0 \nobjective_control           support         awareness             score \n                0                 0                 0                 0 \n            kills            deaths        objectives       shots_fired \n                0                 3                 0                 0 \n     time_alive_s        distance_m   session_minutes       quit_reason \n                0                 0                 9                 0 \n      wrong_turns   items_collected         completed        difficulty \n                0                 0                 0                 0 \n        enjoyment           comment \n                0                 0 \n```\n\n\n:::\n:::\n\n\n`is.na()` on a data frame gives a TRUE/FALSE table the same shape as the data, and\n`colSums()` counts the TRUEs in each column.\n:::\n\n**Write 1 sentence:** which column's gaps would you investigate first, and why\nthat one?\n\n## Exercise 03 — Clean it in one pipeline `[Apply]`\n\nBuild `clean` from `raw` in one pipeline: drop the duplicated rows, then fix\n`cohort` so that it has exactly three values. Count `cohort` before and after to\nprove the fix worked, and note the number of rows.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw |> count(cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 2\n   cohort         n\n   <chr>      <int>\n 1 \" Novice\"      1\n 2 \" Regular\"     1\n 3 \" Veteran\"     1\n 4 \"Novice\"      30\n 5 \"Novice \"      2\n 6 \"REGULAR\"      3\n 7 \"Regular\"     47\n 8 \"Regular \"     3\n 9 \"VETERAN\"      1\n10 \"Veteran\"     29\n11 \"Veteran \"     2\n12 \"regular\"      1\n13 \"veteran\"      3\n```\n\n\n:::\n\n```{.r .cell-code}\nclean <- raw |>\n  distinct() |>\n  mutate(cohort = tolower(trimws(cohort)))\n\nclean |> count(cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  cohort      n\n  <chr>   <int>\n1 novice     33\n2 regular    53\n3 veteran    34\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n:::\n\n\n`trimws()` removes the stray spaces and `tolower()` the inconsistent capitals.\nCounting before and after is the only proof that the fix caught every variant.\n:::\n\n**Write 2 sentences:** the relabelling removed no rows. Why does it still belong in\nthe cleaning log?\n\n## Exercise 04 — Who is missing? `[Apply]`\n\nList every row of `clean` with a blank `session_minutes` **or** a blank `deaths`.\nKeep only `session_id`, `build`, `quit_reason`, `session_minutes` and `deaths`, and\nsort by `build` then `quit_reason`.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  filter(is.na(session_minutes) | is.na(deaths)) |>\n  select(session_id, build, quit_reason, session_minutes, deaths) |>\n  arrange(build, quit_reason)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 5\n   session_id build quit_reason    session_minutes deaths\n   <chr>      <chr> <chr>                    <dbl>  <dbl>\n 1 S025       A     Completed test            30.2     NA\n 2 S077       A     Completed test            26.3     NA\n 3 S001       A     Frustrated                NA        4\n 4 S007       A     Frustrated                NA        4\n 5 S009       A     Frustrated                NA        3\n 6 S019       A     Frustrated                NA        4\n 7 S049       A     Frustrated                NA        1\n 8 S053       A     Frustrated                NA        1\n 9 S073       A     Frustrated                NA        3\n10 S119       A     Frustrated                NA        2\n11 S022       B     Lost interest             11.9     NA\n```\n\n\n:::\n:::\n\n\n`|` means \"or\", so a row is kept if either value is missing. Sorting puts rows\nwith the same build and outcome next to each other, which is what makes the\npattern visible.\n:::\n\n**Write 2 sentences:** describe the pattern in the blank `session_minutes` rows,\nand say how it differs from the pattern in the blank `deaths` rows.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show answer\"}\n\n\n::: {.cell}\n\n:::\n\n\nAll 8 blank session lengths are Build A frustration quits. The\n3 blank death counts are spread across\n2 builds and\n2 different outcomes. One set looks like\nsomething in the game failed to log; the other looks like noise.\n:::\n\n## Exercise 05 — Write the cleaning log `[Decide]`\n\nDecide what to do with the rows that have gaps, then write the cleaning log for\n`clean`: every step, the number of rows after it, and why. Your log is the record\na reader of the report would use to check your *n*\n([rule 6](../notes/ten-rules.qmd)).\n\nBefore you decide, compare each build's median `session_minutes` with the blanks\nleft out, against the median of the Build A frustration quits that *were*\nrecorded.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  group_by(build) |>\n  summarise(median_minutes = median(session_minutes, na.rm = TRUE),\n            missing        = sum(is.na(session_minutes)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  build median_minutes missing\n  <chr>          <dbl>   <int>\n1 A               26.2       8\n2 B               27.1       0\n```\n\n\n:::\n\n```{.r .cell-code}\nclean |>\n  filter(build == \"A\", quit_reason == \"Frustrated\") |>\n  summarise(recorded = sum(!is.na(session_minutes)),\n            median_minutes = median(session_minutes, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  recorded median_minutes\n     <int>          <dbl>\n1       12           11.2\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(complete.cases(clean))   # what \"drop every incomplete row\" would leave\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 109\n```\n\n\n:::\n:::\n\n\n\n\n**One defensible answer: keep every row, and handle the gaps per analysis.**\n\n| Step | Rows after | Why |\n| :- | -: | :- |\n| Raw export | 124 | As delivered |\n| Remove exact duplicates | 120 | 4 sessions exported twice; no key duplicates with different values |\n| Standardise `cohort` | 120 | 18 labels had stray spaces or inconsistent capitals |\n| Keep blank `session_minutes` | 120 | All 8 are Build A frustration quits. Summaries of session length exclude them and say so |\n| Keep blank `deaths` | 120 | 3 rows, no pattern. Excluded from deaths summaries only |\n\n**What makes it defensible.** The blank session lengths are not random. Recorded\nBuild A frustration quits have a median of\n11.2 minutes, so the\nmissing ones are almost certainly short, and Build A's median of\n26.1\nminutes is an overestimate. Keeping the rows keeps their `quit_reason`, which is\ncomplete and carries the finding. The log says what every summary of session\nlength is missing, so a reader can judge it.\n\n**What would make it indefensible.** Dropping every incomplete row by reflex, which\nsilently takes *n* from 120 to 109 and\nremoves the frustration quits the comparison is about. Or filling the blanks with 0\nor with Build A's average, which invents session lengths and hides the logging\nfault.\n:::\n\n**Write 3 sentences:** the blank session lengths are also a bug in Build A's\ntelemetry. Who should hear about it, and what goes in the bug report?\n\n::: {.callout-important title=\"Before Part B\"}\nPart B uses `sessions` from the Setup block, not your `clean`. It is the same\nsessions, exported again after the logging fault was fixed: the same rows, with the\ngaps you found filled.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidentical(clean$session_id, sessions$session_id)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(sessions$session_minutes))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(sessions$deaths))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nEverything Part B compares is therefore free of the bias you found in Exercise 05.\nIn a real playtest you would rarely get that second export. Your cleaning log is\nwhat you would have instead.\n:::\n\n---\n\n# Part B — Is the difference real, and does it matter?\n\nNotes for this part: [From Sample to Population](../notes/07-sample-to-population.qmd)\nand [Comparing Groups](../notes/08-comparing-groups.qmd). Report every comparison\nby answering the six questions from Comparing Groups, in order: what happened, how\nlarge, how uncertain, could it be chance, does it matter, what should the team do.\n\n## Exercise 06 — Describe before you test `[Do]`\n\nProduce one row per build with the number of sessions and the mean, median,\nstandard deviation and IQR of `wrong_turns`. Then draw side-by-side boxplots.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  group_by(build) |>\n  summarise(n      = n(),\n            mean   = mean(wrong_turns),\n            median = median(wrong_turns),\n            sd     = sd(wrong_turns),\n            iqr    = IQR(wrong_turns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  build     n  mean median    sd   iqr\n  <chr> <int> <dbl>  <dbl> <dbl> <dbl>\n1 A        60  8.92      9  2.37  2   \n2 B        60  5.52      5  2.70  4.25\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(wrong_turns ~ build, data = sessions, col = \"grey85\",\n        main = \"Wrong turns per session\", ylab = \"Wrong turns\")\n```\n\n::: {.cell-output-display}\n![](comparing-builds_files/figure-html/ex06b-1.png){fig-alt='Two boxplots of wrong turns per session. Build A\\'s box sits around 8 to 10; Build B\\'s is lower, around 3 to 7.5.' width=768}\n:::\n:::\n\n\n`n()` counts the rows in each group. Always report it: a difference means little\nwithout the number of players behind it.\n:::\n\n**Write 1 sentence:** Build B's standard deviation is larger than Build A's. What\ndoes that mean for a player?\n\n## Exercise 07 — The independent-samples t-test `[Do]`\n\nRun the t-test comparing `wrong_turns` between builds. Store the result, then pull\nout the two means, the confidence interval and the p-value separately.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- t.test(wrong_turns ~ build, data = sessions)\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  wrong_turns by build\nt = 7.3208, df = 116.07, p-value = 3.492e-11\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n 2.480141 4.319859\nsample estimates:\nmean in group A mean in group B \n       8.916667        5.516667 \n```\n\n\n:::\n\n```{.r .cell-code}\nresult$estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean in group A mean in group B \n       8.916667        5.516667 \n```\n\n\n:::\n\n```{.r .cell-code}\nresult$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.480141 4.319859\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nresult$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.491687e-11\n```\n\n\n:::\n:::\n\n\nEach player played one build only, so this is the independent-samples test.\nPulling out the parts with `$` is how you get the numbers into a sentence with\ninline R rather than by copying.\n:::\n\n**Write 2 sentences:** is the confidence interval for Build A minus Build B, or\nBuild B minus Build A? How can you tell from the output?\n\n## Exercise 08 — Could it be chance? Read the shuffle `[Do]`\n\nIf the signposting made no difference, the build label on each session would be\narbitrary. This code shuffles the labels 10,000 times, recomputes the gap in mean\nwrong turns each time, and counts how many shuffled gaps are at least as large as\nthe real one. You do not need to be able to write it. Run it, and compare the\nresult with Exercise 07's p-value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngap <- function(y, g) mean(y[g == \"A\"]) - mean(y[g == \"B\"])\n\nobserved <- gap(sessions$wrong_turns, sessions$build)\nset.seed(1)\nshuffled <- replicate(10000, gap(sessions$wrong_turns, sample(sessions$build)))\n\nobserved\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.4\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(abs(shuffled))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.166667\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(abs(shuffled) >= abs(observed))   # the shuffle's p-value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nhist(shuffled, breaks = 40, col = \"grey85\", border = \"white\",\n     xlim = range(c(shuffled, observed)),\n     main = \"Gaps from shuffled build labels\",\n     xlab = \"Difference in mean wrong turns (A - B)\")\nabline(v = observed, col = \"firebrick\", lwd = 3)\n```\n\n::: {.cell-output-display}\n![](comparing-builds_files/figure-html/ex08-1.png){fig-alt='Bell-shaped histogram of shuffled gaps in mean wrong turns, centred on zero and running from about minus 2 to plus 2, with a red line at the observed gap of 3.4 far to the right of every bar.' width=768}\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\nThe real gap is 3.4 wrong turns; the largest of ten thousand\nshuffled gaps is 2.17. No shuffle came close, so the\nshuffle's p-value is below 1 in 10,000, which agrees with the t-test's tiny\np-value. The shuffle shows what a p-value *is*: the share of a world without a\ndifference that looks at least as extreme as your data.\n:::\n\n**Write 2 sentences:** what does one shuffle represent, and why does the\nproportion of extreme shuffles answer \"could this be chance?\"\n\n## Exercise 09 — The same players, both builds `[Apply]`\n\n`paired` records 30 players who each played both builds. Run the\npaired t-test on `wrong_turns_a` and `wrong_turns_b`, then run the unpaired test on\nthe same two columns. Compare the widths of the two confidence intervals.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaired_test   <- t.test(paired$wrong_turns_a, paired$wrong_turns_b, paired = TRUE)\nunpaired_test <- t.test(paired$wrong_turns_a, paired$wrong_turns_b)\n\npaired_test$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.838014 3.695319\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nunpaired_test$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.180570 4.352763\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(paired_test$conf.int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.857305\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(unpaired_test$conf.int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.172193\n```\n\n\n:::\n:::\n\n\nSame estimate, but the paired interval is\n1.9 wrong turns wide against\n3.2. The paired test compares each player\nwith themselves, so differences in player skill cancel out. `diff()` of an\ninterval is its width.\n:::\n\n**Write 2 sentences:** the paired file does not record which build each player\nplayed first. Why does that matter, and what would you change about the next\npaired study?\n\n## Exercise 10 — No difference, or cannot tell? `[Apply]`\n\nRun the t-test on `enjoyment` by build and on `items_collected` by build. Neither\nis significant. For which one can you say there is **no meaningful difference**,\nand for which can you only say **we cannot tell**?\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenjoy <- t.test(enjoyment ~ build, data = sessions)\nitems <- t.test(items_collected ~ build, data = sessions)\n\nenjoy$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.3483742  0.3483742\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nitems$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.0061446  0.3394779\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nsessions |> summarise(mean_items = mean(items_collected))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  mean_items\n       <dbl>\n1       4.18\n```\n\n\n:::\n:::\n\n\nRead each interval against the size of the variable. Enjoyment's interval runs\nfrom -0.35 to 0.35 on a\nseven-point scale: whatever the true difference is, it is too small to matter. That\nis **no meaningful difference**. The items interval runs from\n-1.01 to 0.34 items, when a\ntypical player collects about\n4. Build B's players could be collecting\nup to 1.0 more items each, or up to\n0.3 fewer. That is **cannot tell**.\n\n\"Cannot tell\" means this playtest was too small to see a difference of that size.\nA bigger playtest, or a paired one, would narrow the interval enough to decide\n([Testing in Depth](../going-further/testing-in-depth.qmd#two-ways-to-be-wrong)).\n:::\n\n**Write 2 sentences:** why is \"not significant\" a weaker statement than \"the\nconfidence interval is narrow and sits around zero\"?\n\n## Exercise 11 — \"Players play longer in Build B\" `[Decide]`\n\n\n\n`t.test(session_minutes ~ build)` gives p = 0.037,\nand Build B's sessions are about 3 minutes\nlonger on average. The producer wants to put \"players play\n3 minutes longer in Build B\" in the pitch. Do you\nlet them? Test before you decide: compare session length between the builds for\nplayers who did **not** quit in frustration.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnot_frustrated <- sessions |> filter(quit_reason != \"Frustrated\")\nt.test(session_minutes ~ build, data = not_frustrated)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  session_minutes by build\nt = 0.63783, df = 88.126, p-value = 0.5252\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n -1.564143  3.042780\nsample estimates:\nmean in group A mean in group B \n       26.19750        25.45818 \n```\n\n\n:::\n\n```{.r .cell-code}\nsessions |>\n  filter(quit_reason == \"Frustrated\") |>\n  group_by(build) |>\n  summarise(n = n(), median_minutes = median(session_minutes))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  build     n median_minutes\n  <chr> <int>          <dbl>\n1 A        20           11.7\n2 B         5           11.7\n```\n\n\n:::\n:::\n\n\n**One defensible answer: no, because the claim describes the wrong thing.** Among\nplayers who did not quit in frustration, Build A averaged\n26.2 minutes and Build B\n25.5 (p = 0.53). Frustration\nquits end at a median of about 11.7 minutes in both builds.\nBuild B does not make anyone play longer. It makes fewer people quit early, and\nthat pulls its average up. The honest pitch line is \"fewer players quit in\nfrustration\", which is also the stronger claim.\n\n**What makes it defensible.** It checks what is driving the difference before\ndescribing it, and it replaces the claim with one the data supports.\n\n**What would make it indefensible.** Approving the line because the p-value is\nbelow 0.05. The difference is real; the explanation attached to it is not.\n:::\n\n**Write 3 sentences:** a significant difference in a mean can come from every\nplayer shifting a little or from a few players shifting a lot. How do you tell\nwhich, and why does it change the design conclusion?\n\n## Exercise 12 — Which number goes in the report? `[Decide]`\n\nYou have three estimates of how much the signposting reduced wrong turns: the\nsession-level test from Exercise 07, the paired study from Exercise 09, and a\nplayer-level test that averages each player's 4\nsessions first. Run the player-level test, then decide which result leads the\nreport.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nper_player <- sessions |>\n  group_by(player_id, build) |>\n  summarise(wrong_turns = mean(wrong_turns), .groups = \"drop\")\nplayer_test <- t.test(wrong_turns ~ build, data = per_player)\n\nplayer_test$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.361153 4.438847\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nresult$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.480141 4.319859\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\npaired_test$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.838014 3.695319\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n**One defensible answer: lead with the player-level result, and cite the paired\nstudy as support.** The session-level test treats\n120 sessions as independent when they come from\n30 players, so its interval is narrower than the data justifies.\nThe player-level interval, 2.4 to\n4.4 wrong turns, is honest about that. The paired\nstudy, a different design with different players, points the same way, which is\nworth more than any single p-value.\n\n**What makes it defensible.** It picks the analysis whose assumptions match how\nthe data was collected, and it uses the other two as corroboration rather than\nchoosing between them.\n\n**What would make it indefensible.** Picking whichever result has the smallest\np-value or the largest effect. That is choosing the answer, not the analysis.\n:::\n\n**Write 2 sentences:** why is agreement between two differently designed studies\nstronger evidence than a very small p-value from one?\n\n---\n\n# Challenge — Build B was meant to be an improvement. Was it? `[Decide]`\n\nThe producer asks one question before approving Build B for the next milestone:\n**was it an improvement?**\n\nBuild the evidence you would take into that meeting. Use more than one measure:\nnavigation, whether players stayed and finished, whether anything got worse, and\nperformance. `frames` is loaded in the Setup block. For each measure, keep the\nevidence separate: what the plot shows, what the summaries say, what the test\nsays, and whether the difference is big enough to matter.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Navigation: the question Build B was built to answer\nt.test(wrong_turns ~ build, data = sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  wrong_turns by build\nt = 7.3208, df = 116.07, p-value = 3.492e-11\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n 2.480141 4.319859\nsample estimates:\nmean in group A mean in group B \n       8.916667        5.516667 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Did players stay and finish? Rates per build, then a test for each\noutcomes <- sessions |>\n  group_by(build) |>\n  summarise(n          = n(),\n            frustrated = sum(quit_reason == \"Frustrated\"),\n            completed  = sum(completed))\noutcomes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  build     n frustrated completed\n  <chr> <int>      <int>     <int>\n1 A        60         20        32\n2 B        60          5        53\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(outcomes$frustrated, outcomes$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  outcomes$frustrated out of outcomes$n\nX-squared = 9.9032, df = 1, p-value = 0.00165\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.09506413 0.40493587\nsample estimates:\n    prop 1     prop 2 \n0.33333333 0.08333333 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(outcomes$completed, outcomes$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  outcomes$completed out of outcomes$n\nX-squared = 16.134, df = 1, p-value = 5.9e-05\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.5167766 -0.1832234\nsample estimates:\n   prop 1    prop 2 \n0.5333333 0.8833333 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. Did anything get worse?\nt.test(enjoyment ~ build, data = sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  enjoyment by build\nt = 0, df = 113.42, p-value = 1\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n -0.3483742  0.3483742\nsample estimates:\nmean in group A mean in group B \n       3.933333        3.933333 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(score ~ build, data = sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  score by build\nt = 0.22558, df = 117.76, p-value = 0.8219\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n -102.6797  129.0797\nsample estimates:\nmean in group A mean in group B \n       1435.367        1422.167 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 4. Performance, which nobody asked about\nframes |>\n  group_by(build) |>\n  summarise(fps = 1000 / mean(ms), p99 = quantile(ms, 0.99))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  build   fps   p99\n  <chr> <dbl> <dbl>\n1 A      58.8  19.5\n2 B      59.0  39.4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(ms ~ build + zone, data = frames, col = \"grey85\", las = 2,\n        main = \"Frame times by build and zone\", ylab = \"Frame time (ms)\", xlab = \"\")\n```\n\n::: {.cell-output-display}\n![](comparing-builds_files/figure-html/challenge-plot-1.png){fig-alt='Boxplots of frame time for each build and zone. All six boxes sit near 17 ms; only Build B\\'s Corridor has a column of outliers between about 34 and 55 ms.' width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n| Measure | Descriptive | Statistical | Practical |\n| :- | :- | :- | :- |\n| Wrong turns | Mean 8.9 in A, 5.5 in B | 95% CI 2.5 to 4.3 fewer, p < 0.001 | Large: players get lost far less |\n| Frustration quits | 20 in A, 5 in B | `prop.test()`: p = 0 | Large: the main way Build A lost players |\n| Completed the test | 53% in A, 88% in B | `prop.test()`: p < 0.001 | Large |\n| Enjoyment | Means 3.9 and 3.9 | 95% CI -0.35 to 0.35, p = 1 | No cost to enjoyment |\n| Score | Means 1435 and 1422 | p = 0.82 | No change |\n| Frame time | Both about 59 FPS; 99th percentile 19.5 ms in A, 39.4 ms in B | Not a comparison of means | Every one of the 60 frames slower than 30 FPS is Build B, in the Corridor |\n\n**The headline, in the six steps.**\n\n1. **What happened?** Build B's players took fewer wrong turns, fewer quit in\n   frustration, and more finished.\n2. **How large?** 3.4 fewer wrong\n   turns per session; 20 frustration quits against 5.\n3. **How uncertain?** The wrong-turns interval runs from\n   2.5 to 4.3 fewer.\n4. **Could it be chance?** Not plausibly: p < 0.001, and the same for\n   frustration and completion.\n5. **Does it matter?** Yes. Even the smallest plausible reduction is noticeable,\n   and none of it cost enjoyment or score. But the frame-time plot shows a hitch\n   in Build B's Corridor that the average frame rate cannot see.\n6. **What should the team do?** Keep the signposting; fix the Corridor hitch\n   before Build B goes forward.\n\n**What would make it indefensible.** Answering from wrong turns alone, because that\nis the measure the build was designed to move. Or quoting average FPS as proof\nthat performance was unchanged. Both answers are supported by a real number, and\nboth miss what a player would actually experience.\n:::\n\n**Write 4 sentences**, using **What → Pattern → Meaning → Action**:\n\n- **What** did you measure?\n- **Pattern**: what does the evidence show, across more than one measure? Give\n  the size and the interval for the main one.\n- **Meaning**: what does that mean for the player?\n- **Action**: what exactly do you recommend to the producer?\n\n---\n\n# Extension — Bring the survey in `[Apply]`\n\nFor anyone who finishes the Challenge with time to spare. It uses one new\nfunction, `left_join()`, which you will meet properly in Stage 4.\n\n\n\nThe survey does not record the build. Load `data/tidebreak_survey.csv`, then use\n`left_join()` to add each session's `build` to it, matching on `session_id`. Then\ncompare the share of responses in each build that **disagreed** (1 or 2) with \"I\nalways knew what my objective was\", using `prop.test()`.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey <- read_csv(\"data/tidebreak_survey.csv\", show_col_types = FALSE)\n\njoined <- survey |>\n  left_join(select(sessions, session_id, build), by = \"session_id\")\n\nnrow(joined)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(joined$build))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\ndisagreed <- joined |>\n  group_by(build) |>\n  summarise(disagreed = sum(objective_clear <= 2), n = n())\ndisagreed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  build disagreed     n\n  <chr>     <int> <int>\n1 A            37    60\n2 B            18    60\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(disagreed$disagreed, disagreed$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  disagreed$disagreed out of disagreed$n\nX-squared = 10.876, df = 1, p-value = 0.0009744\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.1309446 0.5023888\nsample estimates:\n   prop 1    prop 2 \n0.6166667 0.3000000 \n```\n\n\n:::\n:::\n\n\n`left_join()` keeps every survey row and adds `build` from the matching session;\nchecking that the row count is unchanged and that no `build` is `NA` confirms every\nsurvey found its session. 37 of 60\nBuild A responses disagreed, against 18 of\n60 in Build B\n(p < 0.001).\n:::\n\n**Write 2 sentences:** the telemetry says Build B players took fewer wrong turns;\nwhat does this survey result add, and what kind of evidence is it?\n\n---\n\n# Appendix — Reading `t.test()` output\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show the annotated output\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(wrong_turns ~ build, data = sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  wrong_turns by build\nt = 7.3208, df = 116.07, p-value = 3.492e-11\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n 2.480141 4.319859\nsample estimates:\nmean in group A mean in group B \n       8.916667        5.516667 \n```\n\n\n:::\n:::\n\n\n| Line | What it tells you |\n| :- | :- |\n| `Welch Two Sample t-test` | The independent-samples test, not assuming equal spreads. The right default |\n| `t = ..., df = ...` | The test statistic and its degrees of freedom. Report them if asked; do not interpret them |\n| `p-value = ...` | How surprising the data would be if the builds did not differ. `e-11` means \"times 10 to the minus 11\": tiny |\n| `alternative hypothesis: ...` | Names the direction: the difference is *group A minus group B* |\n| `95 percent confidence interval` | The plausible range for the difference, A minus B |\n| `sample estimates` | The two group means |\n\n:::\n\n# Appendix — Common errors\n\n::: {.callout-warning collapse=\"true\" title=\"Show the error guide\"}\n\n| Message | What it usually means |\n| :- | :- |\n| `grouping factor must have exactly 2 levels` | `t.test(y ~ group)` needs exactly two groups. Filter to two first |\n| `not enough 'x' observations` | A group is empty, usually a misspelled level such as `\"a\"` for `\"A\"` |\n| `could not find function \"filter\"` (or `distinct`, `count`) | You have not run `library(dplyr)` |\n| `'x' and 'n' must have the same length` | `prop.test()` needs one count and one total per group, in the same order |\n| `object 'clean' not found` | You skipped Exercise 03, or ran Part A out of order |\n| `unexpected '>'` on a line with `\\|>` | Your R is older than 4.1. Update R |\n\n:::\n",
    "supporting": [
      "comparing-builds_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}