{
  "hash": "33665bd1840bd331b760ef5238669a84",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 04 — Relationships in Your Data\"\nsubtitle: \"Stage 3B clinic: correlation on Tidebreak, then a correlation matrix of your own measures\"\n---\n\n::: {.callout-note appearance=\"simple\" icon=\"false\" title=\"Get the files\"}\n- **Data:** [tidebreak_sessions.csv](../data/tidebreak_sessions.csv){download=\"tidebreak_sessions.csv\"}, [tidebreak_survey.csv](../data/tidebreak_survey.csv){download=\"tidebreak_survey.csv\"}. Save them in the `data/` folder of your project.\n:::\n\n# Overview\n\nThis is a clinic, not a full lab. It is short, and it ends with your team's own\ndata. The aim is one thing:\n\n> **A correlation matrix of 3–5 meaningful measures from your own playtest, read\n> and checked, with one relationship written up as a finding.**\n\nPart A is a warm-up on *Tidebreak*: measure relationships, choose between Pearson\nand Spearman, read a matrix, relate telemetry to self-report, and catch a\nrelationship that reverses within groups. Part B is your project. Bring your\nteam's latest playtest export, in your project's `data/` folder.\n\n| Function | What it does |\n| :- | :- |\n| `cor(x, y)` | Pearson correlation, −1 to +1 |\n| `cor(x, y, method = \"spearman\")` | Spearman correlation: for ratings, curves and outliers |\n| `select()` then `cor()` | A correlation matrix of the columns you chose |\n| `pairs()` | Every pair as a small scatterplot, to check the matrix |\n| `left_join()` | Add columns from another table, matched on a key |\n| `group_by()` + `summarise(r = cor(...))` | The correlation within each group |\n\n# Learning outcomes\n\nBy the end of this clinic you can:\n\n- measure a relationship with `cor()`, and choose between Pearson and Spearman;\n- build and read a correlation matrix of 3–5 measures, and check it with\n  scatterplots;\n- relate a telemetry measure to a self-report measure, and say what it means when\n  they disagree;\n- check a relationship within groups before trusting it;\n- write a relationship as a finding without claiming a cause.\n\n# Ground rules\n\n- Draw before you quote. Every correlation stands in for a scatterplot.\n- Choose your measures for a question. A matrix of every column finds luck.\n- Write \"is associated with\", never \"causes\", unless someone changed something on\n  purpose.\n- Type the code. Open the solution **after** your attempt.\n\n# Setup (run this first)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(dplyr)\nlibrary(ggplot2)\n\nsessions <- read_csv(\"data/tidebreak_sessions.csv\", show_col_types = FALSE)\nsurvey   <- read_csv(\"data/tidebreak_survey.csv\", show_col_types = FALSE)\n\nnrow(sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n:::\n\n\n---\n\n# Part A — Warm-up on Tidebreak\n\nNotes for this part:\n[Relationships and Correlation](../notes/10-relationships-and-correlation.qmd).\n\n## Exercise 01 — What goes with score? `[Do]`\n\nUse `cor()` to measure how strongly `score` is related to `awareness`, and to\n`shots_fired`.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(sessions$awareness, sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5907852\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(sessions$shots_fired, sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05307857\n```\n\n\n:::\n:::\n\n\n`cor()` gives a number from −1 to +1. Near 0 means no straight-line relationship;\nthe sign gives the direction.\n:::\n\n**Write 2 sentences:** a designer wants to reward players who fire more shots,\n\"because they are the ones scoring\". What do you tell them?\n\n## Exercise 02 — Pearson or Spearman? `[Apply]`\n\nDo players who die more rate the game as harder? Draw `difficulty` against\n`deaths`, then compute both the Pearson and the Spearman correlation. Which would\nyou report, and why?\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sessions, aes(x = deaths, y = difficulty)) +\n  geom_jitter(width = 0.15, height = 0.15, alpha = 0.6) +\n  labs(x = \"Deaths\", y = \"Difficulty rating (1-7)\")\n```\n\n::: {.cell-output-display}\n![](clinic-relationships_files/figure-html/ex02-1.png){fig-alt='Jittered scatterplot of difficulty rating against deaths, rising from lower left to upper right with a lot of scatter.' width=768}\n:::\n\n```{.r .cell-code}\ncor(sessions$deaths, sessions$difficulty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5792729\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(sessions$deaths, sessions$difficulty, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5731608\n```\n\n\n:::\n:::\n\n\nThe two agree closely, because the relationship is roughly straight with no wild\nvalues. Report Spearman anyway: `difficulty` is a 1–7 rating, so the gaps between\nits values are not known to be equal, and Spearman only uses their order.\n`geom_jitter()` nudges the points so that sessions with the same values do not hide\neach other.\n:::\n\n**Write 1 sentence:** describe the relationship in words a designer would use,\nincluding how loose it is.\n\n## Exercise 03 — A correlation matrix `[Apply]`\n\nBuild a Spearman correlation matrix of `deaths`, `wrong_turns`, `difficulty`,\n`enjoyment` and `session_minutes`, rounded to 2 places. Then draw every pair with\n`pairs()`. Which pair goes together most strongly, and which measure goes with\nnothing?\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- sessions |>\n  select(deaths, wrong_turns, difficulty, enjoyment, session_minutes)\n\nm |> cor(method = \"spearman\") |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                deaths wrong_turns difficulty enjoyment session_minutes\ndeaths            1.00       -0.03       0.57     -0.20           -0.02\nwrong_turns      -0.03        1.00      -0.09     -0.03            0.04\ndifficulty        0.57       -0.09       1.00     -0.33            0.15\nenjoyment        -0.20       -0.03      -0.33      1.00            0.23\nsession_minutes  -0.02        0.04       0.15      0.23            1.00\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(m, pch = 19, cex = 0.4, col = adjustcolor(\"grey30\", alpha.f = 0.4))\n```\n\n::: {.cell-output-display}\n![](clinic-relationships_files/figure-html/ex03b-1.png){fig-alt='A five by five grid of small scatterplots. Deaths against difficulty shows a rising band; wrong turns show no pattern against anything.' width=768}\n:::\n:::\n\n\n\n\nIgnore the diagonal of 1s and read one triangle. `deaths` and `difficulty` go\ntogether most strongly, 0.57. `wrong_turns` is\nclose to 0 with every other measure. The `pairs()` panels agree: one rising band\nfor deaths and difficulty, shapeless clouds for wrong turns.\n:::\n\n**Write 2 sentences:** wrong turns differ hugely between the builds, yet correlate\nwith nothing here. Why might that be, and what would you check next?\n\n## Exercise 04 — Telemetry against self-report `[Apply]`\n\nDo players who got lost more rate the level as harder to navigate? Join the survey\nonto the sessions with `left_join()`, matching on `session_id`. Then find the\nSpearman correlation between `wrong_turns` and `level_navigable`, and each build's\nmean of both.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\njoined <- sessions |>\n  left_join(survey, by = \"session_id\")\n\ncor(joined$wrong_turns, joined$level_navigable, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05151128\n```\n\n\n:::\n\n```{.r .cell-code}\njoined |>\n  group_by(build) |>\n  summarise(mean_wrong_turns = mean(wrong_turns),\n            mean_navigable   = mean(level_navigable))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  build mean_wrong_turns mean_navigable\n  <chr>            <dbl>          <dbl>\n1 A                 8.92           3.2 \n2 B                 5.52           3.23\n```\n\n\n:::\n:::\n\n\n\n\nThe correlation is 0.05: no relationship. Build A's players made far\nmore wrong turns but rated navigation almost exactly as Build B's did,\n3.2 against 3.23. The telemetry saw a\nnavigation problem; the players did not report one.\n:::\n\n**Write 3 sentences:** what does this mean for a team that only asks players\nwhether the level was easy to navigate? What would **observation** add?\n\n## Exercise 05 — The trade-off `[Apply]`\n\nDraw `survivability` against `mobility` as a scatterplot with a straight-line\ntrend, and measure the relationship with `cor()`.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sessions, aes(x = mobility, y = survivability)) +\n  geom_point(colour = \"grey40\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"black\") +\n  labs(title = \"Mobility against survivability\",\n       x = \"Mobility rating\", y = \"Survivability rating\")\n```\n\n::: {.cell-output-display}\n![](clinic-relationships_files/figure-html/ex05-1.png){fig-alt='Scatterplot of survivability against mobility with a falling black trend line.' width=768}\n:::\n\n```{.r .cell-code}\ncor(sessions$mobility, sessions$survivability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.6562375\n```\n\n\n:::\n:::\n\n\n`geom_smooth(method = \"lm\")` draws the straight line that best fits the points;\n`se = FALSE` leaves out the shaded band. The line and `cor()` describe the same\nrelationship, one as a picture and one as a number.\n:::\n\n**Write 1 sentence:** describe the relationship in words a balance designer would\nuse.\n\n## Exercise 06 — Faster players are more fragile? `[Decide]`\n\n\n\nThe balance designer reads Exercise 05 and proposes a patch: *\"Faster players are\nmore fragile, so when a Scout player gets faster, cut their health to match.\"*\nRedraw the scatterplot with each archetype in its own colour and its own trend\nline, compute the correlation within each archetype, and decide whether the patch\nfollows from the data.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sessions, aes(x = mobility, y = survivability, colour = archetype)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(title = \"Mobility against survivability, by archetype\",\n       x = \"Mobility rating\", y = \"Survivability rating\", colour = \"Archetype\")\n```\n\n::: {.cell-output-display}\n![](clinic-relationships_files/figure-html/ex06-1.png){fig-alt='Survivability against mobility with points coloured by archetype, each with its own rising trend line. The four clusters sit along a falling diagonal, Sentinel at the top left and Scout at the bottom right.' width=768}\n:::\n\n```{.r .cell-code}\nsessions |>\n  group_by(archetype) |>\n  summarise(r = cor(mobility, survivability))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  archetype     r\n  <chr>     <dbl>\n1 Duelist   0.302\n2 Engineer  0.512\n3 Scout     0.465\n4 Sentinel  0.598\n```\n\n\n:::\n:::\n\n\n**One defensible answer: no, the patch reads the data backwards.** Across all\nplayers the correlation is -0.66. Within every archetype it is\npositive, from 0.3 to 0.6. The\ndownward trend is the gap *between* archetypes: Scouts are built fast and fragile,\nSentinels slow and tough. Within any one archetype, better players are better at\nboth. **Archetype is the confounding variable**: it drives both measures, and\nignoring it reverses the direction of the relationship.\n\n**What makes it defensible.** It checks the relationship inside the groups the\ndesign is made of before drawing a conclusion about individuals, and it says what\nthe overall correlation *does* show: the archetypes are balanced against each other\nas intended.\n\n**What would make it indefensible.** Applying the patch because the correlation is\nstrong. A strong correlation across groups says nothing about what happens to one\nplayer within a group.\n:::\n\n**Write 3 sentences:** name the confounder, say what it does to the conclusion, and\nsay which section of the report (Results or Discussion) this belongs in.\n\n---\n\n# Part B — Your project `[Decide]`\n\nThis is the part that matters. Allow at least half the clinic for it.\n\nWork through these steps on your team's own playtest data, in a Quarto document in\nyour project.\n\n1. **Write the design question** the relationships bear on, in one sentence.\n2. **Choose 3–5 numeric measures** that matter to it. Aim for at least one from\n   telemetry and one from self-report, so you can see whether they agree. Join\n   files on a shared ID with `left_join()` if they are separate.\n3. **Build the matrix**: `select()` the measures, then\n   `cor(method = \"spearman\")` if any is a rating, and `round(2)`.\n4. **Check it with `pairs()`**. Any correlation whose scatterplot does not look\n   like its number is not to be trusted.\n5. **Pick the one relationship that matters most** to your question, and draw it\n   properly with `ggplot2`.\n6. **Check it within groups**: build, level, character or experience, whichever\n   your game has. Does it hold inside each?\n\n```r\nour_data |>\n  select(measure_1, measure_2, measure_3, measure_4) |>\n  cor(method = \"spearman\") |>\n  round(2)\n\nour_data |>\n  group_by(build) |>\n  summarise(n = n(), r = cor(measure_1, measure_2, method = \"spearman\"))\n```\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show answer\"}\nThere is no single right matrix: it depends on your game and your question. Check\nyour work against this list.\n\n- [ ] Every measure in the matrix bears on the question; none is there \"in case\".\n- [ ] At least one telemetry and one self-report measure, if your playtest\n  collected both.\n- [ ] Spearman if any measure is a rating; Pearson only if the scatterplots are\n  straight and free of extreme values.\n- [ ] You drew the pairs before quoting any number.\n- [ ] The relationship you chose was checked within groups.\n- [ ] Your write-up says \"is associated with\", not \"causes\".\n- [ ] If telemetry and self-report disagree, you have said so: that is a finding,\n  not a failure.\n\nExercises 03, 04 and 06 are worked versions of steps 3 to 6 on *Tidebreak*.\n:::\n\n**Write 3–4 sentences**, using **What → Pattern → Meaning → Action**, for the one\nrelationship that matters most:\n\n- **What** did you measure, on whom, and how many?\n- **Pattern**: how strongly do the two measures go together, and does it hold\n  within groups?\n- **Meaning**: what might explain it? Name at least one explanation other than\n  cause.\n- **Action**: what would the team test next to find out which explanation is\n  right?\n\n---\n\n# Extension — How much, not just how strongly `[Apply]`\n\nFor anyone who finishes early. A correlation says how tightly two measures go\ntogether; a regression line says *how much* one changes with the other. This is\nGoing Further material, explained on [Regression](../going-further/regression.qmd).\n\nFit a regression of `score` on `awareness` with `lm()`. Report the slope with its\n95% confidence interval, then list the seven sessions that scored furthest below\nwhat their awareness predicted.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(score ~ awareness, data = sessions)\ncoef(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   awareness \n  426.13072    15.15319 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 %    97.5 %\n(Intercept) 172.1697 680.09176\nawareness    11.3806  18.92578\n```\n\n\n:::\n\n```{.r .cell-code}\nworst <- order(resid(fit))[1:7]\nsessions[worst, c(\"session_id\", \"archetype\", \"awareness\", \"score\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 4\n  session_id archetype awareness score\n  <chr>      <chr>         <dbl> <dbl>\n1 S059       Sentinel         78   587\n2 S045       Sentinel         63   597\n3 S034       Sentinel         61   584\n4 S052       Sentinel         54   541\n5 S046       Sentinel         55   579\n6 S047       Sentinel         59   643\n7 S012       Scout            67   934\n```\n\n\n:::\n:::\n\n\n\n\nEach extra point of awareness goes with about 15.2 more points of\nscore on average (95% CI 11.4 to 18.9).\n`resid(fit)` is actual minus predicted, so `order()` puts the biggest\nunderperformers first. 6 of the seven are Sentinels: the collapsing games,\nwhich awareness does not explain at all.\n:::\n\n**Write 2 sentences:** turn the slope into a sentence a balance designer could use,\nthen say what the regression cannot tell them.\n\n---\n\n# Appendix — Common errors\n\n::: {.callout-warning collapse=\"true\" title=\"Show the error guide\"}\n\n| Message or symptom | What it usually means |\n| :- | :- |\n| `'x' must be numeric` | A text column got into `cor()`. `select()` only numeric measures |\n| `NA` in the matrix | A column has missing values. Add `use = \"complete.obs\"` to `cor()`, and say how many rows it left out |\n| `the standard deviation is zero` | A measure has the same value in every row: it cannot correlate with anything |\n| A matrix of every column you have | Choose 3–5 measures for your question instead |\n| `left_join()` gives more rows than you started with | The key is repeated in the second table. Check it with `count(key) \\|> filter(n > 1)` |\n\n:::\n",
    "supporting": [
      "clinic-relationships_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}