{
  "hash": "b4a77d9131b426276185ba4d0d285c40",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Relationships, Correlation and Regression\"\nsubtitle: \"When two things move together, and what that does and does not mean\"\nbody-classes: \"wf-at-describe wf-at-confounds\"\n---\n\n```{=html}\n<nav class=\"wf-strip\" aria-label=\"Where this page sits in the analytical workflow\">\n  <span class=\"wf-label\">Workflow</span>\n  <ol>\n    <li class=\"wf-step wf-ask\">Ask</li>\n    <li class=\"wf-step wf-collect\">Collect</li>\n    <li class=\"wf-step wf-clean\">Inspect &amp; clean</li>\n    <li class=\"wf-step wf-visualise\">Visualise</li>\n    <li class=\"wf-step wf-describe\">Describe</li>\n    <li class=\"wf-step wf-uncertainty\">Quantify uncertainty</li>\n    <li class=\"wf-step wf-test\">Test</li>\n    <li class=\"wf-step wf-confounds\">Confounds</li>\n    <li class=\"wf-step wf-interpret\">Interpret</li>\n    <li class=\"wf-step wf-report\">Report</li>\n  </ol>\n</nav>\n```\n\n\n\n\n> Most playtest questions are about relationships: do players who die more find\n> the game harder? Do more aware players score more? This page covers how to see a\n> relationship (the scatterplot), how to measure it (correlation), how to describe\n> it as a line (simple linear regression), and the trap underneath all three:\n> **two things moving together does not mean one causes the other.** The playtest\n> question running through it: *\"Awareness is the strongest predictor of score.\n> Should we buff awareness?\"*\n\n::: {.at-a-glance}\n**Time:** 30 minutes in class, shared with [Visualising with ggplot2](09-visualising-with-ggplot2.qmd);\n25 more for regression and the Going further sections.\n**Before this:** [Visualising with ggplot2](09-visualising-with-ggplot2.qmd).\n**Key terms:** scatterplot, direction, form, strength, correlation, causation,\nconfounding variable, Simpson's paradox, simple linear regression, slope,\nintercept, residual, R², extrapolation, cross-tabulation.\n**R introduced:** `cor()`, `lm()`, `coef()`, `confint()`, `resid()`,\n`geom_point()`, `geom_smooth(method = \"lm\")`, `geom_bar(position = \"fill\")`.\n:::\n\n## Learning Outcomes\n\nBy the end of these notes you can:\n\n- read a scatterplot for direction, form and strength;\n- compute and interpret a correlation, and say why context decides whether it is\n  strong;\n- name what correlation cannot see, including curves, outliers and groups;\n- give three explanations other than cause for two things moving together;\n- identify a confounding variable, and explain Simpson's paradox with a\n  *Tidebreak* example;\n- fit a simple linear regression with `lm()`, and interpret its slope, intercept,\n  R² and residuals in plain English;\n- describe the relationship between two categorical variables with a\n  cross-tabulation;\n- critique a playtest whose conclusion does not follow from its design.\n\n---\n\n## Why This Matters for Playtesting\n\nComparing two builds was a controlled question: the team chose who played which.\nMost of what a playtest records is not controlled. Awareness, deaths, experience,\ndifficulty ratings: they all arrive together, and they all move together, because\nthey all come from the same players.\n\n**A relationship is a lead, not a finding.** \"Players with high awareness scored\nmore\" is true in the *Tidebreak* data, and it is tempting to read it as \"awareness\ncauses score, so buff awareness\". The data cannot say that. Better players may\nsimply be more aware *and* score more. The difference between those two readings\ndecides whether a balance patch helps or does nothing, and only careful reasoning,\nnot more computation, tells them apart ([rule 7](ten-rules.qmd)).\n\n---\n\n## Seeing a Relationship: the Scatterplot\n\nA **scatterplot** draws one point per observation, with one variable on each axis.\nDo players who die more rate the game as more difficult?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sessions, aes(x = deaths, y = difficulty)) +\n  geom_jitter(width = 0.15, height = 0.15, colour = pal$line, alpha = 0.6) +\n  labs(x = \"Deaths in the session\", y = \"Difficulty rating (1–7)\")\n```\n\n::: {.cell-output-display}\n![Deaths against the player's difficulty rating, one point per session. Points are jittered slightly because both variables are whole numbers.](10-relationships-and-regression_files/figure-html/fig-deaths-difficulty-1.png){#fig-deaths-difficulty fig-alt='Scatterplot of difficulty rating from 2 to 7 against deaths from 0 to 7. The cloud of points rises from lower left to upper right, with a lot of scatter.' width=768}\n:::\n:::\n\n\nRead a scatterplot for three things:\n\n- **Direction.** Do the points rise from left to right (**positive**: more of one,\n  more of the other) or fall (**negative**)? Here they rise.\n- **Form.** Do they follow a straight line, a curve, or no pattern at all? Here,\n  roughly a line.\n- **Strength.** How tightly do they cluster around that form? Here, loosely:\n  plenty of players died often and still rated the game easy.\n\n**In a report you would write:** \"Players who died more rated the game as harder,\nthough with wide variation between players.\"\n\n---\n\n## Measuring a Relationship: Correlation\n\nThe **correlation** coefficient, *r*, puts a number on direction and strength for a\n**straight-line** relationship. It runs from −1 to +1:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![What correlations look like. Each panel is 150 simulated points with the correlation shown.](10-relationships-and-regression_files/figure-html/fig-r-grid-1.png){#fig-r-grid fig-alt='Six scatterplots in a row, labelled r = −0.9, −0.5, −0.2, 0.2, 0.5 and 0.9. At −0.9 the points form a tight falling band; at ±0.2 they are an almost shapeless cloud; at 0.9 a tight rising band.' width=864}\n:::\n:::\n\n\n- **+1**: a perfect rising line. **−1**: a perfect falling line.\n- **0**: no straight-line relationship.\n- The further from 0, the more tightly the points follow a line.\n\n`cor()` computes it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(sessions$deaths, sessions$difficulty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5792729\n```\n\n\n:::\n:::\n\n\nr = 0.58: a clear positive relationship with a lot of scatter, which\nis what @fig-deaths-difficulty showed.\n\n**Which abilities go with score?** Correlating each against score at once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabilities <- c(\"accuracy\", \"mobility\", \"survivability\", \"objective_control\",\n               \"support\", \"awareness\", \"shots_fired\")\nround(sort(cor(sessions[, abilities], sessions$score)[, 1], decreasing = TRUE), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        awareness          mobility           support objective_control \n             0.59              0.29              0.15              0.09 \n      shots_fired          accuracy     survivability \n             0.05              0.03             -0.07 \n```\n\n\n:::\n:::\n\n\nAwareness is the strongest, at 0.59. Shots fired, the\nstatistic everyone assumes matters, is 0.05: no\nrelationship at all.\n\n**Context decides what counts as strong.** There is no universal cut-off. Between\ntwo measurements of the same thing, such as two raters scoring the same session,\n0.6 would be worryingly low. Between a single ability rating and a match outcome\nshaped by teammates, opponents and luck, 0.59 is large.\nSay what the number means for the question, not just whether it is \"strong\".\n\n::: {.callout-note collapse=\"true\" title=\"Going further: Spearman's correlation\"}\nThe usual correlation (Pearson's) measures straight-line relationships and is\npulled around by extreme values. **Spearman's correlation** ranks each variable\nfirst and correlates the ranks, so it measures whether one goes up when the other\ngoes up, in any form, and is robust to outliers. It suits ordinal data such as\nratings:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(sessions$deaths, sessions$difficulty, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5731608\n```\n\n\n:::\n:::\n\n:::\n\n---\n\n## What Correlation Cannot See\n\nA single number cannot describe a picture. In 1973 the statistician Francis\nAnscombe published four small datasets that make the point. They have almost\nidentical means, SDs and correlations, and they look nothing alike:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquartet <- do.call(rbind, lapply(1:4, function(i) {\n  data.frame(set = paste(\"Set\", i),\n             x = anscombe[[paste0(\"x\", i)]], y = anscombe[[paste0(\"y\", i)]])\n}))\nround(sapply(split(quartet, quartet$set), function(d) cor(d$x, d$y)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSet 1 Set 2 Set 3 Set 4 \n 0.82  0.82  0.82  0.82 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(quartet, aes(x, y)) +\n  geom_point(colour = pal$line, size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, colour = pal$highlight, linewidth = 0.8) +\n  facet_wrap(~ set, nrow = 1) +\n  labs(x = NULL, y = NULL)\n```\n\n::: {.cell-output-display}\n![Anscombe's quartet: four datasets with the same correlation, about 0.82, and four different stories.](10-relationships-and-regression_files/figure-html/fig-anscombe-1.png){#fig-anscombe fig-alt='Four scatterplots, each with a straight fitted line of the same slope. Set 1 is a loose linear cloud. Set 2 is a smooth curve. Set 3 is a perfect line with one outlier pulling the fit. Set 4 is a vertical stack of points with one far-right point creating the whole relationship.' width=768}\n:::\n:::\n\n\n`anscombe` ships with R. Only Set 1 is what r = 0.82 suggests. Set 2 is a curve,\nwhich r describes badly. In Set 3, one outlier drags the line away from an\notherwise perfect fit. In Set 4, a single point creates the entire relationship.\n\n**Always draw the scatterplot before quoting r** ([rule 4](ten-rules.qmd)).\nCorrelation sees only straight lines, is moved by single extreme points, and, as\nthe next two sections show, cannot see groups.\n\n---\n\n## Correlation Is Not Causation\n\nWhen two variables move together, there are always several explanations, and\n\"one causes the other\" is only one of them:\n\n| Explanation | Awareness and score |\n| :- | :- |\n| **A causes B** | Being aware of the map makes players score more |\n| **B causes A** | Players who are scoring well have more time to look around |\n| **Something else causes both** | Experienced players are both more aware and better at everything |\n| **Chance** | In a small sample, unrelated measures can line up by luck |\n\nA playtest observes; it does not intervene. Only a test in which you *change* one\nvariable and watch the other, such as giving half the players a better minimap at\nrandom, can separate the first explanation from the rest. Until then, write \"is\nassociated with\", never \"causes\" or \"drives\".\n\n---\n\n## Confounding and Simpson's Paradox\n\nA **confounding variable** is a third variable that drives both of the variables\nyou are comparing, creating or hiding a relationship between them.\n\n```{mermaid}\n%%| label: fig-confounder\n%%| fig-cap: \"A confounder drives both variables. The relationship you see between them may come entirely from it.\"\nflowchart TD\n  E[\"Experience<br/>(cohort)\"] --> A[\"Awareness\"]\n  E --> S[\"Score\"]\n  A -.->|\"the relationship<br/>you observe\"| S\n  classDef c fill:#fbeaea,stroke:#b22222,color:#212529\n  classDef v fill:#f8f9fa,stroke:#6c757d,color:#212529\n  class E c\n  class A,S v\n```\n\n**Experience is a candidate confounder for awareness and score.** Veterans average\n75.6 awareness against 57.3 for Novices,\nand a median score of 1664 against 1281.\nSome of the awareness–score relationship is experience. Checking within each\ncohort, the relationship survives:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(split(sessions, sessions$cohort),\n       function(d) cor(d$awareness, d$score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Novice   Regular   Veteran \n0.5389460 0.4774983 0.4450546 \n```\n\n\n:::\n:::\n\n\nFrom 0.45 to 0.54\nwithin each cohort: experience is part of the story, not all of it. That is how you\ncheck a suspected confounder: **split by it, and see whether the relationship\nholds inside each group.**\n\n### When the relationship reverses\n\nSometimes splitting by the confounder does not just weaken a relationship; it\nreverses it. That is **Simpson's paradox**, and *Tidebreak* has a clear case.\nAcross all players, mobility and survivability have a correlation of\n-0.66: faster players are more fragile. Within each archetype:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboth <- rbind(\n  data.frame(sessions[, c(\"mobility\", \"survivability\", \"archetype\")], panel = \"All players\"),\n  data.frame(sessions[, c(\"mobility\", \"survivability\", \"archetype\")], panel = \"By archetype\")\n)\nggplot(both, aes(mobility, survivability)) +\n  geom_point(aes(colour = ifelse(panel == \"All players\", \"All\", archetype)), alpha = 0.7) +\n  geom_smooth(data = subset(both, panel == \"All players\"), method = \"lm\",\n              se = FALSE, colour = \"black\") +\n  geom_smooth(data = subset(both, panel == \"By archetype\"),\n              aes(colour = archetype), method = \"lm\", se = FALSE) +\n  scale_colour_manual(values = c(All = \"grey60\", Duelist = \"#3a5f8a\",\n                                 Engineer = \"#6c9a3c\", Scout = \"#b22222\",\n                                 Sentinel = \"#8a5a9c\"),\n                      breaks = c(\"Duelist\", \"Engineer\", \"Scout\", \"Sentinel\")) +\n  facet_wrap(~ panel) +\n  labs(x = \"Mobility rating\", y = \"Survivability rating\", colour = \"Archetype\")\n```\n\n::: {.cell-output-display}\n![Mobility against survivability. Left: all players, a falling trend. Right: the same points coloured by archetype, each with its own rising trend.](10-relationships-and-regression_files/figure-html/fig-simpson-1.png){#fig-simpson fig-alt='Two scatterplots of survivability against mobility. Left: one black falling trend line through all the points. Right: the points form four separate clusters by archetype, Scout at high mobility and low survivability, Sentinel the reverse, and within each cluster the fitted line rises.' width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(split(sessions, sessions$archetype),\n       function(d) cor(d$mobility, d$survivability))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Duelist  Engineer     Scout  Sentinel \n0.3015591 0.5117941 0.4648070 0.5979612 \n```\n\n\n:::\n:::\n\n\nWithin every archetype the correlation is **positive**, from\n0.3 to 0.6. The overall falling trend\nis the gap *between* archetypes: Scouts are built fast and fragile, Sentinels slow\nand tough. Within any one archetype, better players are better at both.\n**Archetype is the confounder**, and ignoring it reverses the conclusion. A patch\nthat \"makes fast players more fragile\" would punish exactly the players who are\nplaying their role well. This is Lab 03, Exercise 07.\n\n---\n\n## Simple Linear Regression\n\nCorrelation says how tightly two variables follow a line. **Simple linear\nregression** finds that line, and so answers a more useful question: *how much does\none variable change, on average, for each unit of the other?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(score ~ awareness, data = sessions)\ncoef(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   awareness \n  426.13072    15.15319 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 %    97.5 %\n(Intercept) 172.1697 680.09176\nawareness    11.3806  18.92578\n```\n\n\n:::\n:::\n\n\n`lm()` stands for *linear model*. `score ~ awareness` reads \"score as explained by\nawareness\", the same formula style as `boxplot(y ~ group)`. The result describes a\nstraight line:\n\n$$\\text{predicted score} = 426 + 15.2 \\times \\text{awareness}$$\n\n**The slope** is the number that matters: each extra point of awareness goes with\n15.2 more points of score, on average (95% CI\n11.4 to 18.9). It is in the units of the\nquestion, so a designer can use it: the\n18-point gap in average\nawareness between Novices and Veterans goes with about\n280 points of\nscore.\n\n**The intercept** is the predicted score at awareness zero:\n426. No player has an awareness anywhere near zero (the lowest is\n38), so it means nothing on its own; it just anchors the\nline.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions$predicted <- fitted(fit)\nsessions$residual  <- resid(fit)\nggplot(sessions, aes(awareness, score)) +\n  geom_segment(aes(xend = awareness, yend = predicted), colour = \"grey75\") +\n  geom_point(aes(colour = residual < -600), size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, colour = pal$highlight) +\n  scale_colour_manual(values = c(`FALSE` = pal$line, `TRUE` = \"#8a5a9c\"),\n                      labels = c(\"Other sessions\", \"Residual below −600\"), name = NULL) +\n  labs(x = \"Awareness rating\", y = \"Score\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Score against awareness, with the regression line. Each grey segment is a residual: the gap between a session's actual score and the line's prediction.](10-relationships-and-regression_files/figure-html/fig-regression-1.png){#fig-regression fig-alt='Scatterplot of score against awareness with a rising red line. Short grey vertical segments join each point to the line. A handful of points sit far below the line at the bottom, with long segments, coloured differently from the rest.' width=768}\n:::\n:::\n\n\n**A residual** is the gap between what actually happened and what the line\npredicted: actual minus predicted. The line is chosen to make the residuals, taken\ntogether, as small as possible (it minimises the sum of their squares, hence\n\"least squares\"). `geom_smooth(method = \"lm\")` draws the same line.\n\n**Residuals are where the findings hide.** The seven sessions furthest *below* the\nline, the ones that scored far less than their awareness predicted, include\n6 Sentinels. The regression has found the\nSentinel collapses from [Describing Variables](04-describing-variables.qmd#worked-example)\non its own: those games are not explained by awareness at all.\n\n**R²**, the **coefficient of determination**, is the share of the variation in score\nthat the line accounts for: 0.35, or 35%. For a simple\nregression it is exactly the correlation squared\n(0.59² = 0.35). Awareness accounts for about\na third of the differences in score; the other two thirds are everything else.\n\n**Predicting, carefully.** The line predicts a score of about\n1640 for awareness 80. That\nprediction is an average for players like that, not a promise for any one player,\nwhose residual could easily be 260 points either way. And\n**never predict outside the data**: the line knows nothing about awareness below\n38 or above 95. Using it there is\n**extrapolation**, and the straight line may not continue.\n\n**A regression is still a correlation.** A steep, significant slope says awareness\nand score move together, by this much. It does not say that raising a player's\nawareness would raise their score. Every warning in the previous two sections\napplies unchanged.\n\n::: {.callout-note collapse=\"true\" title=\"Going further: reading the full summary\"}\n`summary(fit)` prints everything at once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = score ~ awareness, data = sessions)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1021.08   -97.01    18.49   183.27   436.30 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  426.131    128.246   3.323  0.00119 ** \nawareness     15.153      1.905   7.954 1.22e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 258.6 on 118 degrees of freedom\nMultiple R-squared:  0.349,\tAdjusted R-squared:  0.3435 \nF-statistic: 63.27 on 1 and 118 DF,  p-value: 1.223e-12\n```\n\n\n:::\n:::\n\n\nThe `awareness` row of the **Coefficients** table gives the slope, its standard\nerror and a p-value testing whether the true slope could be zero. **Multiple\nR-squared** is R². Regression with several predictors at once (multiple\nregression) can adjust for a confounder such as cohort, but it is beyond this\nmodule, and adjusting for the confounders you measured does not protect you from\nthe ones you did not.\n:::\n\n---\n\n## Two Categorical Variables\n\nWhen both variables are categories, the relationship is a **cross-tabulation**,\nread through **row proportions** so that groups of different sizes compare fairly.\nDo more experienced players quit in frustration less?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(prop.table(table(sessions$cohort, sessions$quit_reason), 1), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n          Completed test Frustrated Lost interest Technical fault\n  Novice            0.70       0.18          0.09            0.03\n  Regular           0.51       0.26          0.15            0.08\n  Veteran           0.56       0.15          0.29            0.00\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sessions, aes(x = cohort, fill = quit_reason)) +\n  geom_bar(position = \"fill\") +\n  scale_y_continuous(labels = function(x) paste0(x * 100, \"%\")) +\n  scale_fill_manual(values = c(\"grey80\", \"#b22222\", \"#9bb0c9\", \"grey40\")) +\n  labs(x = \"Cohort\", y = \"Share of sessions\", fill = \"How the session ended\")\n```\n\n::: {.cell-output-display}\n![How sessions ended, by cohort. Each bar is one cohort, scaled to 100%.](10-relationships-and-regression_files/figure-html/fig-crosstab-1.png){#fig-crosstab fig-alt='Three stacked bars, one per cohort, each split into completed test, frustrated, lost interest and technical fault. Regulars have the largest frustrated segment; Veterans the largest lost-interest segment.' width=768}\n:::\n:::\n\n\n`position = \"fill\"` scales every bar to 100%, the picture of row proportions.\n\nNot in a straight line. **Regulars** quit in frustration most often,\n26% of their sessions, against\n18% for Novices and\n15% for Veterans. Veterans more often simply\nlost interest. A relationship between categories does not have to be \"more of A,\nmore of B\", which is one reason correlation is the wrong tool here.\n\n---\n\n## Critiquing a Playtest\n\nEvery one of these ideas comes together when a conclusion is drawn from data that\ncannot support it. Two scenarios to take apart.\n\n**Scenario 1.** *A team adds an optional minimap. Players who turned it on scored\n22% higher than players who left it off. The team makes the minimap mandatory.*\n\n::: {.callout-note collapse=\"true\" title=\"What is wrong\"}\nPlayers chose whether to use the minimap, so the two groups differ in more than the\nminimap. Experienced, engaged players are more likely to explore the options menu\n*and* more likely to score well: a confounder. The 22% may be entirely skill. To\nknow what the minimap does, assign it at random, or have every player try both,\ncounterbalanced ([Planning a Playtest](01-planning-a-playtest.qmd#random-assignment)).\n:::\n\n**Scenario 2.** *The new build was tested on Friday evening with fans recruited\nfrom the studio Discord; the old build on Monday morning with first-year students.\nEnjoyment was 1.5 points higher for the new build, p < 0.001. The team reports that\nthe new build is more enjoyable.*\n\n::: {.callout-note collapse=\"true\" title=\"What is wrong\"}\nBuild is confounded with everything else that differed: the players (committed fans\nagainst strangers), the time of day, and probably the room and who ran the session.\nAny of them could produce the gap. The p-value says the gap is unlikely to be\nchance; it says nothing about *which* of the differences caused it. The fix is to\nrecruit one group and assign builds at random within it, at the same times, in the\nsame room.\n:::\n\n---\n\n## Worked Example\n\n**Should we buff awareness?** The balance designer has seen that awareness is the\nstrongest predictor of score and proposes raising every archetype's base awareness.\n\n**Step 1: look.** The scatterplot (@fig-regression) shows a clear rising\nrelationship, with a cluster of sessions far below the line.\n\n**Step 2: measure.** r = 0.59, the strongest of the\nability ratings. The slope is 15.2 points of score per awareness point\n(95% CI 11.4 to 18.9), and awareness accounts\nfor 35% of the variation in score.\n\n**Step 3: ask what else could explain it.** Experience: Veterans have more of both.\nWithin each cohort the relationship weakens but survives\n(0.45 to 0.54), so\nexperience is part of the story. But a player's awareness *rating* may measure\nskill as much as cause it: good players notice more because they are good.\n\n**Step 4: look at the residuals.** The biggest misses are Sentinel collapses, which\nawareness does not explain at all. A buff to awareness does nothing for them.\n\n**Step 5: conclude.** The data shows an association, by a useful amount. It does not\nshow that raising awareness would raise score. The defensible recommendation is a\ntest, not a patch: give half the players a feature that raises awareness, such as a\nclearer minimap or audio cues, at random, and measure score in both groups.\n\n---\n\n## Interpretation Guidance\n\n**What the data shows.** Score rises with awareness: about 15.2 points\nper awareness point, r = 0.59, across\n120 sessions.\n\n**What the analysis suggests.** Awareness, or whatever awareness ratings reflect,\nmatters to how a match goes. Experience explains part of the relationship but not\nall of it.\n\n**What can legitimately be concluded.** An association, not a cause. A design\nchange aimed at awareness is worth testing; it is not yet supported as a fix.\n\n**Use the right verbs.** \"Is associated with\", \"goes with\", \"predicts\" for\nrelationships in observed data. \"Causes\", \"drives\", \"improves\" only after an\nexperiment that changed one variable on purpose.\n\n---\n\n## Common Mistakes\n\n**Quoting r without the scatterplot.** Anscombe's four datasets share a correlation\nand nothing else ([rule 4](ten-rules.qmd)).\n\n**Reading correlation as cause.** Two things moving together has at least four\nexplanations. Name the alternatives before choosing one.\n\n**Ignoring groups.** A relationship across groups can vanish or reverse within\nthem. Split by the obvious confounders, such as archetype, cohort or build.\n\n**Calling r \"strong\" or \"weak\" without context.** Say what it means for the\nquestion.\n\n**Interpreting the intercept when zero is impossible.** No player has zero\nawareness. The intercept anchors the line; it is not a finding.\n\n**Extrapolating.** The line describes the range of the data, not beyond it.\n\n**Treating a prediction as a promise.** A regression line predicts an average;\nindividual players scatter around it by the residual SD.\n\n**Using correlation on categories.** Two categorical variables need a\ncross-tabulation, not `cor()`.\n\n---\n\n## Practice\n\nEach takes two or three minutes.\n\n**1. Predict.** Before computing it: is the correlation between `kills` and\n`score` closer to 0, 0.5 or 0.9? Then check.\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(sessions$kills, sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06510531\n```\n\n\n:::\n:::\n\n\nClose to 0, 0.07, which surprises\nmost people. In *Tidebreak*, score tracks staying alive (time alive correlates at\n0.43 with score) far more than\nit tracks kills. A number you were sure about is exactly the one to check.\n:::\n\n**2. Compute.** Fit a regression of `score` on `deaths`. Interpret the slope in one\nsentence a designer could use, and compare its R² with awareness's.\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_d <- lm(score ~ deaths, data = sessions)\ncoef(fit_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      deaths \n  1779.8824   -116.7144 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_d)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3156496\n```\n\n\n:::\n:::\n\n\nEach extra death goes with about 117\nfewer points of score, on average. R² is\n0.32, a little below\nawareness's 0.35. The same caution applies: dying more and scoring less\nmay both come from being outplayed.\n:::\n\n**3. Critique.** \"Wrong turns correlate at\n-0.07 with enjoyment, so\ngetting lost does not affect how much players enjoy the game.\" What is wrong with\nthat conclusion?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\nA correlation near zero means no *straight-line* relationship across all sessions.\nIt does not rule out a curve, a relationship within one build or cohort that is\ncancelled out by another, or an effect on a different outcome (players who got lost\nmay have quit, and quitters' enjoyment could be missing or lower). Draw the\nscatterplot, split by build, and look at quit reason too before concluding\nanything.\n:::\n\n**4. Decide.** A designer reads the regression and says: \"If we raise a Novice's\nawareness by 20 points, they will score about 300 more.\" Give two\nreasons to doubt it.\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\nFirst, the slope is an association across players, not the effect of changing one\nplayer: awareness ratings may reflect skill rather than cause it. Second, it is an\naverage: individual players scatter around the line by about\n260 points. A third reason, if the Novice starts low: their raised\nawareness may still be in a range where the data is thin.\n:::\n\n---\n\n## Summary\n\n- A scatterplot shows a relationship's direction, form and strength. Draw it first.\n- Correlation, from −1 to +1, measures straight-line relationships. It misses\n  curves, is moved by outliers, and cannot see groups. Context decides \"strong\".\n- Correlation is not causation: the reverse direction, a third variable or chance\n  can produce the same pattern.\n- A confounder drives both variables. Check by splitting into groups; Simpson's\n  paradox is when the relationship reverses inside them.\n- Simple linear regression, `lm(y ~ x)`, fits a line. The slope is the change in y\n  per unit of x; R² is the share of variation explained; residuals are where the\n  unexplained cases, often the findings, sit.\n- Do not interpret an impossible intercept or extrapolate beyond the data.\n- Two categorical variables: cross-tabulation with row proportions.\n\n| Key term | Meaning |\n| :- | :- |\n| **Scatterplot** | One point per observation, for two numeric variables |\n| **Correlation (r)** | −1 to +1: direction and strength of a straight-line relationship |\n| **Causation** | One variable changing another; needs an experiment to show |\n| **Confounding variable** | A third variable that drives both variables you are comparing |\n| **Simpson's paradox** | A relationship that reverses when the data is split into groups |\n| **Simple linear regression** | Fitting the straight line that best predicts y from x |\n| **Slope** | The change in y, on average, for each unit increase in x |\n| **Intercept** | The line's predicted y when x is zero |\n| **Residual** | Actual minus predicted |\n| **R²** | The share of the variation in y the line accounts for |\n| **Extrapolation** | Predicting outside the range of the data |\n| **Cross-tabulation** | Counts of every combination of two categorical variables |\n\n---\n\n## Links\n\n- [Ten Rules](ten-rules.qmd): rule 4 (look at the shape before you quote the\n  average) and rule 7 (compare distributions, not averages)\n- [Statistics Reference: relationships](../reference/reference-statistics.qmd#relationships)\n- [ggplot2 Reference](../reference/reference-ggplot2.qmd)\n- [Lab 03: Complete Analysis](../labs/complete-analysis.qmd), Part A\n- [Week 3 demo](../demos/week-3.qmd)\n- Next: [Interpreting and Reporting Evidence](11-reporting-evidence.qmd)\n\n---\n\n## Reflective Questions\n\n- Name a relationship in your own game's telemetry that you suspect is confounded.\n  What is the confounder, and how would you check?\n- The awareness regression explains about a third of the variation in score. Is\n  that a lot or a little for a game outcome? What would you expect the other two\n  thirds to be?\n- Simpson's paradox reversed the mobility–survivability relationship. What other\n  grouping in a game could hide or reverse a relationship in the same way?\n- Your producer wants a single sentence for the balance meeting about awareness.\n  Write it, using only what the data can support.\n",
    "supporting": [
      "10-relationships-and-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}