{
  "hash": "21547e75de8953e45d2e906c5a8247a5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 05 — From Evidence to Report\"\nsubtitle: \"Stage 4 workshop: one complete finding, from Tidebreak and then from your own game\"\n---\n\n::: {.callout-note appearance=\"simple\" icon=\"false\" title=\"Get the files\"}\n- **Data:** [tidebreak_sessions.csv](../data/tidebreak_sessions.csv){download=\"tidebreak_sessions.csv\"}, [tidebreak_survey.csv](../data/tidebreak_survey.csv){download=\"tidebreak_survey.csv\"}. Save them in the `data/` folder of your project.\n:::\n\n# Overview\n\nThis is the last lab, and it is a workshop. It brings the whole course together\ninto the thing your assessment needs:\n\n> **One complete finding: research question → relevant data →\n> descriptive, visual and statistical evidence → interpretation →\n> evidence-backed recommendation, written under the report headings.**\n\nPart A works through one finding on *Tidebreak*, quickly: does environmental\nguidance improve navigation without reducing enjoyment? It adds the two things\nStage 4 is about, coding comments and triangulating evidence, and ends with a\n`report.qmd` that renders. Part B is your project. Bring your team's data and your\ndraft report.\n\n| Function | What it does |\n| :- | :- |\n| `pivot_longer()` | Reshape wide survey columns into long rows |\n| `left_join()` | Add columns from another table, matched on a key |\n| `case_when()`, `grepl()` | Give each comment a code |\n| `` `r ` `` inline code | Put a computed number into a sentence |\n| `quarto render` | Turn `report.qmd` into HTML |\n\n# Learning outcomes\n\nBy the end of this lab you can:\n\n- summarise every survey item by build, and decide what a result lets you claim;\n- code free-text comments with a short codebook, and count the codes;\n- triangulate telemetry, ratings and comments, and report a disagreement honestly;\n- build a report in Quarto under the assessment headings, with every number\n  computed, and render it;\n- write a complete finding from your own game, from question to recommendation.\n\n# Ground rules\n\n- Part B is the point. Keep Part A moving; the solutions are there to be read if\n  time is short.\n- No number goes into the report by hand. If it is a number, it is inline R.\n- Results reports; Discussion judges. Keep them apart.\n- Every finding ends with an Action someone could start on tomorrow\n  ([rule 10](../notes/ten-rules.qmd)).\n- If `library(tidyr)` fails, run `install.packages(\"tidyr\")` once in the Console.\n\n# Setup (run this first)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\n\nsessions <- read_csv(\"data/tidebreak_sessions.csv\", show_col_types = FALSE)\nsurvey   <- read_csv(\"data/tidebreak_survey.csv\", show_col_types = FALSE)\n\nnrow(sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120   9\n```\n\n\n:::\n:::\n\n\n`sessions` is the cleaned session data: one row per player per session, each player\non one build. `survey` is the post-session questionnaire: one row per session,\neight agreement items rated 1 to 5.\n\n---\n\n# Part A — One finding, on Tidebreak\n\nNotes for this part:\n[Interpreting and Reporting Evidence](../notes/11-reporting-evidence.qmd) and\n[Combining Evidence](../notes/12-combining-evidence.qmd).\n\n## Exercise 01 — Every survey item, both builds `[Apply]`\n\nReshape `survey` long, join each session's `build` onto it, and find the proportion\nof players agreeing (4 or 5) with each item in each build. Which item moved most\nbetween the builds?\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong <- survey |>\n  pivot_longer(-session_id, names_to = \"item\", values_to = \"rating\")\n\nagree_by_build <- long |>\n  left_join(select(sessions, session_id, build), by = \"session_id\") |>\n  group_by(item, build) |>\n  summarise(agree = mean(rating >= 4), .groups = \"drop\") |>\n  pivot_wider(names_from = build, values_from = agree) |>\n  mutate(change = B - A) |>\n  arrange(desc(abs(change)))\n\nagree_by_build\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  item                     A     B  change\n  <chr>                <dbl> <dbl>   <dbl>\n1 objective_clear     0.0833 0.383  0.3   \n2 match_length        0.7    0.817  0.117 \n3 death_understood    0.267  0.167 -0.1   \n4 controls_responsive 0.717  0.8    0.0833\n5 level_navigable     0.35   0.433  0.0833\n6 would_play_again    0.5    0.517  0.0167\n7 difficulty_fair     0.317  0.3   -0.0167\n8 visual_style        0.933  0.933  0     \n```\n\n\n:::\n:::\n\n\n`pivot_longer()` makes `item` a column so one `group_by()` covers every item.\n`pivot_wider()` puts the two builds side by side so the change is one subtraction\n([Reshaping and Joining](../going-further/reshaping-and-joining.qmd)).\n:::\n\n**Write 2 sentences:** `objective_clear` moved most. Which item would you have\n*expected* to move most, given what Build B changed, and did it?\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show answer\"}\n\n\n::: {.cell}\n\n:::\n\n\n`level_navigable`, since Build B added guidance to help players navigate. It moved\nfrom 35% agreeing to 43%, against\n`objective_clear`'s 8% to 38%. Build B\ncut wrong turns, but what players noticed was knowing where they were meant to go.\n:::\n\n## Exercise 02 — \"Without reducing enjoyment\" `[Decide]`\n\nThe research question has two halves. Test the second: did Build B reduce\nenjoyment? Use `enjoyment` from `sessions` (1–7) and `would_play_again` from\nExercise 01, and decide what the report may claim.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenjoy <- t.test(enjoyment ~ build, data = sessions)\nenjoy$estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean in group A mean in group B \n       3.933333        3.933333 \n```\n\n\n:::\n\n```{.r .cell-code}\nenjoy$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.3483742  0.3483742\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nagree_by_build |> filter(item == \"would_play_again\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  item                 A     B change\n  <chr>            <dbl> <dbl>  <dbl>\n1 would_play_again   0.5 0.517 0.0167\n```\n\n\n:::\n:::\n\n\n\n\n**One defensible answer: the report may claim no meaningful reduction.** Mean\nenjoyment was 3.93 in Build A and\n3.93 in Build B. The 95% confidence interval for the\ndifference runs from -0.35 to\n0.35 on a seven-point scale, so any true difference is\nsmall. Agreement with `would_play_again` was 50% and\n52%. Two different measures agree.\n\n**What makes it defensible.** It rests on an interval, not on \"not significant\",\nand on two measures rather than one. It claims *no meaningful reduction*, which the\nevidence supports, rather than *no effect*, which no test can show.\n\n**What would make it indefensible.** \"The p-value is above 0.05, so Build B has no\neffect on enjoyment.\" Or \"Build B is just as enjoyable\" from one measure with no\ninterval.\n:::\n\n**Write 2 sentences:** both measures were taken straight after one session. What\nwould you need to know before claiming Build B is as enjoyable over a week of play?\n\n## Exercise 03 — Code the comments `[Apply]`\n\nRead every distinct comment with `count(comment)`. Then give each session one of\nfour codes, *Lost or unclear*, *Found the way*, *Difficulty* or *General*, using\n`case_when()` and `grepl()`. Check every distinct comment against its code, then\ncount the codes by build.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |> count(comment, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   comment                                     n\n   <chr>                                   <int>\n 1 Died a lot but it felt fair.               22\n 2 Ran in circles for a while.                16\n 3 Got lost after the first room.             15\n 4 No idea what the objective was.            13\n 5 Too hard for a first attempt.              13\n 6 Could not tell where I was meant to go.    10\n 7 Enjoyed it, would play again.              10\n 8 Lighting made the exit easy to spot.       10\n 9 The route was obvious this time.            6\n10 The signposting helped.                     5\n```\n\n\n:::\n\n```{.r .cell-code}\ncoded <- sessions |>\n  mutate(code = case_when(\n    grepl(\"lost|circles|meant to go|objective\", comment) ~ \"Lost or unclear\",\n    grepl(\"route|exit|signposting\", comment)             ~ \"Found the way\",\n    grepl(\"Died|hard\", comment)                          ~ \"Difficulty\",\n    TRUE                                                 ~ \"General\"\n  ))\n\ncoded |> distinct(comment, code)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   comment                                 code           \n   <chr>                                   <chr>          \n 1 Could not tell where I was meant to go. Lost or unclear\n 2 The signposting helped.                 Found the way  \n 3 Lighting made the exit easy to spot.    Found the way  \n 4 Got lost after the first room.          Lost or unclear\n 5 Too hard for a first attempt.           Difficulty     \n 6 Died a lot but it felt fair.            Difficulty     \n 7 Ran in circles for a while.             Lost or unclear\n 8 The route was obvious this time.        Found the way  \n 9 No idea what the objective was.         Lost or unclear\n10 Enjoyed it, would play again.           General        \n```\n\n\n:::\n\n```{.r .cell-code}\ncoded |> count(code, build)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  code            build     n\n  <chr>           <chr> <int>\n1 Difficulty      A        19\n2 Difficulty      B        16\n3 Found the way   A        12\n4 Found the way   B         9\n5 General         A         6\n6 General         B         4\n7 Lost or unclear A        23\n8 Lost or unclear B        31\n```\n\n\n:::\n:::\n\n\n`case_when()` gives each comment the first code whose keywords it contains;\n`TRUE ~ \"General\"` catches the rest. `distinct(comment, code)` is the check by\nhand: every sentence next to the code it got.\n:::\n\n**Write 1 sentence:** write the codebook entry for *Lost or unclear*: what counts,\nand one example.\n\n## Exercise 04 — Do the sources agree? `[Decide]`\n\n\n\nThe telemetry says Build B players took far fewer wrong turns. Compare that with\nthe comment codes from Exercise 03, by build and then by whether the player\nenjoyed the session (`enjoyment >= 5`). Decide what the report should say about\nnavigation, and which evidence it should trust for what.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  group_by(build) |>\n  summarise(mean_wrong_turns = mean(wrong_turns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  build mean_wrong_turns\n  <chr>            <dbl>\n1 A                 8.92\n2 B                 5.52\n```\n\n\n:::\n\n```{.r .cell-code}\ncoded |> count(code, build)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  code            build     n\n  <chr>           <chr> <int>\n1 Difficulty      A        19\n2 Difficulty      B        16\n3 Found the way   A        12\n4 Found the way   B         9\n5 General         A         6\n6 General         B         4\n7 Lost or unclear A        23\n8 Lost or unclear B        31\n```\n\n\n:::\n\n```{.r .cell-code}\ncoded |> count(code, enjoyed = enjoyment >= 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  code            enjoyed     n\n  <chr>           <lgl>   <int>\n1 Difficulty      FALSE      35\n2 Found the way   TRUE       21\n3 General         TRUE       10\n4 Lost or unclear FALSE      54\n```\n\n\n:::\n:::\n\n\n**The sources disagree.** Build B players took fewer wrong turns, yet\n31 Build B comments were coded *lost or unclear*, against\n23 in Build A. Split by enjoyment instead of build, the codes separate\ncleanly: every *lost or unclear* comment came from a player who rated enjoyment\nbelow 5, and every *found the way* comment from one who rated it 5 or above.\n\n**One defensible answer.** Trust the telemetry for *what happened*: Build B reduced\nwrong turns. Treat the comments as evidence about *how the session felt*: they\ntrack enjoyment, not build. Report both, in Results, and explain the gap in the\nDiscussion. Recommend structured observation at the junctions in the next playtest,\nbecause nothing in this data shows whether players notice when they are lost.\n\n**What would make it indefensible.** Leaving the comments out because they spoil\nthe story, or reporting them as evidence that Build B made navigation worse.\n:::\n\n**Write 4 sentences**, using **What → Pattern → Meaning → Action**, for the\ndisagreement.\n\n## Exercise 05 — Start the report, and render it `[Apply]`\n\nCreate `report.qmd` in the project folder, next to `data/`. Give it:\n\n- a YAML header with a title;\n- the eight assessment headings: Executive Summary, Introduction, Methodology,\n  Results, Discussion, Conclusion, References, Appendices;\n- a setup chunk, hidden with `echo: false`, that loads the libraries and both CSVs;\n- under Introduction, the research question;\n- under Methodology, one sentence giving the number of sessions and players, both\n  as inline R;\n- under Results, the navigation figure from [Lab 03](clinic-figures.qmd),\n  Exercise 03, with a caption that states the takeaway.\n\nThen render it from the Terminal with `quarto render report.qmd` and open\n`report.html`.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n````markdown\n---\ntitle: \"Tidebreak Build B: Playtest Report\"\n---\n\n```{{r}}\n#| echo: false\nlibrary(readr)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\n\nsessions <- read_csv(\"data/tidebreak_sessions.csv\", show_col_types = FALSE)\nsurvey   <- read_csv(\"data/tidebreak_survey.csv\", show_col_types = FALSE)\n```\n\n## Executive Summary\n\n## Introduction\n\nDoes environmental guidance improve navigation without reducing enjoyment?\n\n## Methodology\n\nWe analysed `r nrow(sessions)` sessions from\n`r length(unique(sessions$player_id))` players, each of whom\nplayed one build only.\n\n## Results\n\n```{{r}}\n#| label: fig-wrong-turns\n#| fig-cap: \"Players made fewer wrong turns in Build B.\"\n#| echo: false\nggplot(sessions, aes(x = wrong_turns)) +\n  geom_histogram(binwidth = 1, fill = \"grey60\", colour = \"white\") +\n  facet_wrap(~ build, ncol = 1) +\n  labs(title = \"Wrong turns per session, by build\",\n       x = \"Wrong turns\", y = \"Sessions\")\n```\n\n## Discussion\n\n## Conclusion\n\n## References\n\n## Appendices\n````\n\nThe two inline expressions produce these values when the report renders:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(unique(sessions$player_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30\n```\n\n\n:::\n:::\n\n\n`echo: false` hides the code and keeps its output, which is what a reader of a\nreport wants. Because the numbers are inline, the report corrects itself the next\ntime the data changes.\n:::\n\n**Write 2 sentences:** change one value in your copy of the CSV, render again, and\ndescribe what changed in the report and what you did not have to do.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"What you should see\"}\nThe terminal ends with `Output created: report.html`. The page shows eight\nheadings, the sentence under Methodology reads \"120 sessions from\n30 players\", and the two-panel histogram sits\nunder Results with its caption and no code above it.\n\nIf the render stops with an error, the message names the line. The most common\ncauses are a data path written as `../data/...`, a chunk that uses a package it\ndid not load, and a missing closing ```` ``` ````.\n:::\n\n## Exercise 06 — Discussion, Conclusion and Executive Summary `[Decide]`\n\nWrite the last three pieces of the *Tidebreak* report. Every number is inline R.\n\n- **Discussion:** whether the reduction in wrong turns matters to the player; the\n  disagreement from Exercise 04; and at least three limitations specific to this\n  playtest.\n- **Conclusion:** one finding in **What → Pattern → Meaning → Action** form that\n  answers the research question.\n- **Executive Summary:** the question, the finding and the action, in three\n  sentences. Write it last.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwt <- t.test(wrong_turns ~ build, data = sessions)\nwt$estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean in group A mean in group B \n       8.916667        5.516667 \n```\n\n\n:::\n\n```{.r .cell-code}\nwt$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.480141 4.319859\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nsessions |> count(cohort, build)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  cohort  build     n\n  <chr>   <chr> <int>\n1 Novice  A        18\n2 Novice  B        15\n3 Regular A        26\n4 Regular B        27\n5 Veteran A        16\n6 Veteran B        18\n```\n\n\n:::\n:::\n\n\n\n\n**One defensible Discussion.**\n\n> A reduction of 3.4 wrong turns per\n> session is large enough for players to notice, and enjoyment did not fall. The\n> comments disagree with the telemetry, but they track enjoyment rather than\n> build, so we treat them as evidence about how sessions felt, not about\n> navigation.\n>\n> Limitations:\n>\n> - Each of the 30 players contributed 4 sessions, so the\n>   120 sessions are not independent; the result holds when each\n>   player counts once.\n> - Every measure was taken after one session. Nothing here shows whether the\n>   difference lasts.\n> - Cohorts were not perfectly balanced between the builds; the cohort table is in\n>   the appendices so the reader can judge.\n> - No observation was recorded, so we cannot say whether players noticed when\n>   they were lost.\n\n**One defensible Conclusion.**\n\n> **What.** Wrong turns per session in 120 sessions, and enjoyment\n> on a seven-point scale, compared between Build A and Build B.\n>\n> **Pattern.** Build B players averaged 5.5 wrong turns\n> against Build A's 8.9, a reduction of between\n> 2.5 and 4.3 per session at 95%\n> confidence. Enjoyment was unchanged, with a mean of\n> 3.93 in both builds.\n>\n> **Meaning.** The guidance works, and costs nothing players noticed.\n>\n> **Action.** Keep Build B's guidance and carry it into the next build. Retest\n> with an on-screen objective added, since objective clarity was the survey item\n> that moved most, and add an observation sheet at the first two junctions.\n\n**One defensible Executive Summary.**\n\n> Build B's environmental guidance cut wrong turns by about\n> 3.4 per session without reducing\n> enjoyment. Players' comments did not reflect the improvement, because they track\n> how a session felt rather than where the player went. Keep the guidance, add an\n> on-screen objective, and observe the junctions in the next playtest.\n\n**What makes it defensible.** The limitations are specific to this data, and say\nwhat was checked. The Conclusion's Action follows from its Meaning, and its\nPattern gives a size and an interval. The Executive Summary stands on its own.\n\n**What would make it indefensible.** \"The sample was small\" as the only\nlimitation; a Conclusion whose Action (\"improve the level\") no one could start on;\nor an Executive Summary that describes the method instead of the finding.\n:::\n\n**Write 3 sentences:** which limitation would most change your Action if it turned\nout to matter, and how would you test it?\n\n---\n\n# Part B — One complete finding from your own game `[Decide]`\n\nThis is the part that matters. Allow at least half the workshop for it.\n\nWork in your team's `report.qmd`. Pick **one** design question your playtest can\nanswer, and take it all the way through:\n\n1. **Research question** (Introduction). One sentence a designer would recognise.\n2. **Relevant data** (Methodology). Which measures, from which sources, on how many\n   players and sessions. Point to your cleaning log.\n3. **Evidence** (Results). Descriptive: a summary per group, with n. Visual: one\n   figure with a caption that states the takeaway (Lab 03). Statistical: an\n   interval, and a test if the question is a comparison (Lab 02) or a correlation\n   checked within groups if it is a relationship (Lab 04). Qualitative: coded\n   comments or observation, if you collected them.\n4. **Interpretation** (Discussion). Does it matter to the player? Do the sources\n   agree? What could make it wrong?\n5. **Recommendation** (Conclusion). What → Pattern → Meaning → Action. An Action\n   someone on your team could start on tomorrow.\n\nRender the report after each step, not just at the end.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show answer\"}\nThere is no single right finding: it depends on your game. Check your finding\nagainst the **Nine-Part Evidence Workflow** before you call it done.\n\n- [ ] **Research question** is stated, in the Introduction.\n- [ ] **Experimental design** is described, with n and the cleaning log, in the\n  Methodology.\n- [ ] **Descriptive evidence**: a summary per group, with n, in the Results.\n- [ ] **Visual evidence**: one figure with a takeaway caption, in the Results.\n- [ ] **Statistical evidence**: an interval, and a test or a within-group check,\n  in the Results.\n- [ ] **Practical significance**: whether it matters to the player, in the\n  Discussion.\n- [ ] **Qualitative evidence**: coded comments or observation, in the Results and\n  Discussion, or a limitation saying you have none.\n- [ ] **Limitations**: specific to your playtest, in the Discussion.\n- [ ] **Design conclusion**: What → Pattern → Meaning → Action, in the Conclusion.\n- [ ] No number typed by hand. The report renders.\n\nExercises 01 to 06 are a worked version of the whole process on *Tidebreak*.\n:::\n\n---\n\n# What to leave with\n\n- A `report.qmd` with the eight assessment headings that renders without errors.\n- One complete finding from your own game, from question to recommendation.\n- A list of what is still missing for the final report, from the checklist above.\n\n---\n\n# Appendix — Common errors\n\n::: {.callout-warning collapse=\"true\" title=\"Show the error guide\"}\n\n| Message | What it usually means |\n| :- | :- |\n| `could not find function \"ggplot\"` | You have not run `library(ggplot2)` |\n| `could not find function \"pivot_longer\"` | You have not run `library(tidyr)` |\n| ``Cannot use `+` with a single argument`` | A line starts with `+`. Move it to the end of the line above |\n| `object 'build' not found` | A column name used outside `aes()` or outside a dplyr verb |\n| `'data/tidebreak_sessions.csv' does not exist` | `report.qmd` is not in the project folder next to `data/` |\n| `object 'agree_by_build' not found` when rendering | The report uses an object you made in the Console. Put the code in a chunk in the report |\n| Every comment coded \"General\" | The keywords do not match: check capitals, since `grepl()` is case-sensitive |\n\n:::\n",
    "supporting": [
      "complete-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}