{
  "hash": "204bf7b1ca9d59a09ad1223516a8d16b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Cleaning and Transforming\"\nsubtitle: \"Every cleaning choice is part of the analysis\"\n---\n\n> Week 2, first cycle, for everyone, before Part A of Lab 02. It covers getting a\n> raw export into a shape that can answer a question: finding what is missing,\n> doubled, mislabelled or impossible, and deciding what to do about each. Then it\n> introduces the six `dplyr` verbs and the pipe, and shows what they are doing by\n> setting them next to the base R you already know. The worked example is the one\n> to remember: eight blank cells that were hiding the finding.\n\n\n\n---\n\n## Learning Outcomes\n\nBy the end of these notes you can:\n\n- say what an `NA` means in a playtest export, and check whether the pattern of\n  missing values is itself a finding;\n- find exact duplicates and duplicates on the key, and remove them;\n- tell an impossible value from an unusual one, and treat each correctly;\n- repair inconsistent category labels and convert text to numbers without losing\n  data silently;\n- keep a cleaning log that records every row dropped and what it did to *n*;\n- use `select()`, `filter()`, `mutate()`, `arrange()`, `group_by()` and\n  `summarise()`, composed with the pipe;\n- explain what `group_by()` + `summarise()` does by writing the same answer with\n  `tapply()`.\n\n---\n\n## Why This Matters for Playtesting\n\nNo playtest export arrives ready. Telemetry drops events when a build crashes.\nSpreadsheets get pasted into twice. Someone types \"veteran\" where the form said\n\"Veteran\". Every one of these has to be dealt with before any summary means\nanything, and every way of dealing with it is a choice.\n\n**Cleaning choices change conclusions.** Dropping the rows with a blank cell is one\nline of R. If the blanks are not scattered at random, that line removes a\nparticular kind of player, and the summary you compute afterwards describes the\nplayers who were left. The worked example below does exactly this to the strongest\nfinding in the *Tidebreak* data.\n\n**That is why cleaning goes in the report.** A reader who cannot see what you\nremoved cannot judge what you found. Cleaning is analysis\n([rule 6](ten-rules.qmd)): record every choice where the reader can see it, not\nhidden in a script.\n\n---\n\n## What `NA` Actually Means\n\n`NA` is R's marker for a **missing value**: a cell with nothing in it. It does not\nmean zero, and it does not mean the event did not happen. It means the export does\nnot know. A blank `deaths` cell is not a player who never died.\n\n**`NA` is contagious.** Any calculation that touches an `NA` returns `NA`, because\nR will not guess what the missing value was. `mean(deaths)` on a column with one\nblank returns `NA`. Adding `na.rm = TRUE` tells R to leave the blanks out, which is\nitself a decision: it assumes the missing players look like the ones you can see.\n\nThree questions, in this order, before you do anything to a missing value:\n\n1. **How much is missing?** A handful of blanks in 120 rows is different from half\n   a column.\n2. **Where is it missing?** Split the count by build, cohort and outcome. If the\n   blanks cluster, something produced them.\n3. **Is the pattern the finding?** A build whose quit path never writes the session\n   length has a telemetry bug, and the players on that path are the ones the\n   playtest was run to find ([rule 9](ten-rules.qmd)).\n\n---\n\n## Duplicates\n\nA **duplicate** is a row that appears more than once. It inflates *n*, and it\ncounts one player's experience twice.\n\nAn **exact duplicate** repeats every column. It is almost always an export or\ncopy-paste fault, and removing it is safe. A **duplicate on the key** repeats the\nidentifier, here `session_id`, but may differ elsewhere. That is two records\nclaiming to be the same session, and you have to work out which one is right before\nyou remove either.\n\n**Check both.** If the two counts match, every key duplicate is an exact copy. If\nthey do not, look at the rows that differ before deciding.\n\n---\n\n## Impossible Versus Unusual\n\nAn **impossible value** cannot happen in the game: a negative session length, a\nrating of 9 on a 1–7 scale, more objectives captured than the map has. It is an\nerror. Fix it if you can trace the cause, otherwise set it to `NA`, and log it\neither way.\n\nAn **unusual value** is extreme but possible: a player who never died, a Sentinel\nwho scored almost nothing. It is data. Removing it because it spoils a chart is\ndeleting the players you most need to hear from.\n\n**The test is the game's rules, not the chart.** A boxplot flags points by distance\nfrom the rest. Only you know whether the game allows that value. Write the rule\ndown, such as `session_minutes > 0` or `enjoyment` in 1–7, then check the data\nagainst it.\n\n---\n\n## Labels and Types\n\n**Inconsistent labels.** R compares text exactly. `\"Veteran\"`, `\"veteran\"` and\n`\"Veteran \"` with a trailing space are three different cohorts to `table()`, and a\ngrouped summary will report three groups where the design had one. `trimws()`\nstrips leading and trailing spaces and `tolower()` makes the case consistent. Use\nthem together, and always check the result with `table()`. `read_csv()` trims\nspaces on import by default, which hides them in R but not in the file anyone else\nopens.\n\n**Numbers stored as text.** When one cell in a numeric column contains `\"n/a\"` or a\ncomma decimal, `read_csv()` reads the whole column as text. `as.numeric()` converts\nit back, and turns every value it cannot read into `NA` with only a warning. Count\nthe `NA`s before and after converting: any increase is data you just lost.\n\n**Factors.** A **factor** is a categorical variable that knows its possible values\nand their order. `factor(cohort, levels = c(\"novice\", \"regular\", \"veteran\"))`\nfixes the order to the order of experience, so tables and plots read left to right\nfrom least to most experienced, not alphabetically. It also makes a misspelled\nlabel visible: anything not in `levels` becomes `NA` rather than a fourth group\n([rule 3](ten-rules.qmd)).\n\n---\n\n## Keeping a Cleaning Log\n\nA **cleaning log** is a list of every change made to the data, in order, with the\nnumber of rows before and after. It is short, and it goes in the report.\n\n| Step | Rows after | Why |\n| :- | -: | :- |\n| Raw export | 124 | As delivered |\n| Remove exact duplicates | 120 | 4 sessions exported twice |\n| Standardise `cohort` labels | 120 | 18 values re-spaced or re-cased; no rows removed |\n| Keep blank `session_minutes` | 120 | All 8 are Build A frustration quits; see the worked example |\n\n**A step that removes no rows still goes in the log.** Relabelling changes which\ngroup a player is counted in, and the reader needs to know that happened.\n\n---\n\n## The Six Verbs and the Pipe\n\nThe `dplyr` package, part of the tidyverse, reduces most data manipulation to six\n**verbs**. Each takes a data frame and returns a data frame.\n\n| Verb | What it does | Base R you already know |\n| :- | :- | :- |\n| `select()` | Keep some columns | `sessions[, c(\"build\", \"score\")]` |\n| `filter()` | Keep some rows | `sessions[sessions$build == \"A\", ]` |\n| `mutate()` | Add or change a column | `sessions$kd <- sessions$kills / sessions$deaths` |\n| `arrange()` | Sort the rows | `sessions[order(sessions$score), ]` |\n| `group_by()` | Mark the groups | The second argument of `tapply()` |\n| `summarise()` | One row of results per group | The function inside `tapply()` |\n\nThe **pipe**, `|>`, passes the result on its left in as the first argument of the\nfunction on its right. `sessions |> filter(build == \"A\")` means\n`filter(sessions, build == \"A\")`. Its value is in chaining: a sequence of verbs\nreads top to bottom, in the order the steps happen, instead of inside out.\n\n**You will also see `%>%`.** It is the older tidyverse pipe and does the same job\nin everything you will write here. [Distributions and Variation](distributions-and-variation.qmd)\nused it; these notes use `|>`, which is built into R and needs no package.\n\n---\n\n## Worked Examples\n\n**Which build keeps players longer?** The raw export has 124 rows. After\nremoving the 4 duplicates, 8 sessions have a\nblank `session_minutes`. Every one of them is Build A. Every one of them ended in a\nfrustration quit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(build   = deduped$build,\n      missing = is.na(deduped$session_minutes))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     missing\nbuild FALSE TRUE\n    A    52    8\n    B    60    0\n```\n\n\n:::\n:::\n\n\nThat pattern is not random, so both obvious ways of handling it are wrong.\n\n**Choice 1: drop incomplete rows.** `complete.cases()` keeps only rows with no\nblank anywhere. It keeps 109 of 120 sessions. Before,\nBuild A had 20 frustration quits against Build B's\n5. After, it has 12 against\n5. One line of cleaning removed\n40% of\nthe evidence for Build A's biggest problem, and nothing warned you.\n\n**Choice 2: leave them out of the median.** With `na.rm = TRUE`, Build A's median\nsession is 26.1 minutes. But the Build A frustration quits\nthat *were* recorded have a median of\n11.2\nminutes. The missing sessions are almost certainly short ones, so leaving them out\nmakes Build A look better than it is.\n\n**What the complete data says.** For this exercise the unbroken export exists, so\nthe damage can be measured. Build A's true median is\n23.2 minutes, not 26.1. The blank\ncells were never noise. They were the shortest, angriest sessions in the playtest,\nlost by a telemetry bug on exactly the path the playtest was meant to examine.\n\n**The defensible handling** keeps the rows, counts them from `quit_reason`, which\nsurvived, reports the median with a note that 8 short sessions are\nmissing from it, and files a bug against Build A's session logging.\n\n---\n\n## R Demonstrations\n\nBase R first for each cleaning step, then the six verbs, then `tapply()` and\n`group_by()` answering the same question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(dplyr)\n\nraw <- read_csv(\"data/tidebreak_sessions_raw.csv\",\n                trim_ws = FALSE, show_col_types = FALSE)\nnrow(raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 124\n```\n\n\n:::\n:::\n\n\n`read_csv()` normally strips spaces from the edges of text values without telling\nyou. `trim_ws = FALSE` switches that off, so you see the file the way Excel or a\ndatabase import would.\n\n### Missing values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nna_counts <- colSums(is.na(raw))\nna_counts[na_counts > 0]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         deaths session_minutes \n              3               9 \n```\n\n\n:::\n\n```{.r .cell-code}\nmean(raw$deaths)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(raw$deaths, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n:::\n\n\n`is.na()` returns `TRUE` for each blank cell, and `colSums()` counts them per\ncolumn. Printing only the columns with blanks keeps the output readable. The first\n`mean()` shows the contagion; the second is a decision.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(complete.cases(raw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 112\n```\n\n\n:::\n:::\n\n\n`complete.cases()` returns `TRUE` for each row with no blanks anywhere. Count it\nbefore you ever filter by it.\n\n### Duplicates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(raw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(duplicated(raw$session_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\nraw$session_id[duplicated(raw)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"S046\" \"S053\" \"S057\" \"S103\"\n```\n\n\n:::\n\n```{.r .cell-code}\nsessions <- raw[!duplicated(raw), ]\nnrow(sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n:::\n\n\n`duplicated()` marks the second and later copies of a row, or of a value when you\ngive it one column. Keeping `!duplicated()` keeps the first copy of each.\n\n### Labels, types and impossible values\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(sessions$cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  Novice  Regular  Veteran   Novice  Novice   regular  Regular  REGULAR \n       1        1        1       30        2        1       45        3 \nRegular   veteran  Veteran  VETERAN Veteran  \n       3        3       27        1        2 \n```\n\n\n:::\n\n```{.r .cell-code}\nsessions$cohort <- tolower(trimws(sessions$cohort))\nsessions$cohort <- factor(sessions$cohort,\n                          levels = c(\"novice\", \"regular\", \"veteran\"))\ntable(sessions$cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n novice regular veteran \n     33      53      34 \n```\n\n\n:::\n:::\n\n\n13 spellings become three cohorts, in order of experience.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nminutes_text <- c(\"12.9\", \"24.6\", \"n/a\", \"8,6\")\nas.numeric(minutes_text)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: NAs introduced by coercion\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.9 24.6   NA   NA\n```\n\n\n:::\n:::\n\n\nA constructed example, since this export's numbers all arrived as numbers. Two of\nfour values became `NA`, and the only sign was a warning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(sessions$session_minutes <= 0, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(!sessions$enjoyment %in% 1:7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(sessions[order(sessions$score), c(\"session_id\", \"archetype\", \"score\")], 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  session_id archetype score\n  <chr>      <chr>     <dbl>\n1 S052       Sentinel    541\n2 S046       Sentinel    579\n3 S034       Sentinel    584\n4 S059       Sentinel    587\n5 S045       Sentinel    597\n```\n\n\n:::\n:::\n\n\nNo impossible lengths or ratings. The five lowest scores are all Sentinels. They\nare unusual, not impossible, and they are the bimodal Sentinel finding from\n[Describing What You Have](describing-what-you-have.qmd). They stay.\n\n### The six verbs\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  filter(build == \"A\", quit_reason == \"Frustrated\") |>\n  mutate(logged = !is.na(session_minutes)) |>\n  select(session_id, cohort, session_minutes, logged) |>\n  arrange(session_minutes) |>\n  head(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  session_id cohort  session_minutes logged\n  <chr>      <fct>             <dbl> <lgl> \n1 S117       regular             8.6 TRUE  \n2 S043       novice              9.3 TRUE  \n3 S097       novice              9.6 TRUE  \n4 S039       regular            10.3 TRUE  \n```\n\n\n:::\n:::\n\n\nRead it as a sentence: take the sessions, keep Build A's frustration quits, add a\ncolumn saying whether the length was logged, keep four columns, sort by length,\nshow the first four. Each line is one step, and removing a line removes one step.\n`arrange()` puts `NA` last, so the shortest *recorded* quits come first.\n\n### The same question, twice\n\n*What is the average number of wrong turns in each build?*\n\n::: {layout-ncol=2}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(sessions$wrong_turns,\n       sessions$build,\n       mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       A        B \n8.916667 5.516667 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  group_by(build) |>\n  summarise(mean_wrong = mean(wrong_turns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  build mean_wrong\n  <chr>      <dbl>\n1 A           8.92\n2 B           5.52\n```\n\n\n:::\n:::\n\n\n:::\n\nSame numbers: the tibble prints three significant figures, but stores the same\nvalues. Both do the same three things, which together are called\n**split–apply–combine**: split `wrong_turns` into one piece per build, apply\n`mean()` to each piece, combine the results. `tapply()` takes all three as\narguments in one call and returns a named vector. `group_by()` does the split,\n`summarise()` does the apply, and the combine is a tibble with one row per group.\n\nThe difference shows when the question grows. *How many sessions does each build\nhave, how many are missing a length, and what is the median length of the rest?*\n\n::: {layout-ncol=2}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbind(\n  n       = tapply(sessions$session_minutes,\n                   sessions$build, length),\n  missing = tapply(is.na(sessions$session_minutes),\n                   sessions$build, sum),\n  median  = tapply(sessions$session_minutes,\n                   sessions$build, median,\n                   na.rm = TRUE)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   n missing median\nA 60       8  26.15\nB 60       0  27.10\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  group_by(build) |>\n  summarise(\n    n       = n(),\n    missing = sum(is.na(session_minutes)),\n    median  = median(session_minutes,\n                     na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  build     n missing median\n  <chr> <int>   <int>  <dbl>\n1 A        60       8   26.2\n2 B        60       0   27.1\n```\n\n\n:::\n:::\n\n\n:::\n\n`tapply()` needs one call per statistic, each repeating the column and the\ngrouping, and `cbind()` to stick them together. `summarise()` takes as many\nstatistics as you like against one `group_by()`. The answer is the worked example\nin one table: all 8 missing lengths are Build A's, and the median\nbeside them is computed without them.\n\n---\n\n## Interpretation Guidance\n\n**What the data shows.** The raw export has 4 duplicated\nsessions, 18 mislabelled cohorts and\n8 blank session lengths, all in Build A frustration quits.\n\n**What the analysis suggests.** Build A's quit path does not write the session\nlength. The blanks are a telemetry fault concentrated in the sessions that matter\nmost.\n\n**What can legitimately be concluded.** Build A's frustration-quit count is\nreliable, because it comes from `quit_reason`, which is complete. Its median\nsession length is an overestimate by an amount you cannot know from this export.\nSay both.\n\n**Report what you did, not only what you found.** The cleaning log goes in the\nreport's experimental design section. A reader should be able to reproduce your\n*n* from it.\n\n---\n\n## Common Mistakes\n\n**Dropping incomplete rows by reflex.** `na.omit()` and `complete.cases()` are one\nline each and can remove the finding. Check where the blanks are first.\n\n**Treating `NA` as zero.** A blank deaths cell is unknown, not a player who never\ndied. Replacing it with 0 invents a very good player.\n\n**Using `na.rm = TRUE` without saying so.** It is the right tool, and it changes\nwhat the number describes. Report how many values it left out.\n\n**Fixing labels without checking.** Run `table()` before and after. A label you did\nnot know about survives `tolower()`.\n\n**Deleting unusual values as if they were impossible.** The game's rules decide\nwhat is impossible. The chart does not.\n\n**Cleaning in a spreadsheet.** Edits made by hand cannot be seen, repeated or\nreviewed. Every change belongs in code, where it runs again on the next export.\n\n---\n\n## Short Practice Activities\n\nEach takes two or three minutes. Start from `sessions`, the de-duplicated data with\nfixed labels from the demonstrations.\n\n**1.** Which rows would `complete.cases()` remove, split by build and quit reason?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndropped <- sessions[!complete.cases(sessions), ]\ntable(dropped$build, dropped$quit_reason)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   \n    Completed test Frustrated Lost interest\n  A              2          8             0\n  B              0          0             1\n```\n\n\n:::\n:::\n\n\n11 rows. The 8 Build A frustration quits are the\nblank lengths; the other 3 are blank `deaths` cells\nscattered across other outcomes. Those two groups need different handling, and\n`complete.cases()` treats them the same.\n:::\n\n**2.** Rewrite `tapply(sessions$score, sessions$archetype, median)` with\n`group_by()` and `summarise()`, and add the number of sessions per archetype.\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  group_by(archetype) |>\n  summarise(n = n(), median_score = median(score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  archetype     n median_score\n  <chr>     <int>        <dbl>\n1 Duelist      30        1426.\n2 Engineer     30        1472.\n3 Scout        30        1546 \n4 Sentinel     30        1528.\n```\n\n\n:::\n:::\n\n\nAdding `n = n()` costs one argument in `summarise()` and a second `tapply()` call\nin base R. Always report *n* next to a group summary\n([rule 8](ten-rules.qmd)).\n:::\n\n**3.** Using the pipe, list the sessions with a blank `deaths` cell, showing only\n`session_id`, `build` and `quit_reason`.\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  filter(is.na(deaths)) |>\n  select(session_id, build, quit_reason)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  session_id build quit_reason   \n  <chr>      <chr> <chr>         \n1 S022       B     Lost interest \n2 S025       A     Completed test\n3 S077       A     Completed test\n```\n\n\n:::\n:::\n\n\nNo pattern across builds or outcomes: these blanks look scattered, so leaving them\nout of a deaths summary with `na.rm = TRUE` is defensible. That is a conclusion\nabout these three rows, not a rule for every blank.\n:::\n\n---\n\n## Summary\n\n- `NA` means unknown. Count it, find where it is, and ask whether the pattern is\n  the finding before doing anything to it.\n- Check duplicates both exactly and on the key.\n- Impossible values are errors; unusual values are data. The game's rules decide\n  which is which.\n- `trimws()` and `tolower()` fix labels; `factor()` fixes their order; `table()`\n  checks the result.\n- Keep a cleaning log with *n* at every step. It goes in the report.\n- The six verbs, chained with `|>`, are split–apply–combine made readable.\n  `tapply()` does the same thing in one call.\n- In *Tidebreak*, the 8 blank cells were the frustration quits.\n  Dropping them would have hidden Build A's worst problem.\n\n---\n\n## Links to Relevant Reference Material\n\n- [Ten Rules](ten-rules.qmd): rule 3 (know what kind of number you are holding),\n  rule 6 (cleaning is analysis), rule 8 (small samples lie confidently) and rule 9\n  (sometimes the rare value is the whole story)\n- [Distributions and Variation](distributions-and-variation.qmd): the three kinds of\n  outlier\n- [R and Quarto Reference: getting at parts of a data frame](../reference/r-quarto-reference.qmd#getting-at-parts-of-a-data-frame)\n  and [describing by group](../reference/r-quarto-reference.qmd#describing-by-group)\n- [Lab 02: cleaning, transforming and comparing](../labs/comparing-builds.qmd)\n\n---\n\n## Reflective Questions\n\n- A colleague removes every row with a blank cell \"to be safe\". What would you need\n  to know about those rows before you agreed with them?\n- Build A's median session length is wrong in a direction you know but by an amount\n  you do not. Should the report quote it at all? What would you write instead?\n- Two rows share a `session_id` but have different scores. What evidence would you\n  use to decide which one to keep, and what do you do if there is none?\n- `tapply()` and `group_by()` give the same answer. When would you choose the base R\n  version in your own analysis?\n\n---\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}