<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Cleaning and Transforming – Playtest Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notes/07-sample-to-population.html" rel="next">
<link href="../demos/stage-1.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-640402775883e0dc5b71a44650c95e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked wf-at-clean quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/06-cleaning-and-transforming.html">Stage 2 · Comparing Evidence</a></li><li class="breadcrumb-item"><a href="../notes/06-cleaning-and-transforming.html">Cleaning and Transforming</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Playtest Analytics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Start Here</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/00-start-here.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Start Here</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ten-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ten Rules for Reading Playtest Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/setting-up.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 00 — Setting Up</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/stage-0.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stage 0 Demo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Stage 1 · Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/01-planning-a-playtest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Planning a Playtest</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/02-r-first-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R from First Principles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/03-data-and-types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data, Variables and Types</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/04-describing-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Describing Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/05-distributions-and-shape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distributions and Shape</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/reading-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 01 — Reading Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/stage-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stage 1 Demo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Stage 2 · Comparing Evidence</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/06-cleaning-and-transforming.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Cleaning and Transforming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/07-sample-to-population.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">From Sample to Population</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/08-comparing-groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comparing Groups</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/comparing-builds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 02 — Comparing Builds</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/stage-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stage 2 Demo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Stage 3 · Relationships &amp; Visual Evidence</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/09-visualising-with-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualising with ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/10-relationships-and-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Relationships and Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/clinic-figures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 03 — A Figure for Your Report</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/clinic-relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 04 — Relationships in Your Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/stage-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stage 3 Demo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Stage 4 · Evidence to Decision</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/11-reporting-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interpreting and Reporting Evidence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/12-combining-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Combining Evidence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/complete-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 05 — From Evidence to Report</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/stage-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stage 4 Demo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/reference-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistics Reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/r-quarto-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R and Quarto Reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/reference-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ggplot2 Reference</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Going Further</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../going-further/normality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Is It Normal Enough?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../going-further/sampling-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sampling Theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../going-further/testing-in-depth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Testing in Depth</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../going-further/regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../going-further/reshaping-and-joining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reshaping and Joining</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  <li><a href="#why-this-matters-for-playtesting" id="toc-why-this-matters-for-playtesting" class="nav-link" data-scroll-target="#why-this-matters-for-playtesting">Why This Matters for Playtesting</a></li>
  <li><a href="#part-1-cleaning" id="toc-part-1-cleaning" class="nav-link" data-scroll-target="#part-1-cleaning">Part 1: Cleaning</a>
  <ul class="collapse">
  <li><a href="#what-na-actually-means" id="toc-what-na-actually-means" class="nav-link" data-scroll-target="#what-na-actually-means">What <code>NA</code> Actually Means</a></li>
  <li><a href="#duplicates" id="toc-duplicates" class="nav-link" data-scroll-target="#duplicates">Duplicates</a></li>
  <li><a href="#impossible-versus-unusual" id="toc-impossible-versus-unusual" class="nav-link" data-scroll-target="#impossible-versus-unusual">Impossible Versus Unusual</a></li>
  <li><a href="#labels-and-types" id="toc-labels-and-types" class="nav-link" data-scroll-target="#labels-and-types">Labels and Types</a></li>
  <li><a href="#keeping-a-cleaning-log" id="toc-keeping-a-cleaning-log" class="nav-link" data-scroll-target="#keeping-a-cleaning-log">Keeping a Cleaning Log</a></li>
  <li><a href="#worked-example-the-blanks-are-the-finding" id="toc-worked-example-the-blanks-are-the-finding" class="nav-link" data-scroll-target="#worked-example-the-blanks-are-the-finding">Worked Example: the Blanks Are the Finding</a></li>
  </ul></li>
  <li><a href="#part-2-transforming" id="toc-part-2-transforming" class="nav-link" data-scroll-target="#part-2-transforming">Part 2: Transforming</a>
  <ul class="collapse">
  <li><a href="#the-pipe" id="toc-the-pipe" class="nav-link" data-scroll-target="#the-pipe">The Pipe</a></li>
  <li><a href="#the-six-verbs" id="toc-the-six-verbs" class="nav-link" data-scroll-target="#the-six-verbs">The Six Verbs</a></li>
  <li><a href="#splitapplycombine" id="toc-splitapplycombine" class="nav-link" data-scroll-target="#splitapplycombine">Split–Apply–Combine</a></li>
  <li><a href="#interpretation-guidance" id="toc-interpretation-guidance" class="nav-link" data-scroll-target="#interpretation-guidance">Interpretation Guidance</a></li>
  <li><a href="#common-mistakes" id="toc-common-mistakes" class="nav-link" data-scroll-target="#common-mistakes">Common Mistakes</a></li>
  <li><a href="#practice" id="toc-practice" class="nav-link" data-scroll-target="#practice">Practice</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#links" id="toc-links" class="nav-link" data-scroll-target="#links">Links</a></li>
  <li><a href="#reflective-questions" id="toc-reflective-questions" class="nav-link" data-scroll-target="#reflective-questions">Reflective Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/06-cleaning-and-transforming.html">Stage 2 · Comparing Evidence</a></li><li class="breadcrumb-item"><a href="../notes/06-cleaning-and-transforming.html">Cleaning and Transforming</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Cleaning and Transforming</h1>
<p class="subtitle lead">Every cleaning choice is part of the analysis</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<nav class="wf-strip" aria-label="Where this page sits in the evidence workflow">
  <span class="wf-label">Workflow</span>
  <ol>
    <li class="wf-step wf-question">Question</li>
    <li class="wf-step wf-measure">Measure</li>
    <li class="wf-step wf-collect">Collect</li>
    <li class="wf-step wf-clean">Clean</li>
    <li class="wf-step wf-describe">Describe</li>
    <li class="wf-step wf-compare">Compare/Relate</li>
    <li class="wf-step wf-interpret">Interpret</li>
    <li class="wf-step wf-act">Act</li>
  </ol>
</nav>
<blockquote class="blockquote">
<p>No playtest export arrives ready to analyse. This page has two halves. The first is <strong>cleaning</strong>: finding missing values, duplicates, impossible values and broken labels, and dealing with each without quietly changing the answer. The second is <strong>transforming</strong>: the pipe and the six <code>dplyr</code> verbs that reshape a clean table into the one your question needs. The playtest question running through it: <em>“Which build keeps players longer?”</em>, and how a single line of cleaning nearly hides the answer.</p>
</blockquote>
<div class="at-a-glance">
<p><strong>Stage:</strong> 2 · Core. <strong>Time:</strong> 30 minutes in class; 20 more to work through the R. <strong>Before this:</strong> <a href="../notes/05-distributions-and-shape.html">Distributions and Shape</a>. <strong>Key terms:</strong> missing value, duplicate, key, impossible value, factor, cleaning log, pipe, verb, split–apply–combine. <strong>R you will write:</strong> <code>is.na()</code>, <code>distinct()</code>, <code>trimws()</code>, <code>tolower()</code>, <code>factor()</code>, <code>filter()</code>, <code>select()</code>, <code>mutate()</code>, <code>arrange()</code>, <code>group_by()</code>, <code>summarise()</code>, <code>count()</code>, <code>n()</code>.</p>
</div>
<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning Outcomes</h2>
<p>By the end of these notes you can:</p>
<ul>
<li>say what an <code>NA</code> means in a playtest export, and check whether the pattern of missing values is itself a finding;</li>
<li>find exact duplicates and duplicates on the key, and remove them with <code>distinct()</code>;</li>
<li>tell an impossible value from an unusual one, and treat each correctly;</li>
<li>repair inconsistent category labels and convert text to numbers without losing data silently;</li>
<li>keep a cleaning log that records every row dropped and what it did to <em>n</em>;</li>
<li>chain <code>filter()</code>, <code>select()</code>, <code>mutate()</code>, <code>arrange()</code>, <code>group_by()</code> and <code>summarise()</code> with the pipe to answer a playtest question.</li>
</ul>
<hr>
</section>
<section id="why-this-matters-for-playtesting" class="level2">
<h2 class="anchored" data-anchor-id="why-this-matters-for-playtesting">Why This Matters for Playtesting</h2>
<p>Telemetry drops events when a build crashes. Spreadsheets get pasted into twice. Someone types “veteran” where the form said “Veteran”. Every one of these has to be dealt with before any summary means anything, and every way of dealing with it is a choice.</p>
<p><strong>Cleaning choices change conclusions.</strong> Dropping the rows with a blank cell is one line of R. If the blanks are not scattered at random, that line removes a particular kind of player, and the summary you compute afterwards describes the players who were left. The worked example below does exactly this to the strongest finding in the <em>Tidebreak</em> data.</p>
<p><strong>That is why cleaning goes in the report.</strong> A reader who cannot see what you removed cannot judge what you found. Cleaning is analysis (<a href="../notes/ten-rules.html">rule 6</a>): record every choice where the reader can see it, not hidden in a script.</p>
<hr>
</section>
<section id="part-1-cleaning" class="level1">
<h1>Part 1: Cleaning</h1>
<p>You already know <code>count()</code>, <code>mutate()</code>, <code>group_by()</code> and <code>summarise()</code> from Stage 1. This part also uses <code>filter()</code>, which keeps the rows where a condition is true: <code>raw |&gt; filter(build == "A")</code> is the Build A rows. Part 2 covers it properly.</p>
<p>The raw <em>Tidebreak</em> export is <code>tidebreak_sessions_raw.csv</code>. Load it so you see the file as delivered:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/tidebreak_sessions_raw.csv"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">trim_ws =</span> <span class="cn">FALSE</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 124</code></pre>
</div>
</div>
<p><code>read_csv()</code> normally strips spaces from the edges of text values without telling you. <code>trim_ws = FALSE</code> switches that off, so you see what a spreadsheet or database import would see.</p>
<p>Here is the whole cleaning process for this file, with the number of rows after each step. Every step is explained below.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-cleaning-pipeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cleaning-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-cleaning-pipeline">flowchart LR
  R["Raw export&lt;br/&gt;124 rows"] --&gt; D["Remove exact&lt;br/&gt;duplicates&lt;br/&gt;120 rows"]
  D --&gt; L["Fix cohort&lt;br/&gt;labels&lt;br/&gt;120 rows"]
  L --&gt; I["Check impossible&lt;br/&gt;values&lt;br/&gt;120 rows"]
  I --&gt; M["Keep blank&lt;br/&gt;session lengths&lt;br/&gt;120 rows"]
  M --&gt; C(["Clean data&lt;br/&gt;120 rows"])
  class C action
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cleaning-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The cleaning pipeline for the raw Tidebreak export, with the number of rows after each step.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Only one step removes rows. The others change values or decide to leave something alone, and they belong in the record just as much.</p>
<hr>
<section id="what-na-actually-means" class="level2">
<h2 class="anchored" data-anchor-id="what-na-actually-means">What <code>NA</code> Actually Means</h2>
<p><code>NA</code> is R’s marker for a <strong>missing value</strong>: a cell with nothing in it. It does not mean zero, and it does not mean the event did not happen. It means the export does not know. A blank <code>deaths</code> cell is not a player who never died.</p>
<p><strong><code>NA</code> is contagious.</strong> Any calculation that touches an <code>NA</code> returns <code>NA</code>, because R will not guess what the missing value was. Adding <code>na.rm = TRUE</code> tells R to leave the blanks out, which is itself a decision: it assumes the missing players look like the ones you can see.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(raw))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       session_id         player_id            cohort         archetype 
                0                 0                 0                 0 
            build          accuracy          mobility     survivability 
                0                 0                 0                 0 
objective_control           support         awareness             score 
                0                 0                 0                 0 
            kills            deaths        objectives       shots_fired 
                0                 3                 0                 0 
     time_alive_s        distance_m   session_minutes       quit_reason 
                0                 0                 9                 0 
      wrong_turns   items_collected         completed        difficulty 
                0                 0                 0                 0 
        enjoyment           comment 
                0                 0 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(raw<span class="sc">$</span>deaths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(raw<span class="sc">$</span>deaths, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p><code>is.na()</code> returns <code>TRUE</code> for each blank cell, and <code>colSums()</code> adds them up column by column: a count of blanks in every column at once. The first <code>mean()</code> shows the contagion; the second is a decision.</p>
<p>Three questions, in this order, before you do anything to a missing value:</p>
<ol type="1">
<li><strong>How much is missing?</strong> A handful of blanks in 124 rows is different from half a column.</li>
<li><strong>Where is it missing?</strong> Split the count by build, cohort and outcome. If the blanks cluster, something produced them.</li>
<li><strong>Is the pattern the finding?</strong> A build whose quit path never writes the session length has a telemetry bug, and the players on that path are the ones the playtest was run to find (<a href="../notes/ten-rules.html">rule 9</a>).</li>
</ol>
<p><strong>Common mistake:</strong> dropping every row with a blank, “to be safe”. You will see it done with <code>na.omit()</code>, <code>drop_na()</code> or <code>complete.cases()</code>. Count what it would remove before you ever do it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">complete.cases</span>(raw))   <span class="co"># rows with no blank anywhere</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 112</code></pre>
</div>
</div>
<p>The worked example below shows what that one line would have cost.</p>
<hr>
</section>
<section id="duplicates" class="level2">
<h2 class="anchored" data-anchor-id="duplicates">Duplicates</h2>
<p>A <strong>duplicate</strong> is a row that appears more than once. It inflates <em>n</em>, and it counts one player’s experience twice.</p>
<p>An <strong>exact duplicate</strong> repeats every column. It is almost always an export or copy-paste fault, and removing it is safe. A <strong>duplicate on the key</strong> repeats the identifier, here <code>session_id</code>, but may differ elsewhere. That is two records claiming to be the same session, and you have to work out which one is right before you remove either.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exact duplicates: how many rows disappear when repeats are removed?</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(raw) <span class="sc">-</span> <span class="fu">nrow</span>(<span class="fu">distinct</span>(raw))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Duplicates on the key: which session IDs appear more than once?</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>raw <span class="sc">|&gt;</span> <span class="fu">count</span>(session_id) <span class="sc">|&gt;</span> <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  session_id     n
  &lt;chr&gt;      &lt;int&gt;
1 S046           2
2 S053           2
3 S057           2
4 S103           2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>clean <span class="ot">&lt;-</span> raw <span class="sc">|&gt;</span> <span class="fu">distinct</span>()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 120</code></pre>
</div>
</div>
<p><code>distinct()</code> keeps the first copy of every row and drops the repeats. <strong>Check both counts.</strong> Here 4 rows are exact copies and 4 session IDs are repeated: the same number, so every key duplicate is an exact copy and removing them is safe. If they did not match, you would look at the differing rows first.</p>
<hr>
</section>
<section id="impossible-versus-unusual" class="level2">
<h2 class="anchored" data-anchor-id="impossible-versus-unusual">Impossible Versus Unusual</h2>
<p>An <strong>impossible value</strong> cannot happen in the game: a negative session length, a rating of 9 on a 1–7 scale, more objectives captured than the map has. It is an error. Fix it if you can trace the cause, otherwise set it to <code>NA</code>, and log it either way.</p>
<p>An <strong>unusual value</strong> is extreme but possible: a player who never died, a Sentinel who scored almost nothing. It is data. Removing it because it spoils a chart is deleting the players you most need to hear from.</p>
<p><strong>The test is the game’s rules, not the chart.</strong> A boxplot flags points by distance from the rest. Only you know whether the game allows that value. Write the rule down, such as <code>session_minutes &gt; 0</code> or <code>enjoyment</code> in 1–7, then check the data against it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span> <span class="fu">filter</span>(session_minutes <span class="sc">&lt;=</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> <span class="fu">nrow</span>()     <span class="co"># sessions of zero or less</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span>enjoyment <span class="sc">%in%</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">|&gt;</span> <span class="fu">nrow</span>()      <span class="co"># ratings off the 1-7 scale</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span> <span class="fu">arrange</span>(score) <span class="sc">|&gt;</span> <span class="fu">select</span>(session_id, archetype, score) <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  session_id archetype score
  &lt;chr&gt;      &lt;chr&gt;     &lt;dbl&gt;
1 S052       Sentinel    541
2 S046       Sentinel    579
3 S034       Sentinel    584
4 S059       Sentinel    587
5 S045       Sentinel    597</code></pre>
</div>
</div>
<p><code>%in%</code> asks “is this value one of these?”, and <code>!</code> turns it round.</p>
<p>No impossible lengths or ratings. The five lowest scores are all Sentinels: unusual, not impossible, and they are the bimodal Sentinel finding from <a href="../notes/04-describing-variables.html#worked-example">Describing Variables</a>. They stay. The <a href="../notes/05-distributions-and-shape.html#outliers">outlier decision tree</a> is the same reasoning in diagram form.</p>
<hr>
</section>
<section id="labels-and-types" class="level2">
<h2 class="anchored" data-anchor-id="labels-and-types">Labels and Types</h2>
<p><strong>Inconsistent labels.</strong> R compares text exactly. <code>"Veteran"</code>, <code>"veteran"</code> and <code>"Veteran "</code> with a trailing space are three different cohorts to <code>count()</code>, and a grouped summary will report three groups where the design had one. <code>trimws()</code> strips leading and trailing spaces and <code>tolower()</code> makes the case consistent. Use them together inside <code>mutate()</code>, and always count before and after:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span> <span class="fu">count</span>(cohort)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
   cohort         n
   &lt;chr&gt;      &lt;int&gt;
 1 " Novice"      1
 2 " Regular"     1
 3 " Veteran"     1
 4 "Novice"      30
 5 "Novice "      2
 6 "REGULAR"      3
 7 "Regular"     45
 8 "Regular "     3
 9 "VETERAN"      1
10 "Veteran"     27
11 "Veteran "     2
12 "regular"      1
13 "veteran"      3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>clean <span class="ot">&lt;-</span> clean <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">cohort =</span> <span class="fu">tolower</span>(<span class="fu">trimws</span>(cohort)))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span> <span class="fu">count</span>(cohort)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  cohort      n
  &lt;chr&gt;   &lt;int&gt;
1 novice     33
2 regular    53
3 veteran    34</code></pre>
</div>
</div>
<p>13 spellings become three cohorts.</p>
<p><strong>Factors.</strong> A <strong>factor</strong> is a categorical variable that knows its possible values and their order. Setting the levels puts the cohorts in order of experience rather than the alphabet, and it makes a misspelled label visible: anything not in <code>levels</code> becomes <code>NA</code> rather than a fourth group (<a href="../notes/ten-rules.html">rule 3</a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>clean <span class="ot">&lt;-</span> clean <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cohort =</span> <span class="fu">factor</span>(cohort, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"novice"</span>, <span class="st">"regular"</span>, <span class="st">"veteran"</span>)))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span> <span class="fu">count</span>(cohort)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  cohort      n
  &lt;fct&gt;   &lt;int&gt;
1 novice     33
2 regular    53
3 veteran    34</code></pre>
</div>
</div>
<p><strong>Numbers stored as text.</strong> When one cell in a numeric column contains <code>"n/a"</code> or a comma decimal, <code>read_csv()</code> reads the whole column as text. <code>as.numeric()</code> converts it back, and turns every value it cannot read into <code>NA</code> with only a warning:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>minutes_text <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"12.9"</span>, <span class="st">"24.6"</span>, <span class="st">"n/a"</span>, <span class="st">"8,6"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(minutes_text)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.9 24.6   NA   NA</code></pre>
</div>
</div>
<p>A constructed example, since this export’s numbers all arrived as numbers. Two of four values became <code>NA</code>, and the only sign was a warning. Count the <code>NA</code>s before and after converting: any increase is data you just lost.</p>
<hr>
</section>
<section id="keeping-a-cleaning-log" class="level2">
<h2 class="anchored" data-anchor-id="keeping-a-cleaning-log">Keeping a Cleaning Log</h2>
<p>A <strong>cleaning log</strong> is a list of every change made to the data, in order, with the number of rows before and after. It is short, and it goes in the report.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Step</th>
<th style="text-align: right;">Rows after</th>
<th style="text-align: left;">Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Raw export</td>
<td style="text-align: right;">124</td>
<td style="text-align: left;">As delivered</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remove exact duplicates</td>
<td style="text-align: right;">120</td>
<td style="text-align: left;">4 sessions exported twice</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standardise <code>cohort</code> labels</td>
<td style="text-align: right;">120</td>
<td style="text-align: left;">18 values re-spaced or re-cased; no rows removed</td>
</tr>
<tr class="even">
<td style="text-align: left;">Check impossible values</td>
<td style="text-align: right;">120</td>
<td style="text-align: left;">None found against the game’s rules</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Keep blank <code>session_minutes</code></td>
<td style="text-align: right;">120</td>
<td style="text-align: left;">All 8 are Build A frustration quits; see the worked example</td>
</tr>
</tbody>
</table>
<p><strong>A step that removes no rows still goes in the log.</strong> Relabelling changes which group a player is counted in, and the reader needs to know that happened.</p>
<p><strong>For your project:</strong> start the cleaning log the day the first export arrives, in the same Quarto document as the analysis. It goes in the Methodology section of your report, and a reader should be able to reproduce your <em>n</em> from it.</p>
<hr>
</section>
<section id="worked-example-the-blanks-are-the-finding" class="level2">
<h2 class="anchored" data-anchor-id="worked-example-the-blanks-are-the-finding">Worked Example: the Blanks Are the Finding</h2>
<p><strong>Which build keeps players longer?</strong> After removing the 4 duplicates, 8 sessions have a blank <code>session_minutes</code>. Every one of them is Build A. Every one of them ended in a frustration quit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span> <span class="fu">count</span>(build, quit_reason, <span class="at">missing =</span> <span class="fu">is.na</span>(session_minutes))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 4
  build quit_reason     missing     n
  &lt;chr&gt; &lt;chr&gt;           &lt;lgl&gt;   &lt;int&gt;
1 A     Completed test  FALSE      31
2 A     Frustrated      FALSE      12
3 A     Frustrated      TRUE        8
4 A     Lost interest   FALSE       7
5 A     Technical fault FALSE       2
6 B     Completed test  FALSE      38
7 B     Frustrated      FALSE       5
8 B     Lost interest   FALSE      14
9 B     Technical fault FALSE       3</code></pre>
</div>
</div>
<p><code>count()</code> can count a condition as well as a column: <code>missing = is.na(...)</code> makes a TRUE/FALSE column and counts each combination.</p>
<p>That pattern is not random, so both obvious ways of handling it are wrong.</p>
<p><strong>Choice 1: drop incomplete rows.</strong> <code>complete.cases()</code> keeps only rows with no blank anywhere. It keeps 109 of 120 sessions. Before, Build A had 20 frustration quits against Build B’s 5. After, it has 12 against 5. One line of cleaning removed 40% of the evidence for Build A’s biggest problem, and nothing warned you.</p>
<p><strong>Choice 2: leave them out of the median.</strong> With <code>na.rm = TRUE</code>, Build A’s median session is 26.1 minutes. But the Build A frustration quits that <em>were</em> recorded have a median of 11.2 minutes. The missing sessions are almost certainly short ones, so leaving them out makes Build A look better than it is.</p>
<p><strong>What the complete data says.</strong> For this exercise the unbroken export exists, so the damage can be measured. Build A’s true median is 23.2 minutes, not 26.1. The blank cells were never noise. They were the shortest, angriest sessions in the playtest, lost by a telemetry bug on exactly the path the playtest was meant to examine.</p>
<p><strong>The defensible handling</strong> keeps the rows, counts them from <code>quit_reason</code>, which survived, reports the median with a note that 8 short sessions are missing from it, and files a bug against Build A’s session logging.</p>
<p><strong>What should the team do?</strong> Fix the logger first, because the next playtest will have the same hole. Then report Build A’s frustration quits from the column that is complete, and say plainly which number is an overestimate and why.</p>
<hr>
</section>
</section>
<section id="part-2-transforming" class="level1">
<h1>Part 2: Transforming</h1>
<p>A clean table is rarely the table your question needs. You need some of the rows, some of the columns, a new column computed from others, a different order, or one row per group. The <code>dplyr</code> package, part of the tidyverse, does each of these with one <strong>verb</strong>, and the pipe joins the verbs together.</p>
<section id="the-pipe" class="level2">
<h2 class="anchored" data-anchor-id="the-pipe">The Pipe</h2>
<p>You met the pipe in Stage 1. As a reminder, <code>|&gt;</code> passes the result on its left in as the <strong>first argument</strong> of the function on its right:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">With the pipe</th>
<th style="text-align: left;">Means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>x \|&gt; f()</code></td>
<td style="text-align: left;"><code>f(x)</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>x \|&gt; f(y)</code></td>
<td style="text-align: left;"><code>f(x, y)</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>x \|&gt; f() \|&gt; g()</code></td>
<td style="text-align: left;"><code>g(f(x))</code></td>
</tr>
</tbody>
</table>
<p>Its value is in chaining. “The median session length of Build A’s frustration quits, to one decimal place”:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(build <span class="sc">==</span> <span class="st">"A"</span>, quit_reason <span class="sc">==</span> <span class="st">"Frustrated"</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(session_minutes) <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">median</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.2</code></pre>
</div>
</div>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-pipe" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-pipe">flowchart LR
  C[("clean")] --&gt; F["filter()&lt;br/&gt;Build A quits"]
  F --&gt; P["pull()&lt;br/&gt;session_minutes"]
  P --&gt; M["median()"]
  M --&gt; R["round(1)"]
  R --&gt; A(["answer"])
  class A action
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: A pipeline reads in the order things happen: each step takes the result of the one before it.
</figcaption>
</figure>
</div>
</div>
</div>
<p>It reads as a sentence: <em>take the clean data, keep Build A’s frustration quits, pull out the session lengths, take the median, round it.</em> Each line is one step, and deleting a line deletes one step. <code>pull()</code> extracts one column as a vector, the pipe-friendly version of <code>$</code>.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Going further: the same question without the pipe">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Going further: the same question without the pipe
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You will see code written the other two ways. Both give the same answer.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nested: read from the inside out</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">median</span>(clean<span class="sc">$</span>session_minutes[clean<span class="sc">$</span>build <span class="sc">==</span> <span class="st">"A"</span> <span class="sc">&amp;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                                     clean<span class="sc">$</span>quit_reason <span class="sc">==</span> <span class="st">"Frustrated"</span>],</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intermediate objects: clear, but leaves a trail of names</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>a_frus <span class="ot">&lt;-</span> clean[clean<span class="sc">$</span>build <span class="sc">==</span> <span class="st">"A"</span> <span class="sc">&amp;</span> clean<span class="sc">$</span>quit_reason <span class="sc">==</span> <span class="st">"Frustrated"</span>, ]</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">median</span>(a_frus<span class="sc">$</span>session_minutes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.2</code></pre>
</div>
</div>
<p>You will also see <code>%&gt;%</code>, the older tidyverse pipe. It does the same job here. In RStudio, <code>Ctrl+Shift+M</code> types a pipe; <em>Tools → Global Options → Code</em> chooses which one.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="the-six-verbs" class="level2">
<h2 class="anchored" data-anchor-id="the-six-verbs">The Six Verbs</h2>
<p>Each verb takes a data frame first and returns a data frame, which is what makes them chain. To see what each one does, here is a small table of six sessions that every example below starts from:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>few <span class="ot">&lt;-</span> clean <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(session_id, build, cohort, deaths, kills, session_minutes) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">6</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>few</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  session_id build cohort  deaths kills session_minutes
  &lt;chr&gt;      &lt;chr&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt;           &lt;dbl&gt;
1 S001       A     regular      4     7            NA  
2 S002       B     veteran      2     5            24.6
3 S003       A     regular      2     5            12.5
4 S004       B     novice       4     7            18.8
5 S005       A     veteran      3    12            18.7
6 S006       B     regular      5     7            25.3</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Verb</th>
<th style="text-align: left;">What it does</th>
<th style="text-align: left;">The question it answers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>select()</code></td>
<td style="text-align: left;">Keep some columns</td>
<td style="text-align: left;">“I only need these measures”</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>filter()</code></td>
<td style="text-align: left;">Keep some rows</td>
<td style="text-align: left;">“Only Build A”, “only the frustration quits”</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>mutate()</code></td>
<td style="text-align: left;">Add or change a column</td>
<td style="text-align: left;">“Kills per death”, “fix the labels”</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>arrange()</code></td>
<td style="text-align: left;">Sort the rows</td>
<td style="text-align: left;">“Shortest sessions first”</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>group_by()</code></td>
<td style="text-align: left;">Mark the groups</td>
<td style="text-align: left;">“For each build…”</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>summarise()</code></td>
<td style="text-align: left;">One row of results per group</td>
<td style="text-align: left;">“…what is the median?”</td>
</tr>
</tbody>
</table>
<p>Inside every verb you refer to columns by their bare names, <code>deaths</code> rather than <code>few$deaths</code>: the verb already knows which table it is working on.</p>
<section id="select-keep-columns" class="level3">
<h3 class="anchored" data-anchor-id="select-keep-columns"><code>select()</code>: keep columns</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>few <span class="sc">|&gt;</span> <span class="fu">select</span>(session_id, build, deaths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  session_id build deaths
  &lt;chr&gt;      &lt;chr&gt;  &lt;dbl&gt;
1 S001       A          4
2 S002       B          2
3 S003       A          2
4 S004       B          4
5 S005       A          3
6 S006       B          5</code></pre>
</div>
</div>
<p>Six rows, three columns. <code>select(-cohort)</code> would keep everything <em>except</em> <code>cohort</code>.</p>
</section>
<section id="filter-keep-rows" class="level3">
<h3 class="anchored" data-anchor-id="filter-keep-rows"><code>filter()</code>: keep rows</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>few <span class="sc">|&gt;</span> <span class="fu">filter</span>(build <span class="sc">==</span> <span class="st">"A"</span>, deaths <span class="sc">&gt;=</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  session_id build cohort  deaths kills session_minutes
  &lt;chr&gt;      &lt;chr&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt;           &lt;dbl&gt;
1 S001       A     regular      4     7            NA  
2 S005       A     veteran      3    12            18.7</code></pre>
</div>
</div>
<p>Only the rows where every condition is <code>TRUE</code>. A comma between conditions means “and”; use <code>|</code> for “or”.</p>
</section>
<section id="mutate-add-a-column" class="level3">
<h3 class="anchored" data-anchor-id="mutate-add-a-column"><code>mutate()</code>: add a column</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>few <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">kd =</span> <span class="fu">round</span>(kills <span class="sc">/</span> <span class="fu">pmax</span>(deaths, <span class="dv">1</span>), <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  session_id build cohort  deaths kills session_minutes    kd
  &lt;chr&gt;      &lt;chr&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;
1 S001       A     regular      4     7            NA    1.75
2 S002       B     veteran      2     5            24.6  2.5 
3 S003       A     regular      2     5            12.5  2.5 
4 S004       B     novice       4     7            18.8  1.75
5 S005       A     veteran      3    12            18.7  4   
6 S006       B     regular      5     7            25.3  1.4 </code></pre>
</div>
</div>
<p>A new column, computed row by row from the others. <code>pmax(deaths, 1)</code> replaces a zero with 1 so that a player who never died does not divide by zero.</p>
</section>
<section id="arrange-sort" class="level3">
<h3 class="anchored" data-anchor-id="arrange-sort"><code>arrange()</code>: sort</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>few <span class="sc">|&gt;</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(session_minutes))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  session_id build cohort  deaths kills session_minutes
  &lt;chr&gt;      &lt;chr&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt;           &lt;dbl&gt;
1 S006       B     regular      5     7            25.3
2 S002       B     veteran      2     5            24.6
3 S004       B     novice       4     7            18.8
4 S005       A     veteran      3    12            18.7
5 S003       A     regular      2     5            12.5
6 S001       A     regular      4     7            NA  </code></pre>
</div>
</div>
<p>Longest session first. Without <code>desc()</code> it sorts smallest first. <code>arrange()</code> puts <code>NA</code> last whichever way you sort.</p>
</section>
<section id="group_by-and-summarise-one-row-per-group" class="level3">
<h3 class="anchored" data-anchor-id="group_by-and-summarise-one-row-per-group"><code>group_by()</code> and <code>summarise()</code>: one row per group</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>few <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(build) <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sessions =</span> <span class="fu">n</span>(), <span class="at">mean_deaths =</span> <span class="fu">mean</span>(deaths))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  build sessions mean_deaths
  &lt;chr&gt;    &lt;int&gt;       &lt;dbl&gt;
1 A            3        3   
2 B            3        3.67</code></pre>
</div>
</div>
<p>Six rows in, one row per build out. <code>group_by()</code> changes nothing you can see; it marks the groups so that <code>summarise()</code> computes once for each. <code>n()</code> counts the rows in each group.</p>
</section>
<section id="chaining-them" class="level3">
<h3 class="anchored" data-anchor-id="chaining-them">Chaining them</h3>
<p>The verbs earn their keep together:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(build <span class="sc">==</span> <span class="st">"A"</span>, quit_reason <span class="sc">==</span> <span class="st">"Frustrated"</span>) <span class="sc">|&gt;</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">logged =</span> <span class="sc">!</span><span class="fu">is.na</span>(session_minutes)) <span class="sc">|&gt;</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(session_id, cohort, session_minutes, logged) <span class="sc">|&gt;</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(session_minutes) <span class="sc">|&gt;</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  session_id cohort  session_minutes logged
  &lt;chr&gt;      &lt;fct&gt;             &lt;dbl&gt; &lt;lgl&gt; 
1 S117       regular             8.6 TRUE  
2 S043       novice              9.3 TRUE  
3 S097       novice              9.6 TRUE  
4 S039       regular            10.3 TRUE  </code></pre>
</div>
</div>
<p>Read it as a sentence: take the clean sessions, keep Build A’s frustration quits, add a column saying whether the length was logged, keep four columns, sort by length, show the first four. The shortest <em>recorded</em> quits come first, because the blank ones are sorted last.</p>
<hr>
</section>
</section>
<section id="splitapplycombine" class="level2">
<h2 class="anchored" data-anchor-id="splitapplycombine">Split–Apply–Combine</h2>
<p><code>group_by()</code> with <code>summarise()</code> does three things, which together are called <strong>split–apply–combine</strong>:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-split-apply-combine" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-split-apply-combine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-split-apply-combine">flowchart LR
  D[("wrong_turns")] --&gt;|split by build| A["Build A&lt;br/&gt;sessions"]
  D --&gt;|split by build| B["Build B&lt;br/&gt;sessions"]
  A --&gt;|"apply mean()"| MA["mean for A"]
  B --&gt;|"apply mean()"| MB["mean for B"]
  MA --&gt;|combine| T(["one row&lt;br/&gt;per build"])
  MB --&gt;|combine| T
  class T action
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-split-apply-combine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Split the column by group, apply a function to each piece, combine the results into one table.
</figcaption>
</figure>
</div>
</div>
</div>
<p><em>What is the average number of wrong turns in each build?</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(build) <span class="sc">|&gt;</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_wrong =</span> <span class="fu">mean</span>(wrong_turns))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  build mean_wrong
  &lt;chr&gt;      &lt;dbl&gt;
1 A           8.92
2 B           5.52</code></pre>
</div>
</div>
<p><code>group_by()</code> does the split, <code>summarise()</code> does the apply, and the combine is a table with one row per group.</p>
<p>The point of it shows when the question grows. <em>How many sessions does each build have, how many are missing a length, and what is the median length of the rest?</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(build) <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n       =</span> <span class="fu">n</span>(),</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(session_minutes)),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median  =</span> <span class="fu">median</span>(session_minutes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  build     n missing median
  &lt;chr&gt; &lt;int&gt;   &lt;int&gt;  &lt;dbl&gt;
1 A        60       8   26.2
2 B        60       0   27.1</code></pre>
</div>
</div>
<p>One <code>group_by()</code>, as many summaries as you like. The answer is the worked example in one table: all 8 missing lengths are Build A’s, and the median beside them is computed without them.</p>
<p><strong>You will also see</strong> <code>tapply()</code> and <code>aggregate()</code> doing split–apply–combine in older code. You do not need to write them.</p>
<hr>
</section>
<section id="interpretation-guidance" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-guidance">Interpretation Guidance</h2>
<p><strong>What the data shows.</strong> The raw export has 4 duplicated sessions, 18 mislabelled cohorts and 8 blank session lengths, all in Build A frustration quits.</p>
<p><strong>What the analysis suggests.</strong> Build A’s quit path does not write the session length. The blanks are a telemetry fault concentrated in the sessions that matter most.</p>
<p><strong>What can legitimately be concluded.</strong> Build A’s frustration-quit count is reliable, because it comes from <code>quit_reason</code>, which is complete. Its median session length is an overestimate by an amount you cannot know from this export. Say both.</p>
<p><strong>Report what you did, not only what you found.</strong> The cleaning log goes in the report’s Methodology section. A reader should be able to reproduce your <em>n</em> from it.</p>
<hr>
</section>
<section id="common-mistakes" class="level2">
<h2 class="anchored" data-anchor-id="common-mistakes">Common Mistakes</h2>
<p><strong>Dropping incomplete rows by reflex.</strong> <code>na.omit()</code> and <code>complete.cases()</code> are one line each and can remove the finding. Check where the blanks are first.</p>
<p><strong>Treating <code>NA</code> as zero.</strong> A blank deaths cell is unknown, not a player who never died. Replacing it with 0 invents a very good player.</p>
<p><strong>Using <code>na.rm = TRUE</code> without saying so.</strong> It is the right tool, and it changes what the number describes. Report how many values it left out.</p>
<p><strong>Fixing labels without checking.</strong> Run <code>count()</code> before and after. A label you did not know about survives <code>tolower()</code>.</p>
<p><strong>Deleting unusual values as if they were impossible.</strong> The game’s rules decide what is impossible. The chart does not.</p>
<p><strong>Forgetting to keep the result.</strong> <code>clean |&gt; filter(build == "A")</code> prints the filtered rows and changes nothing. Assign it, <code>a_only &lt;- clean |&gt; filter(...)</code>, to keep it.</p>
<p><strong>Using <code>=</code> inside <code>filter()</code>.</strong> <code>filter(build = "A")</code> is an error; the comparison is <code>==</code>.</p>
<p><strong>Cleaning in a spreadsheet.</strong> Edits made by hand cannot be seen, repeated or reviewed. Every change belongs in code, where it runs again on the next export.</p>
<hr>
</section>
<section id="practice" class="level2">
<h2 class="anchored" data-anchor-id="practice">Practice</h2>
<p>Each takes two or three minutes. Start from <code>clean</code>, the de-duplicated data with fixed labels from Part 1.</p>
<ol type="1">
<li><strong>Predict.</strong> Before running it: how many rows will <code>clean |&gt; filter(build == "B", quit_reason == "Frustrated")</code> return? Use what you know from <a href="../notes/01-planning-a-playtest.html#worked-example">Planning a Playtest</a>.</li>
<li><strong>Compute.</strong> Which rows have a blank <code>session_minutes</code> or a blank <code>deaths</code>? Count them by build and quit reason.</li>
<li><strong>Rewrite.</strong> You find <code>tapply(clean$score, clean$archetype, median)</code> in a teammate’s script. Rewrite it as a pipeline with <code>group_by()</code> and <code>summarise()</code>, and add the number of sessions per archetype.</li>
<li><strong>Critique.</strong> A teammate’s script starts <code>clean &lt;- na.omit(raw)</code> and then reports Build A’s frustration rate. What is wrong, and what should the first lines of the script do instead?</li>
</ol>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Show answers">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Show answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1.</strong> Piping into <code>nrow()</code> counts the rows the filter kept:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span> <span class="fu">filter</span>(build <span class="sc">==</span> <span class="st">"B"</span>, quit_reason <span class="sc">==</span> <span class="st">"Frustrated"</span>) <span class="sc">|&gt;</span> <span class="fu">nrow</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>5, the Build B frustration count from the worked example in Planning a Playtest.</p>
<p><strong>2.</strong> <code>|</code> means “or”:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(session_minutes) <span class="sc">|</span> <span class="fu">is.na</span>(deaths)) <span class="sc">|&gt;</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(build, quit_reason)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  build quit_reason        n
  &lt;chr&gt; &lt;chr&gt;          &lt;int&gt;
1 A     Completed test     2
2 A     Frustrated         8
3 B     Lost interest      1</code></pre>
</div>
</div>
<p>The 8 Build A frustration quits are the blank lengths; the blank <code>deaths</code> cells are scattered across other outcomes. Those two groups need different handling, and dropping every incomplete row treats them the same.</p>
<p><strong>3.</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>clean <span class="sc">|&gt;</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(archetype) <span class="sc">|&gt;</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">median_score =</span> <span class="fu">median</span>(score))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  archetype     n median_score
  &lt;chr&gt;     &lt;int&gt;        &lt;dbl&gt;
1 Duelist      30        1426.
2 Engineer     30        1472.
3 Scout        30        1546 
4 Sentinel     30        1528.</code></pre>
</div>
</div>
<p>Adding <code>n = n()</code> costs one argument. Always report <em>n</em> next to a group summary (<a href="../notes/ten-rules.html">rule 8</a>).</p>
<p><strong>4.</strong> <code>na.omit()</code> drops every row with any blank, which removes all 8 of Build A’s unlogged frustration quits, so the reported frustration rate is too low. The script should remove duplicates, fix labels, then <strong>count</strong> the missing values by build and outcome before deciding anything, and log each step.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li><code>NA</code> means unknown. Count it, find where it is, and ask whether the pattern is the finding before doing anything to it.</li>
<li>Check duplicates both exactly and on the key.</li>
<li>Impossible values are errors; unusual values are data. The game’s rules decide which is which.</li>
<li><code>trimws()</code> and <code>tolower()</code> fix labels; <code>factor()</code> fixes their order; <code>count()</code> checks the result.</li>
<li>Keep a cleaning log with <em>n</em> at every step. It goes in the report.</li>
<li>The pipe passes its left side in as the first argument on its right, so a pipeline reads in the order things happen.</li>
<li>The six verbs select columns, filter rows, mutate columns, arrange rows, and group and summarise. <code>group_by()</code> + <code>summarise()</code> is split–apply–combine.</li>
<li>In <em>Tidebreak</em>, the 8 blank cells were the frustration quits. Dropping them would have hidden Build A’s worst problem.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Key term</th>
<th style="text-align: left;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Missing value (<code>NA</code>)</strong></td>
<td style="text-align: left;">A value that should exist but was not recorded</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Exact duplicate</strong></td>
<td style="text-align: left;">A row repeated in every column</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Key</strong></td>
<td style="text-align: left;">The column that identifies a row, such as <code>session_id</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Impossible value</strong></td>
<td style="text-align: left;">A value the game’s rules do not allow: an error</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Unusual value</strong></td>
<td style="text-align: left;">An extreme but possible value: data</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Factor</strong></td>
<td style="text-align: left;">A categorical variable with fixed, ordered levels</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Cleaning log</strong></td>
<td style="text-align: left;">Every change to the data, in order, with <em>n</em> after each</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Pipe (<code>\|&gt;</code>)</strong></td>
<td style="text-align: left;">Passes the result on its left as the first argument on its right</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Verb</strong></td>
<td style="text-align: left;">A <code>dplyr</code> function that takes a data frame and returns one</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Split–apply–combine</strong></td>
<td style="text-align: left;">Split by group, apply a function to each piece, combine the results</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="links" class="level2">
<h2 class="anchored" data-anchor-id="links">Links</h2>
<ul>
<li><a href="../notes/ten-rules.html">Ten Rules</a>: rule 3 (know what kind of number you are holding), rule 6 (cleaning is analysis), rule 8 (small samples lie confidently) and rule 9 (sometimes the rare value is the whole story)</li>
<li><a href="../reference/r-quarto-reference.html#cleaning">R and Quarto Reference: cleaning</a> and <a href="../reference/r-quarto-reference.html#transforming-with-dplyr">transforming with dplyr</a></li>
<li><a href="../labs/comparing-builds.html#part-a-clean-the-export">Lab 02: Comparing Builds</a>, Part A</li>
<li><a href="../demos/stage-2.html">Stage 2 demo</a></li>
<li>Next: <a href="../notes/07-sample-to-population.html">From Sample to Population</a></li>
</ul>
<hr>
</section>
<section id="reflective-questions" class="level2">
<h2 class="anchored" data-anchor-id="reflective-questions">Reflective Questions</h2>
<ul>
<li>A colleague removes every row with a blank cell “to be safe”. What would you need to know about those rows before you agreed with them?</li>
<li>Build A’s median session length is wrong in a direction you know but by an amount you do not. Should the report quote it at all? What would you write instead?</li>
<li>Two rows share a <code>session_id</code> but have different scores. What evidence would you use to decide which one to keep, and what do you do if there is none?</li>
<li>Your own game’s telemetry will have blanks. Which of your measures would you expect a crash or a rage-quit to leave blank, and what would that do to your results?</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/nmcguinness\.github\.io\/L8-3DGD-Playtest-Analytics\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../demos/stage-1.html" class="pagination-link" aria-label="Stage 1 Demo">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Stage 1 Demo</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notes/07-sample-to-population.html" class="pagination-link" aria-label="From Sample to Population">
        <span class="nav-page-text">From Sample to Population</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>COMP I8015 · 3D Game Development · Dundalk Institute of Technology</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>