<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Describing What You Have – Playtest Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notes/distributions-and-variation.html" rel="next">
<link href="../notes/why-measure.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-640402775883e0dc5b71a44650c95e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/ten-rules.html">Notes</a></li><li class="breadcrumb-item"><a href="../notes/describing-what-you-have.html">Describing What You Have</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Playtest Analytics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Start here</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Notes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/ten-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ten Rules for Reading Playtest Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/why-measure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Why Developers Measure Anything</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/describing-what-you-have.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Describing What You Have</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/distributions-and-variation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distributions and Variation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/visualising-with-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualising with ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/comparing-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comparing Playtest Conditions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Labs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/setting-up.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 00 — Setting Up</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/reading-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 01 — Reading Data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/reference-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistics Reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/r-quarto-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R and Quarto Reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reference/reference-ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ggplot2 Reference</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Demos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/week-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1 Demo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  <li><a href="#why-this-matters-for-playtesting" id="toc-why-this-matters-for-playtesting" class="nav-link" data-scroll-target="#why-this-matters-for-playtesting">Why This Matters for Playtesting</a></li>
  <li><a href="#what-kind-of-number-is-this" id="toc-what-kind-of-number-is-this" class="nav-link" data-scroll-target="#what-kind-of-number-is-this">What Kind of Number Is This?</a></li>
  <li><a href="#tidy-data-one-row-per-observation" id="toc-tidy-data-one-row-per-observation" class="nav-link" data-scroll-target="#tidy-data-one-row-per-observation">Tidy Data: One Row Per Observation</a></li>
  <li><a href="#sample-and-population" id="toc-sample-and-population" class="nav-link" data-scroll-target="#sample-and-population">Sample and Population</a></li>
  <li><a href="#centre" id="toc-centre" class="nav-link" data-scroll-target="#centre">Centre</a></li>
  <li><a href="#spread" id="toc-spread" class="nav-link" data-scroll-target="#spread">Spread</a></li>
  <li><a href="#look-at-the-shape-first" id="toc-look-at-the-shape-first" class="nav-link" data-scroll-target="#look-at-the-shape-first">Look at the Shape First</a></li>
  <li><a href="#worked-examples" id="toc-worked-examples" class="nav-link" data-scroll-target="#worked-examples">Worked Examples</a></li>
  <li><a href="#r-demonstrations" id="toc-r-demonstrations" class="nav-link" data-scroll-target="#r-demonstrations">R Demonstrations</a></li>
  <li><a href="#interpretation-guidance" id="toc-interpretation-guidance" class="nav-link" data-scroll-target="#interpretation-guidance">Interpretation Guidance</a></li>
  <li><a href="#common-mistakes" id="toc-common-mistakes" class="nav-link" data-scroll-target="#common-mistakes">Common Mistakes</a></li>
  <li><a href="#short-practice-activities" id="toc-short-practice-activities" class="nav-link" data-scroll-target="#short-practice-activities">Short Practice Activities</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#links-to-relevant-reference-material" id="toc-links-to-relevant-reference-material" class="nav-link" data-scroll-target="#links-to-relevant-reference-material">Links to Relevant Reference Material</a></li>
  <li><a href="#reflective-questions" id="toc-reflective-questions" class="nav-link" data-scroll-target="#reflective-questions">Reflective Questions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/ten-rules.html">Notes</a></li><li class="breadcrumb-item"><a href="../notes/describing-what-you-have.html">Describing What You Have</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Describing What You Have</h1>
<p class="subtitle lead">Variable types, tidy data, centre, spread and shape</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>Week 1, for everyone, before Part B of Lab 01. This is the vocabulary for describing a single variable: what kind of number it is, where its centre sits, how spread out it is and what shape it has. Every later page assumes it.</p>
</blockquote>
<hr>
<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning Outcomes</h2>
<p>By the end of these notes you can:</p>
<ul>
<li>classify a variable as nominal, ordinal, discrete or continuous, and say which operations that allows;</li>
<li>recognise a tidy table and name the most common way data fails to be one;</li>
<li>say what a sample is, and why every number you compute describes the sample rather than your audience;</li>
<li>choose between mean and median, and read the gap between them as evidence of skew;</li>
<li>describe spread with the standard deviation, quartiles and IQR, and say why the range is rarely enough;</li>
<li>draw a histogram and a boxplot in base R and say what each shows that a summary hides.</li>
</ul>
<hr>
</section>
<section id="why-this-matters-for-playtesting" class="level2">
<h2 class="anchored" data-anchor-id="why-this-matters-for-playtesting">Why This Matters for Playtesting</h2>
<p>Before comparing anything to anything, you have to be able to say what a single variable looks like. This section is the vocabulary for that, and it is the part students most often skip and most often get caught by.</p>
<hr>
</section>
<section id="what-kind-of-number-is-this" class="level2">
<h2 class="anchored" data-anchor-id="what-kind-of-number-is-this">What Kind of Number Is This?</h2>
<p>Four types, and the type decides which operations are legal.</p>
<p><strong>Nominal</strong> — labels with no order. Character class, platform, quit reason. You can count them. You cannot average them. The mean of <code>Scout</code> and <code>Sentinel</code> does not exist, and if your code produces one, something has gone wrong upstream.</p>
<p><strong>Ordinal</strong> — ordered labels with unknown gaps. Difficulty setting, player experience level, and every agreement scale ever printed. Novice, Regular and Veteran are in an order, but Regular is not “halfway” between the other two in any meaningful sense.</p>
<p><strong>Discrete</strong> — counts. Deaths, kills, items collected. Whole numbers, and there is no such thing as 2.4 deaths in a single session — though the <em>average</em> number of deaths across many sessions is perfectly meaningful at 2.4.</p>
<p><strong>Continuous</strong> — measurements. Completion time, frame time, distance travelled. Any value in a range, limited only by the precision of your instrument.</p>
<p><strong>The awkward case is the rating scale</strong>, and it is awkward every time. A 1–5 agreement scale is strictly <strong>ordinal</strong>: you know Agree is above Neutral, but you do not know that the step from Disagree to Neutral is the same size as the step from Agree to Strongly Agree. In practice, when a scale has five or more points and the responses are reasonably spread, people treat it as numeric and average it. That convention is defensible and universal, and you should still know you are making an assumption. Where it matters — where the whole finding rests on a mean of 3.2 against 3.4 — report the distribution instead.</p>
<hr>
</section>
<section id="tidy-data-one-row-per-observation" class="level2">
<h2 class="anchored" data-anchor-id="tidy-data-one-row-per-observation">Tidy Data: One Row Per Observation</h2>
<p>Data arrives in whatever shape the tool that produced it happened to use. Almost all analysis assumes one particular shape, and it is worth naming.</p>
<p>A table is <strong>tidy</strong> when each row is one observation, each column is one variable, and each cell is one value. For a playtest: one row per player per session, one column per thing you recorded.</p>
<p>The most common violation is a survey export, where the eight questions become eight columns. That is convenient to read and inconvenient to analyse, because “question” is really a variable and its eight values have been spread across the column headings. Reshaping it into one row per player <em>per question</em> is what makes the whole survey analysable in one operation, and you will do exactly that in Lab 03.</p>
<hr>
</section>
<section id="sample-and-population" class="level2">
<h2 class="anchored" data-anchor-id="sample-and-population">Sample and Population</h2>
<p>The 120 <em>Tidebreak</em> sessions come from 30 players who happened to attend this playtest. They are a <strong>sample</strong>. The <strong>population</strong> is everybody you are making the game for, and you never get to measure it.</p>
<p><strong>Every number describes the sample.</strong> The question you care about is always about the population: not “did these players struggle?” but “will players struggle?”. Bring in a different group next week and every figure on this page moves. How far it can move is the subject of Week 2; until then, report how many people a number came from every time you quote it (<a href="../notes/ten-rules.html">rule 8</a>).</p>
<p><strong>Who is in the sample matters as much as how many.</strong> A playtest recruited from the studio’s own Discord samples the game’s most committed fans, not its audience. No amount of analysis afterwards corrects for who walked in the door.</p>
<hr>
</section>
<section id="centre" class="level2">
<h2 class="anchored" data-anchor-id="centre">Centre</h2>
<p>Two summaries of “the typical value”, and choosing between them is a real decision, not a formality.</p>
<p>The <strong>mean</strong> adds everything and divides by the count. It uses every value, which is its strength, and it is dragged by extremes, which is its weakness.</p>
<p>The <strong>median</strong> is the middle value when sorted. Half above, half below. It ignores how extreme the extremes are, which is its strength and its weakness.</p>
<p><strong>When they disagree, the data is skewed, and the gap tells you which way.</strong> If the mean sits well above the median, a few large values are pulling it up: a long right tail. If it sits below, a group of small values is pulling it down.</p>
<p>For game data this is not an edge case, it is the norm. Completion times, session lengths and frame times are all skewed almost by construction — there is a floor on how fast anyone can finish and no ceiling on how slow. <strong>Default to the median for anything time-like</strong> and reach for the mean only when you have looked at the shape and satisfied yourself it is roughly symmetric.</p>
<p>When you compare the two, compare them relative to the size of the variable. A gap of 40 points on a score in the thousands is nothing; a gap of 3 minutes on a median of 26 is a real skew.</p>
<hr>
</section>
<section id="spread" class="level2">
<h2 class="anchored" data-anchor-id="spread">Spread</h2>
<p>The centre alone is nearly useless. Two levels with identical average completion times, one where everybody takes four minutes and one where half take one minute and half take seven, are not the same level.</p>
<p><strong>Range</strong> is minimum to maximum. Easy to quote and almost always misleading, since a single unusual value defines it entirely.</p>
<p><strong>Standard deviation</strong> is the typical distance from the mean. It is the right measure for roughly symmetric data and it inherits the mean’s sensitivity to extremes.</p>
<p><strong>Quartiles</strong> split the sorted data into four. The first quartile has a quarter below it, the third has three quarters. The <strong>interquartile range</strong> — the distance between them — is the width of the middle half of your players, and it is the most robust description of spread you have. For skewed game data, quote the median and the IQR together.</p>
<p><strong>Percentiles</strong> generalise this: the 95th percentile has 95% of values below it. <a href="../notes/distributions-and-variation.html">Distributions and Variation</a> will show you why the 99th percentile of frame time is the single most important number in a performance capture.</p>
<hr>
</section>
<section id="look-at-the-shape-first" class="level2">
<h2 class="anchored" data-anchor-id="look-at-the-shape-first">Look at the Shape First</h2>
<p>Every summary statistic throws information away. That is what a summary is for. The risk is that it throws away the finding.</p>
<p>A <strong>histogram</strong> shows you the whole distribution: where the bulk sits, whether it is symmetric, whether there is a second hump, whether there are outliers. Draw one before quoting any average. It costs one line.</p>
<p>The number of bins changes what you see, sometimes dramatically. Too few and a second hump disappears; too many and noise looks like structure. Try several. That a chart changes with its settings is not a flaw to hide — it is the first evidence that a chart is an argument rather than a fact, and you are responsible for the argument you make.</p>
<p>A <strong>boxplot</strong> compresses the same information into median, quartiles and outliers. It is less informative than a histogram for one variable and much better for comparing several groups side by side, which is what Section 4 is about.</p>
<p><strong>Two humps are always worth chasing.</strong> A distribution with two peaks usually means two populations have been mixed: players who found the key and players who did not, sessions that completed and sessions that crashed. The average of a bimodal distribution describes nobody at all — it names a value that sits in the valley between the two groups, where the fewest players actually are.</p>
<hr>
</section>
<section id="worked-examples" class="level2">
<h2 class="anchored" data-anchor-id="worked-examples">Worked Examples</h2>
<p><strong>Is the Sentinel underpowered?</strong> Sort the four archetypes by mean score and the Sentinel comes last, at 1313 points. A balance pass built on that number buffs the Sentinel.</p>
<p>Sort by median instead and the Sentinel is the second-highest, at 1528. The mean and the median disagree by 215 points, and the standard deviation is 455 against 225 to 259 for the other three. Something is dragging the mean down without moving the middle.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sentinel,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">12</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main   =</span> <span class="st">"Sentinel score, one bar per band"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab   =</span> <span class="st">"Score"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col    =</span> <span class="st">"grey85"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"white"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="describing-what-you-have_files/figure-html/worked-sentinel-hist-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The histogram answers it. 7 of the 30 Sentinel sessions scored under 700 and sit in a clump of their own at the far left, 274 points below the next-lowest Sentinel game. The Sentinel either anchors the round or collapses early. It is not underpowered; it is inconsistent. A flat buff raises the scores of the players already doing well, and the design question becomes what the collapsing games have in common (<a href="../notes/ten-rules.html">rule 4</a>).</p>
<p><strong>How clear was the objective?</strong> The survey item “I always knew what my objective was” averages 2.61 on a 1 to 5 scale. That is a mean of an ordinal rating, and the distribution says more:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(survey<span class="sc">$</span>objective_clear)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2  3  4  5 
24 31 37 24  4 </code></pre>
</div>
</div>
<p>55 of 120 players chose 1 or 2, and 4 chose 5. “46% of players disagreed that they always knew their objective” is a sentence a designer acts on. “Mean 2.61” is not (<a href="../notes/ten-rules.html">rule 3</a>).</p>
<hr>
</section>
<section id="r-demonstrations" class="level2">
<h2 class="anchored" data-anchor-id="r-demonstrations">R Demonstrations</h2>
<p>All base R. The variable here is <code>time_alive_s</code>, seconds survived in the match.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sessions<span class="sc">$</span>time_alive_s)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   60.0   105.0   133.0   130.4   155.5   180.0 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(sessions<span class="sc">$</span>time_alive_s)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32.74505</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(sessions<span class="sc">$</span>time_alive_s)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(sessions<span class="sc">$</span>time_alive_s, <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  10%   90% 
 82.0 175.2 </code></pre>
</div>
</div>
<p><code>summary()</code> gives centre and quartiles in one call; <code>sd()</code> and <code>IQR()</code> give the two measures of spread; <code>quantile()</code> with a vector of proportions gives any percentiles you ask for, here the 10th and 90th.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sessions<span class="sc">$</span>time_alive_s,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">15</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main   =</span> <span class="st">"Time alive per session"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab   =</span> <span class="st">"Seconds"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col    =</span> <span class="st">"grey85"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"white"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="describing-what-you-have_files/figure-html/demo-hist-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><code>breaks</code> sets roughly how many bars. Change it and look again before believing any shape.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(sessions<span class="sc">$</span>cohort)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Novice Regular Veteran 
     33      53      34 </code></pre>
</div>
</div>
<p><code>table()</code> counts a categorical variable. It is the only summary a nominal variable has.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(sessions<span class="sc">$</span>time_alive_s, sessions<span class="sc">$</span>cohort, median)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Novice Regular Veteran 
  127.0   137.0   143.5 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(time_alive_s <span class="sc">~</span> cohort,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> sessions,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Time alive by cohort"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Seconds"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col  =</span> <span class="st">"grey85"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="describing-what-you-have_files/figure-html/demo-by-group-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><code>tapply()</code> applies one function to one variable, split by a group. The boxplot shows the same split as a picture: the thick line is the median, the box is the middle half, and the whiskers and points show the rest.</p>
<hr>
</section>
<section id="interpretation-guidance" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-guidance">Interpretation Guidance</h2>
<p><strong>A description has four parts: centre, spread, shape and size.</strong> One sentence can hold all four:</p>
<blockquote class="blockquote">
<p>Median time alive was 133 seconds (IQR 50.5, n = 120). The mean sits 2.6 seconds from the median, so the centre is not being pulled by a tail. 11 sessions sit at exactly 180 seconds, the full match: those players never died, and the tallest bar on the right is a ceiling, not a peak.</p>
</blockquote>
<p><strong>Pick the summary to fit the shape, and say why.</strong> Median and IQR for anything skewed or with outliers; mean and standard deviation only when the histogram is roughly symmetric.</p>
<p><strong>Keep what the data shows apart from what it suggests.</strong> “The Sentinel’s scores fall into two groups” is what the data shows. “Some Sentinel players do not know how to play the role” is a suggestion, and it needs a different kind of evidence before it becomes a conclusion.</p>
<hr>
</section>
<section id="common-mistakes" class="level2">
<h2 class="anchored" data-anchor-id="common-mistakes">Common Mistakes</h2>
<p><strong>Averaging a label.</strong> <code>mean(sessions$cohort)</code> returns <code>NA</code> with a warning, which is R protecting you. Code the cohorts as 1, 2 and 3 and R will average them happily, and the answer will mean nothing.</p>
<p><strong>Trusting R’s idea of the type.</strong> R stores <code>cohort</code> as text and every survey item as a number. Neither is wrong, but neither tells R that cohorts come in an order or that a rating is ordinal. The type R prints is where your checking starts (<a href="../notes/ten-rules.html">rule 3</a>).</p>
<p><strong>Quoting a mean without looking.</strong> The Sentinel’s mean is a correct calculation that describes no Sentinel game. Draw the histogram first (<a href="../notes/ten-rules.html">rule 4</a>).</p>
<p><strong>Quoting the range as the spread.</strong> One extreme player sets the range on their own. Quote the IQR.</p>
<p><strong>Trusting one bin setting.</strong> A histogram drawn once is one argument among several the data could make. Redraw it with fewer and more bars.</p>
<p><strong>Leaving out n.</strong> “Players rated it 2.6” means nothing without “out of how many” (<a href="../notes/ten-rules.html">rule 8</a>).</p>
<hr>
</section>
<section id="short-practice-activities" class="level2">
<h2 class="anchored" data-anchor-id="short-practice-activities">Short Practice Activities</h2>
<p>Each takes two or three minutes.</p>
<p><strong>1.</strong> Classify each of these as nominal, ordinal, discrete or continuous: <code>kills</code>, <code>quit_reason</code>, <code>cohort</code>, <code>distance_m</code>, <code>visual_style</code>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>kills</code> discrete; <code>quit_reason</code> nominal; <code>cohort</code> ordinal; <code>distance_m</code> continuous; <code>visual_style</code> ordinal (a 1 to 5 rating), whatever type R gives it.</p>
</div>
</div>
</div>
<p><strong>2.</strong> Describe <code>distance_m</code> in one sentence with centre, spread and size. Does the mean sit above or below the median?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(sessions<span class="sc">$</span>distance_m)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 381.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(sessions<span class="sc">$</span>distance_m)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 176.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sessions<span class="sc">$</span>distance_m)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 387.8833</code></pre>
</div>
</div>
<p>Median distance was 381.5 m (IQR 176.5, n = 120). The mean sits above the median by 6.4 m, which is small against a spread of that size.</p>
</div>
</div>
</div>
<p><strong>3.</strong> Use <code>table()</code> to find the most common number of deaths in a session. Why is <code>table()</code> sensible for <code>deaths</code> but not for <code>distance_m</code>?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(sessions<span class="sc">$</span>deaths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 0  1  2  3  4  5  6  7 
 4 18 26 23 31 12  4  2 </code></pre>
</div>
</div>
<p>The most common count is 4 deaths. Deaths is discrete with only a handful of possible values, so counting each one is informative. 110 of the 120 <code>distance_m</code> values are different, so its table is mostly a list of ones; a continuous variable needs a histogram instead.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li>The type of a variable decides which summaries are legal. A 1 to 5 rating is ordinal, and averaging it is an assumption you should know you are making.</li>
<li>Tidy data has one row per observation and one column per variable.</li>
<li>Every number describes the sample. Report n every time.</li>
<li>When mean and median disagree, the data is skewed. Default to the median for anything time-like.</li>
<li>Describe spread with the IQR for skewed data and the standard deviation for symmetric data. The range is rarely enough.</li>
<li>Look at the histogram before quoting any average. Two humps mean two groups.</li>
</ul>
<hr>
</section>
<section id="links-to-relevant-reference-material" class="level2">
<h2 class="anchored" data-anchor-id="links-to-relevant-reference-material">Links to Relevant Reference Material</h2>
<ul>
<li><a href="../notes/ten-rules.html">Ten Rules</a>: rule 3 (know what kind of number you are holding), rule 4 (look at the shape before you quote the average), rule 5 (the mean is the wrong summary more often than you think) and rule 8 (small samples lie confidently)</li>
<li><a href="../reference/r-quarto-reference.html#describing-one-variable">R and Quarto Reference: describing one variable</a>, <a href="../reference/r-quarto-reference.html#describing-by-group">describing by group</a> and <a href="../reference/r-quarto-reference.html#plots">plots</a></li>
<li><a href="../labs/reading-data.html">Lab 01: exploring playtest data</a>, Part B</li>
</ul>
<hr>
</section>
<section id="reflective-questions" class="level2">
<h2 class="anchored" data-anchor-id="reflective-questions">Reflective Questions</h2>
<ul>
<li>Take a variable from your own project’s telemetry. Which of the four types is it, and what would break if you treated it as the type next door?</li>
<li>Why is the median usually the right summary for completion time, but not for something like accuracy percentage?</li>
<li>You draw a histogram of level completion times and see two clear humps. List three things that could have caused that, and say how you would tell them apart.</li>
<li>A teammate reports “average session length is 22 minutes”. What two further numbers would you ask for before letting that into a report?</li>
</ul>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notes/why-measure.html" class="pagination-link" aria-label="Why Developers Measure Anything">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Why Developers Measure Anything</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notes/distributions-and-variation.html" class="pagination-link" aria-label="Distributions and Variation">
        <span class="nav-page-text">Distributions and Variation</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>COMP I8015 · 3D Game Development · Dundalk Institute of Technology</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>