{
  "hash": "93811435ae67b6126ff5f24ebab31810",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"From Sample to Population\"\nsubtitle: \"Why the next playtest would give different numbers\"\nbody-classes: \"wf-at-compare\"\n---\n\n```{=html}\n<nav class=\"wf-strip\" aria-label=\"Where this page sits in the evidence workflow\">\n  <span class=\"wf-label\">Workflow</span>\n  <ol>\n    <li class=\"wf-step wf-question\">Question</li>\n    <li class=\"wf-step wf-measure\">Measure</li>\n    <li class=\"wf-step wf-collect\">Collect</li>\n    <li class=\"wf-step wf-clean\">Clean</li>\n    <li class=\"wf-step wf-describe\">Describe</li>\n    <li class=\"wf-step wf-compare\">Compare/Relate</li>\n    <li class=\"wf-step wf-interpret\">Interpret</li>\n    <li class=\"wf-step wf-act\">Act</li>\n  </ol>\n</nav>\n```\n\n\n\n\n> Every number in a playtest report describes the players who happened to turn\n> up. Bring in a different group and every number moves. This page is about how\n> far: what **sampling variability** is, and how a **confidence interval** turns\n> one playtest's number into an honest range for the players you care about. The\n> playtest question running through it: *\"Build B sessions averaged 24 minutes.\n> How sure can we be?\"*\n\n::: {.at-a-glance}\n**Stage:** 2 · Core.\n**Time:** 15 minutes in class (the two simulation figures); the rest is reading.\n**Before this:** [Cleaning and Transforming](06-cleaning-and-transforming.qmd).\n**Key terms:** sampling variability, sampling distribution, standard error,\nconfidence interval.\n**R you will write:** `t.test(x)$conf.int`.\n:::\n\n## Learning Outcomes\n\nBy the end of these notes you can:\n\n- explain why a second playtest with different players would give different\n  numbers, even if nothing about the game changed;\n- say in plain words what a sampling distribution is and what the standard error\n  measures, and tell the standard error from the standard deviation;\n- compute a 95% confidence interval for a mean with `t.test()`, and say what the\n  \"95%\" does and does not mean;\n- report a mean with its interval and its n.\n\n---\n\n## Why This Matters for Playtesting\n\nBuild B's sessions were longer than Build A's. Is that because Build B is better,\nor because Build B happened to get the more patient players? You cannot answer\nthat until you know how much a number would move by chance alone.\n\nThat is what this page is for. **Every comparison in Stage 2 rests on it.** The\nnext page, [Comparing Groups](08-comparing-groups.qmd), uses it to decide whether a\ndifference between builds is real.\n\n---\n\n## Sampling Variability\n\nSplit the 120 *Tidebreak* sessions into four batches of 30, in the\norder they were recorded, and treat each as a separate playtest. Same game, same\nbuild mix, same procedure. The mean score of each batch:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  mutate(batch = ceiling(row_number() / 30)) |>   # rows 1-30 are batch 1, and so on\n  group_by(batch) |>\n  summarise(mean_score = round(mean(score)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  batch mean_score\n  <dbl>      <dbl>\n1     1       1550\n2     2       1313\n3     3       1462\n4     4       1390\n```\n\n\n:::\n:::\n\n\nFour playtests, four different answers, from 1313 to\n1550. Nothing changed except which players were in each batch.\n\n**Sampling variability** is this: a different sample gives a different number,\neven from the same population. It is not a mistake and it cannot be avoided. The\nonly question is how big it is, and that depends on two things: **how much the\nplayers differ** (the SD) and **how many of them you measured** (n).\n\n---\n\n## The Sampling Distribution\n\nTo see sampling variability properly you need many playtests, not four. Real\nstudios cannot afford that, but a simulation can.\n\nImagine everyone who will ever play *Tidebreak*, and suppose their session lengths\nlook exactly like the 120 you recorded. Build that population by\ncopying the sessions a thousand times over, then run a thousand imaginary\nplaytests of 30 players each, and record each playtest's mean. You do not need to\nwrite this code; read it as a description of the experiment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop <- rep(sessions$session_minutes, times = 1000)   # the imaginary population\n\nset.seed(7)\nmeans_30 <- replicate(1000, mean(sample(pop, 30)))    # 1,000 playtests of 30\n```\n:::\n\n\n`sample(pop, 30)` draws 30 players at random; `mean()` is that playtest's result;\n`replicate(1000, ...)` runs it a thousand times. The thousand means form the\n**sampling distribution**: the spread of results across every playtest you might\nhave run.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nop <- par(mfrow = c(1, 2), mar = c(4, 3, 2, 1))\nhist(pop, breaks = 26, col = pal$fill, border = \"white\", main = \"Individual sessions\",\n     xlab = \"Session length (minutes)\", ylab = \"\", yaxt = \"n\", cex.main = 0.9)\nabline(v = pop_mean, col = pal$highlight, lwd = 2)\nhist(means_30, breaks = 30, col = pal$fill, border = \"white\",\n     main = \"1,000 playtest means, n = 30\", xlim = range(pop),\n     xlab = \"Mean session length (minutes)\", ylab = \"\", yaxt = \"n\", cex.main = 0.9)\nabline(v = pop_mean, col = pal$highlight, lwd = 2)\npar(op)\n```\n\n::: {.cell-output-display}\n![Individual sessions (left) are lopsided and two-humped. The means of 1,000 playtests of 30 (right) are far less spread out, and centred on the truth.](07-sample-to-population_files/figure-html/fig-sampling-dist-1.png){#fig-sampling-dist fig-alt='Two histograms on the same horizontal scale. Left: the population of session lengths, piled up near 30 minutes with a second smaller hump around 12 minutes. Right: the distribution of 1,000 sample means, a narrow symmetric bell centred near 23 minutes.' width=768}\n:::\n:::\n\n\nTwo things stand out.\n\n**The means are centred on the truth.** The population mean is\n22.8 minutes; the average of the thousand playtest means is\n22.8. Any one playtest misses, but not systematically in\none direction.\n\n**The means are far less spread out than the players.** Individual sessions run\nfrom 7.7 to 32 minutes. Playtest means of 30 players fall almost\nall between 19.9 and\n25.3. Averaging cancels out most of the\ndifferences between players.\n\n### The standard error\n\nThe spread of the sampling distribution has its own name: the **standard error**\n(SE). It is how far one playtest's mean is typically off from the truth. You never\nget to run a thousand playtests, but you do not need to: the SE can be estimated\nfrom one sample as the SD divided by the square root of n.\n\n**You need to know** the difference between the two:\n\n- The **SD** describes the *players*: how much one session differs from another.\n- The **SE** describes your *estimate*: how much your mean would move if you ran\n  the playtest again.\n\nMore players does not make the players less varied, so the SD stays put. It makes\nyour estimate steadier, so the SE shrinks, but slowly: **four times the players\nhalves the SE**.\n\n**Going further:** why the formula works, why the means form a bell even when the\ndata does not (the central limit theorem), and the bootstrap are on\n[Sampling Theory](../going-further/sampling-theory.qmd).\n\n---\n\n## Confidence Intervals\n\nAbout 95% of playtest means land within about 2 SEs of the true mean. Turn that\nround, and the true mean is within about 2 SEs of your playtest's mean 95% of the\ntime. That range is a **95% confidence interval**:\n\n> mean ± about 2 × SE\n\n**For real:** Build B's 60 sessions. `t.test()` computes the interval for you:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmins_b <- sessions$session_minutes[sessions$build == \"B\"]\nmean(mins_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.24167\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(mins_b)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22.44820 26.03513\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n**In a report you would write:** \"Build B sessions averaged\n24.2 minutes (95% CI 22.4 to 26, n = 60).\" The\ninterval says the data is consistent with a population average anywhere from\n22.4 to 26 minutes. That honesty is the point:\na reader now knows how much weight the 24.2 can bear.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Going further: these sessions are not quite independent\"}\nThe interval treats Build B's 60 sessions as 60 independent\nobservations. They are not: they come from 15 players who each played\n4 times, and one player's sessions\nresemble each other. The honest effective sample size is somewhere between the\nnumber of players and the number of sessions, so the true interval is somewhat\nwider than this one. Handling repeated measurements properly needs methods beyond\nthis course; the practical lesson is to report both counts\n([rule 8](ten-rules.qmd)).\n:::\n\n### What \"95%\" means\n\nThis is the most misread number in statistics. **The 95% describes the method,\nnot this particular interval.** If you ran the playtest many times and computed an\ninterval each time, about 95% of those intervals would contain the true population\nmean. Any one interval either contains it or does not; you never know which.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nmiss <- cis[, 1] > pop_mean | cis[, 2] < pop_mean\npar(mar = c(4, 4, 1, 1))\nplot(NA, xlim = range(cis), ylim = c(1, 20), yaxt = \"n\",\n     xlab = \"Mean session length (minutes)\", ylab = \"Playtest\")\naxis(2, at = c(1, 5, 10, 15, 20), las = 1)\nsegments(cis[, 1], 1:20, cis[, 2], 1:20, lwd = 2,\n         col = ifelse(miss, pal$highlight, pal$line))\npoints(rowMeans(cis), 1:20, pch = 19, cex = 0.7,\n       col = ifelse(miss, pal$highlight, pal$line))\nabline(v = pop_mean, lty = 2, lwd = 2, col = pal$guide)\n```\n\n::: {.cell-output-display}\n![Twenty simulated playtests of 30 players, each with its 95% confidence interval. About one in twenty misses the true mean (dashed line), and nothing warns you which one.](07-sample-to-population_files/figure-html/fig-twenty-cis-1.png){#fig-twenty-cis fig-alt='Twenty horizontal line segments stacked vertically, each with a dot at its centre. A vertical dashed line marks the true mean. Most segments cross the dashed line; the ones that do not are drawn in red.' width=768}\n:::\n:::\n\n\nIn this run, 1 of the 20 intervals missed the true mean, close to the one\nin twenty the method promises. A playtest that misses has done nothing wrong; it\ndrew an unusual set of players, which is exactly what the 5% allows for.\n\n**So do not say** \"there is a 95% chance the true mean is between\n22.4 and 26\". In a report, give the interval\nand let it stand for \"the plausible range\".\n\n**Wider means less certain.** An interval narrows with more players (a smaller SE)\nand widens with more varied players (a larger SD).\n\n**For your project:** your playtests will be small, often a dozen players. Your\nintervals will be wide. That is not a failure: it is the honest size of what a\ndozen players can tell you, and it is exactly what the Discussion section of your\nreport should say.\n\n---\n\n## Worked Example\n\n**Build B sessions averaged 24 minutes. How sure can we be?** The draft report\nsays: \"Build B sessions last 24 minutes on average.\"\n\n**Step 1: what is the sample?** 60 sessions from 15 players, one\nplaytest. A different group would give a different mean.\n\n**Step 2: how much would it move?** The SD of Build B's session lengths is\n6.94 minutes, so the standard error is\n0.9 minutes. A second playtest's mean would typically land within\nabout 0.9 minutes of this one.\n\n**Step 3: give the range.** The 95% confidence interval is 22.4 to 26\nminutes.\n\n**Step 4: rewrite.** \"Build B sessions averaged 24.2 minutes\n(95% CI 22.4 to 26; 60 sessions from 15 players).\" The claim\nis now as strong as the data, and no stronger.\n\n**Step 5: notice what is still missing.** This is one build on its own. Whether\nBuild B's sessions are longer than Build A's is a different question, because both\nnumbers wobble. Comparing two groups, and asking whether the gap could be chance, is\n[Comparing Groups](08-comparing-groups.qmd).\n\n---\n\n## Interpretation Guidance\n\n**What the data shows.** One playtest's mean: 24.2 minutes\nfor Build B.\n\n**What the analysis suggests.** The population mean is plausibly anywhere from\n22.4 to 26 minutes, with values near the centre\nof that range more plausible than values at its ends.\n\n**What can legitimately be concluded.** A range, not a point. A decision that\ndepends on the exact value of a mean, such as \"sessions must average 25 minutes\",\ncannot be settled by a playtest whose interval spans both sides of 25.\n\n---\n\n## Common Mistakes\n\n**Treating one playtest's number as a fact about the game.** It is a fact about\nthose players. Give the interval.\n\n**Confusing the SD and the SE.** The SD describes the players; the SE describes\nyour estimate. Reporting an SE as if it were the spread of the players makes the\nplayers look far more alike than they are.\n\n**Reading \"95%\" as the chance this interval is right.** It describes how often the\nmethod works, not this interval.\n\n**Expecting a bigger sample to fix everything.** Four times the players halves the\nSE. Doubling the playtest buys less precision than it seems.\n\n**Forgetting that sessions are not players.** Repeated sessions from the same\nplayer are not independent, so an interval built on sessions is somewhat too\nnarrow. Report both counts.\n\n**Trusting an interval from a handful of players.** With five players and skewed\ndata, the interval is not reliable. Say so rather than quoting it.\n\n---\n\n## Practice\n\nEach takes two or three minutes.\n\n1. **Predict.** A playtest of 25 players gives an SE of 2 minutes. Roughly what SE\n   would 100 players give? And 400?\n2. **Compute.** Find the 95% confidence interval for the mean session length of\n   **Build A**, and compare its width with Build B's.\n3. **Critique.** A report says: \"Mean enjoyment was 4.1 (SE 0.08), so players\n   agreed closely about how much they enjoyed it.\" What is wrong?\n4. **Interpret.** In @fig-twenty-cis, one of the red intervals came from a\n   playtest. Did that playtest do anything wrong?\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show answers\"}\n**1.** About 1 minute with 100 players (four times the players, half the SE) and\nabout 0.5 with 400 (sixteen times the players, a quarter of the SE). Each halving\ncosts four times as many players.\n\n**2.** `diff()` of the interval gives its width:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmins_a <- sessions$session_minutes[sessions$build == \"A\"]\nt.test(mins_a)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.15051 23.43949\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(t.test(mins_a)$conf.int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.288983\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(t.test(mins_b)$conf.int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.58693\n```\n\n\n:::\n:::\n\n\nBuild A's interval is 19.2 to 23.4\nminutes, and it is wider: the same number of sessions, but Build A's session\nlengths are more spread out (SD\n8.3 against\n6.9), because of its two groups of players.\n\n**3.** The SE says how precisely the *mean* is known, not how much players agreed.\nWith 120 sessions, the SE is small even if players disagreed widely.\nTo describe agreement, report the SD or the distribution. (Enjoyment is also a 1 to\n7 rating, so the distribution is the better summary anyway; see\n[Data, Variables and Types](03-data-and-types.qmd#the-rating-scale-question).)\n\n**4.** No. It drew an unusual set of players by chance. A 95% method is designed to\nmiss about one time in twenty, and nothing in the data warns you when it is your\nturn. That is why a single surprising result is a reason to run another playtest,\nnot to redesign the game.\n:::\n\n---\n\n## Summary\n\n- A different sample gives a different number. That is sampling variability, and\n  it is unavoidable.\n- The sampling distribution is the spread of a summary across every playtest you\n  might have run. Its spread is the standard error: how far your estimate is\n  typically off.\n- The SD describes the players; the SE describes your estimate. Four times the\n  players halves the SE.\n- A 95% confidence interval is about mean ± 2 SE, from `t.test(x)$conf.int`. The\n  95% describes the method: it captures the true value in about 95% of playtests.\n- Report a mean with its interval and n.\n\n| Key term | Meaning |\n| :- | :- |\n| **Sampling variability** | Different samples from the same population give different results |\n| **Sampling distribution** | The distribution of a summary across many possible samples |\n| **Standard error** | How far an estimate is typically off: the spread of the sampling distribution |\n| **Confidence interval** | A range of plausible values for the population, given the sample |\n\n---\n\n## Links\n\n- [Ten Rules](ten-rules.qmd): rule 8 (small samples lie confidently)\n- [Sampling Theory](../going-further/sampling-theory.qmd): the SE formula, the\n  central limit theorem, the interval by hand, the bootstrap\n- [Statistics Reference: from sample to population](../reference/reference-statistics.qmd#from-sample-to-population)\n- [Lab 02: Comparing Builds](../labs/comparing-builds.qmd), Part B\n- [Stage 2 demo](../demos/stage-2.qmd)\n- Next: [Comparing Groups](08-comparing-groups.qmd)\n\n---\n\n## Reflective Questions\n\n- Your playtest found a mean session length of 24 minutes, and your producer wants\n  \"the number\". Do you give them 24, or the interval? What do you say to justify\n  your choice?\n- Doubling the playtest from 30 to 60 players narrows the interval by less than a\n  third. When is that worth the cost, and when is it not?\n- Your interval for Build B is built on sessions, but players played four sessions\n  each. Is the true interval wider or narrower, and why does it matter for a\n  design decision?\n- Your team's next playtest will have twelve players. What would you say in the\n  report about how far its numbers can be trusted?\n",
    "supporting": [
      "07-sample-to-population_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}