{
  "hash": "f53bee3a7ec9a474d16c0c601dc65004",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Comparing Groups\"\nsubtitle: \"Is the difference real, and does it matter?\"\nbody-classes: \"wf-at-uncertainty wf-at-test\"\naliases:\n  - comparing-conditions.html\n---\n\n```{=html}\n<nav class=\"wf-strip\" aria-label=\"Where this page sits in the analytical workflow\">\n  <span class=\"wf-label\">Workflow</span>\n  <ol>\n    <li class=\"wf-step wf-ask\">Ask</li>\n    <li class=\"wf-step wf-collect\">Collect</li>\n    <li class=\"wf-step wf-clean\">Inspect &amp; clean</li>\n    <li class=\"wf-step wf-visualise\">Visualise</li>\n    <li class=\"wf-step wf-describe\">Describe</li>\n    <li class=\"wf-step wf-uncertainty\">Quantify uncertainty</li>\n    <li class=\"wf-step wf-test\">Test</li>\n    <li class=\"wf-step wf-confounds\">Confounds</li>\n    <li class=\"wf-step wf-interpret\">Interpret</li>\n    <li class=\"wf-step wf-report\">Report</li>\n  </ol>\n</nav>\n```\n\n\n\n\n> Every build comparison ends with a difference, because two groups of people\n> never produce identical numbers. This page is about the two questions that\n> follow: **could the difference be chance?** and **is it big enough to matter?**\n> It builds the idea of a p-value from a simple shuffle, then introduces the\n> t-test, paired designs, comparing proportions, and the errors any test can make.\n> The playtest question running through it: *\"Did the new signposting reduce wrong\n> turns?\"*\n\n::: {.at-a-glance}\n**Time:** 30 minutes in class; 25 more for the Going further sections.\n**Before this:** [From Sample to Population](07-sample-to-population.qmd).\n**Key terms:** observed difference, permutation test, null hypothesis,\nalternative hypothesis, p-value, significance level, Type I error, Type II error,\npower, effect size, t-test, paired design, practical significance, multiple\ncomparisons.\n**R introduced:** `sample()` for shuffling, `t.test()` for two groups and pairs,\n`prop.test()`, `qqnorm()`, `aggregate()`.\n:::\n\n## Learning Outcomes\n\nBy the end of these notes you can:\n\n- work through **visualise → describe → estimate difference → confidence interval\n  → statistical test → interpret** in that order;\n- explain a p-value through a permutation test, and say what it is and is not;\n- name the two errors a test can make, and explain how sample size affects power;\n- run and read an independent-samples t-test, a paired t-test and a test of two\n  proportions, and choose between them from the design;\n- report a difference with its size and confidence interval, and tell statistical\n  significance from practical significance;\n- check a test's assumptions at a practical level, including with a Q-Q plot;\n- explain why testing many things at once produces false alarms.\n\n---\n\n## Why This Matters for Playtesting\n\nBuild B's players took fewer wrong turns, or scored more, or quit less. The\nquestion is never \"is there a difference?\" but **\"is this difference telling me\nsomething about the build, or only about the players who happened to turn up?\"**\n\n**A playtest is a sample.** [From Sample to Population](07-sample-to-population.qmd)\nshowed that every mean wobbles from one playtest to the next. When you compare two\ngroups, both means wobble, and so does the gap between them. Before you rebuild a\nlevel on the strength of a difference, you need to know whether that difference\nwould survive a second playtest.\n\n**And a real difference can still be worthless.** With enough data, a change too\nsmall for any player to notice becomes statistically detectable. A result can be\ncertain and irrelevant at the same time. Deciding whether it matters is a design\njudgement, and no test makes it for you.\n\n---\n\n## The Workflow\n\nComparing two conditions always follows the same six steps, in this order:\n\n| Step | Question | Tool |\n| :- | :- | :- |\n| 1. Visualise | What do the two distributions look like? | Side-by-side boxplots, strip charts |\n| 2. Describe | Where is each centre, how wide is each spread? | Means, medians, SDs, IQRs |\n| 3. Estimate the difference | How far apart are the groups in this sample? | Difference in means |\n| 4. Confidence interval | How far apart could they plausibly be, for players in general? | `t.test()` |\n| 5. Test | Could a gap this size be chance alone? | Permutation test, `t.test()` |\n| 6. Interpret | Is it real, is it big enough, and what do we do? | Judgement |\n\n**The test comes fifth, not first.** A p-value with no picture and no size\nattached cannot be interpreted. If the boxplots show a gap nobody would care\nabout, no p-value changes that ([rule 7](ten-rules.qmd)).\n\n---\n\n## Look, Describe, Estimate\n\nThe *Tidebreak* team added signposting to Build B. Did players get lost less?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(wrong_turns ~ build, data = sessions, col = pal$fill, outline = FALSE,\n        ylab = \"Wrong turns per session\", xlab = \"Build\")\nstripchart(wrong_turns ~ build, data = sessions, vertical = TRUE, add = TRUE,\n           method = \"jitter\", jitter = 0.15, pch = 19,\n           col = adjustcolor(c(pal$build_a, pal$build_b), alpha.f = 0.5))\ntapply(sessions$wrong_turns, sessions$build, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       A        B \n8.916667 5.516667 \n```\n\n\n:::\n\n```{.r .cell-code}\ntapply(sessions$wrong_turns, sessions$build, sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       A        B \n2.374238 2.702740 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Wrong turns per session in each build. Every session is a point; the boxes summarise them.](08-comparing-groups_files/figure-html/fig-wt-look-1.png){#fig-wt-look fig-alt='Two boxplots of wrong turns per session, Build A higher than Build B, with every session drawn as a jittered point on top. Build A\\'s points cluster around 8 to 10; Build B\\'s around 4 to 7, with overlap between the two.' width=768}\n:::\n:::\n\n\nBuild A's players averaged 8.9 wrong turns per session and\nBuild B's 5.5. The **observed difference** is\n3.4 wrong turns: your best single estimate of the true difference,\nand almost certainly not exactly right. The two boxes do not overlap, but the\npoints do: plenty of individual Build A sessions had fewer wrong turns than plenty\nof Build B sessions.\n\nA **confidence interval for the difference** works the same way as the interval\nfor one mean in [From Sample to Population](07-sample-to-population.qmd#confidence-intervals),\nusing the standard error of the gap. Here it runs from 2.5 to 4.3\nwrong turns. **Read it as a range of plausible sizes**: the signposting saved\nsomewhere between 2.5 and\n4.3 wrong turns per session. **If an interval includes\nzero, \"no difference\" is still plausible**; this one is nowhere near zero.\n\n---\n\n## Could It Be Chance? The Permutation Test\n\nSuppose the signposting did nothing. Then the build label on each session is\narbitrary: each player would have taken the same number of wrong turns whichever\nbuild they had been given. So you could shuffle the labels, give every session a\nrandom build, and the gap between the \"builds\" would be just as large as the real\none.\n\nThat is a test you can run. **Shuffle the build labels, recompute the gap, and\nrepeat ten thousand times.** The shuffled gaps show what differences chance alone\nproduces. If the real gap looks like them, chance is a fine explanation. If it is\nfar outside them, chance is not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngap <- function(y, g) mean(y[g == \"A\"]) - mean(y[g == \"B\"])\n\nobserved <- gap(sessions$wrong_turns, sessions$build)\nset.seed(1)\nshuffled <- replicate(10000, gap(sessions$wrong_turns, sample(sessions$build)))\n\nobserved\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.4\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(abs(shuffled))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.166667\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(abs(shuffled) >= abs(observed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n`sample(sessions$build)` shuffles the labels; `replicate()` does it ten thousand\ntimes. The real gap is 3.4. The largest gap in ten thousand\nshuffles is 2.17.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar = c(4, 4, 1, 1))\nhist(shuffled_wt, breaks = 40, col = pal$fill, border = \"white\", main = \"\",\n     xlim = c(-3.6, 3.6), xlab = \"Difference in mean wrong turns (A − B)\",\n     ylab = \"Shuffles\")\nabline(v = gap_wt, col = pal$highlight, lwd = 3)\ntext(gap_wt, par(\"usr\")[4] * 0.9, \"observed\", pos = 2, col = pal$highlight, cex = 0.85)\n```\n\n::: {.cell-output-display}\n![The gap in mean wrong turns from 10,000 random shufflings of the build labels, against the real gap. Chance never came close.](08-comparing-groups_files/figure-html/fig-permutation-1.png){#fig-permutation fig-alt='A bell-shaped histogram of shuffled differences centred on zero, running from about −2 to +2. A red vertical line marks the observed difference of 3.4, far to the right of every bar.' width=768}\n:::\n:::\n\n\n**The proportion of shuffles at least as extreme as the real gap is the\np-value.** Here not one of ten thousand was, so p is below 1 in 10,000. If the\nsignposting did nothing, a gap this large would essentially never happen.\n\n**Most results are less clear-cut.** The same test on the 1–7 difficulty rating\ngives a gap of 0.42 points (Build B rated harder), and\n3.9% of shuffles produce a gap at least that large in either\ndirection:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlim <- ceiling(max(abs(shuffled_df)) * 20) / 20 + 0.05\nbr  <- seq(-lim, lim, by = 0.05)\nh  <- hist(shuffled_df, breaks = br, plot = FALSE)\npar(mar = c(4, 4, 1, 1))\nplot(h, col = ifelse(abs(h$mids) >= abs(obs_df), pal$highlight, pal$fill),\n     border = \"white\", main = \"\", xlab = \"Difference in mean difficulty (A − B)\",\n     ylab = \"Shuffles\")\nabline(v = c(obs_df, -obs_df), lty = 2, col = pal$line)\n```\n\n::: {.cell-output-display}\n![The p-value is a tail area. The shaded bars are the shuffles at least as extreme as the observed difficulty gap, in either direction.](08-comparing-groups_files/figure-html/fig-pvalue-tail-1.png){#fig-pvalue-tail fig-alt='A bell-shaped histogram of shuffled differences in difficulty rating centred on zero. The bars beyond the observed gap on both sides are shaded red; they are a small fraction of the total.' width=768}\n:::\n:::\n\n\nThat 3.9% is the difficulty p-value. Chance alone produces a\ngap that size in roughly one shuffle in 26: unusual, but not\nunheard of.\n\n---\n\n## The Language of Testing\n\nThe shuffle has a formal vocabulary.\n\nThe **null hypothesis** is the claim of no difference: here, that the build makes\nno difference to wrong turns. The shuffle is a simulation of the world where the\nnull is true. The **alternative hypothesis** is that the build does make a\ndifference.\n\nThe **p-value** is the probability of seeing a difference at least as large as the\none observed, *if the null hypothesis were true*. A small p-value means the data\nwould be surprising in a world where the builds did not differ.\n\n::: {.callout-important}\n**A p-value is not the probability that the null hypothesis is true.**\n\nIt is calculated by *assuming* the null is true, so it cannot also measure how\nlikely the null is. p = 0.03 does not mean \"a 3% chance the builds are the same\".\nIt means \"if the builds were the same, a gap this large would turn up about 3% of\nthe time\".\n:::\n\n**The significance level**, written α (alpha), is the threshold you choose\n**before** looking, conventionally 0.05. If p falls below it, the result is called\n**statistically significant**: \"unlikely to be chance alone\", and nothing more.\nChoosing it in advance is the same discipline as deciding what would change your\nmind before you look at the data ([rule 1](ten-rules.qmd)).\n\n**Not significant does not mean no difference.** A large p-value means this sample\ncould not rule out chance. That can be because there is no difference, or because\nthere were too few players to see one. The confidence interval tells you which.\n\n---\n\n## Two Ways to Be Wrong\n\nA test makes a decision from incomplete information, so it can be wrong in two\ndirections.\n\n| | The build really makes no difference | The build really makes a difference |\n| :- | :- | :- |\n| **Test says \"significant\"** | **Type I error**: a false alarm | Correct |\n| **Test says \"not significant\"** | Correct | **Type II error**: a missed effect |\n\n**A Type I error** is acting on a difference that is not there: rebuilding a level\nbecause of a fluke. Its rate is α. To check, draw two groups of 30 from the *same*\npopulation of wrong turns, so there is no real difference, and test them two\nthousand times: 5.3% come out significant, close to the 5% that α\n= 0.05 promises.\n\n**A Type II error** is missing a difference that is there: shipping a build with a\nproblem because the playtest was too small to see it. The chance of *avoiding* it\nis the test's **power**. Power grows with sample size. Drawing playtests of\ndifferent sizes from *Tidebreak*'s real Build A and Build B sessions, and counting\nhow often the t-test detects the signposting effect:\n\n| Sessions per build | 5 | 10 | 15 | 30 |\n| :- | :-: | :-: | :-: | :-: |\n| Chance of detecting the effect | 44% | 78% | 94% | >99% |\n\nEven this large effect is missed more often than not with five sessions per build.\nA smaller effect needs far more players. **Plan the playtest size around the\nsmallest difference that would change your decision**, which is the \"how many\nplayers\" question from [Planning a Playtest](01-planning-a-playtest.qmd#how-many-players),\nnow with numbers.\n\n**The two errors trade off.** A stricter α, such as 0.01, means fewer false alarms\nand more missed effects. Which mistake is worse depends on the decision: a false\nalarm that costs a week of rework, or a missed problem that ships to every player.\n\n---\n\n## The t-Test: the Shortcut\n\nShuffling ten thousand times works for any summary, but for comparing two means\nthere is a formula that gives almost the same answer instantly: the **t-test**. It\nrelies on the central limit theorem from\n[From Sample to Population](07-sample-to-population.qmd#the-central-limit-theorem),\nwhich says that the gap between two means is approximately normal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- t.test(wrong_turns ~ build, data = sessions)\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  wrong_turns by build\nt = 7.3208, df = 116.07, p-value = 3.492e-11\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n 2.480141 4.319859\nsample estimates:\nmean in group A mean in group B \n       8.916667        5.516667 \n```\n\n\n:::\n:::\n\n\n`t.test(y ~ group)` is the **independent-samples t-test**, for when different\nplayers tested each build. R runs the Welch version by default, which does not\nassume the two builds have the same spread, and that is the right default. Read\nthree parts of the output: the **sample estimates** (the two means), the **95\npercent confidence interval** (for Build A minus Build B), and the **p-value**.\n\n`$` pulls single parts out of the result, which is how you get numbers into a\nsentence with inline R instead of copying them by hand:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult$estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean in group A mean in group B \n       8.916667        5.516667 \n```\n\n\n:::\n\n```{.r .cell-code}\nresult$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.480141 4.319859\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nresult$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.491687e-11\n```\n\n\n:::\n:::\n\n\n**The two methods agree.** For wrong turns, both say p is tiny. For difficulty,\nthe shuffle gave p = 0.038 and the t-test gives\np = 0.032. The shuffle shows what the p-value *means*; the t-test\nis how you will usually compute it.\n\n---\n\n## Size Matters: Effect Size and Practical Significance\n\n**Practical significance** is whether a difference is large enough to change a\ndesign decision. Statistical significance cannot tell you this, because it depends\non how much data you have as well as on how big the difference is.\n\n**Lead with the size.** The **effect size** in its simplest form is the difference\nitself, in the units a designer understands, with its interval: \"Build B's players\ntook 3.4 fewer wrong turns per session (95% CI\n2.5 to 4.3).\" A designer can judge whether 3 wrong turns matters;\nnobody can judge a p-value.\n\n**The Atrium shows why.** The frame-time capture has 3000 frames from\nthe Atrium zone. There, Build B's frames are 0.42 ms\nfaster than Build A's, p < 0.001. That is about as statistically\nsignificant as a result gets, and no player can perceive a difference of less than\nhalf a millisecond per frame. Nobody should schedule work around it.\n\n| | Practically small | Practically large |\n| :- | :- | :- |\n| **Statistically significant** | Real but not worth acting on | Act on it |\n| **Not significant** | Nothing to see, if the interval is narrow | Test more players: the sample was too small to tell |\n\n**Always report the size of the difference.** \"Significant\" alone hides which cell\nof that table you are in.\n\n::: {.callout-note collapse=\"true\" title=\"Going further: Cohen's d\"}\nWhen measures are on different scales, a **standardised** effect size lets you\ncompare them. **Cohen's d** divides the difference in means by the typical SD of\nthe two groups:\n\n$$d = \\frac{\\text{mean}_A - \\text{mean}_B}{\\text{pooled SD}}$$\n\nFor wrong turns, d = 1.34: the groups are well over one SD apart.\nA common rough guide calls 0.2 small, 0.5 medium and 0.8 large, but those labels\ncome from psychology; in a playtest, \"large\" means large enough to change a design\ndecision, which only the units can tell you.\n:::\n\n---\n\n## Two Designs: Independent and Paired\n\nHow the playtest was run decides which test you use\n([Planning a Playtest](01-planning-a-playtest.qmd#choose-a-design-who-plays-what)).\n\n**Independent samples.** Different players test each build. That is how the\n*Tidebreak* sessions file was collected: 30 players, each of whom played\nonly one build. Use the independent-samples t-test, as above.\n\n**Paired.** The same players test both builds. `tidebreak_paired.csv` records a\nsecond study in which 30 players each played both. Each player is\ncompared with themselves, so their skill cancels out. Use the **paired t-test**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar = c(4, 4, 1, 1))\nmatplot(rbind(paired$wrong_turns_a, paired$wrong_turns_b), type = \"l\", lty = 1,\n        col = adjustcolor(pal$line, alpha.f = 0.4), xaxt = \"n\", xlim = c(0.8, 2.2),\n        xlab = \"\", ylab = \"Wrong turns\")\naxis(1, at = 1:2, labels = c(\"Build A\", \"Build B\"))\nlines(1:2, colMeans(paired[, c(\"wrong_turns_a\", \"wrong_turns_b\")]),\n      col = pal$highlight, lwd = 4)\n```\n\n::: {.cell-output-display}\n![Each line is one player in the paired study: their wrong turns in Build A and in Build B. Most lines slope down.](08-comparing-groups_files/figure-html/fig-paired-1.png){#fig-paired fig-alt='Thirty grey lines joining each player\\'s wrong turns in Build A on the left to Build B on the right. Most slope downward; players who took many wrong turns in Build A tend to take many in Build B too. A thick red line joins the two means.' width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(paired$wrong_turns_a, paired$wrong_turns_b, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  paired$wrong_turns_a and paired$wrong_turns_b\nt = 6.0932, df = 29, p-value = 1.234e-06\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 1.838014 3.695319\nsample estimates:\nmean difference \n       2.766667 \n```\n\n\n:::\n:::\n\n\n`paired = TRUE` compares each player's two values. The estimate is the **mean\ndifference**: on average, a player took 2.8 fewer wrong\nturns in Build B. 26 of 30 players improved,\n2 stayed the same and 2 got worse.\n\n**Ignoring the pairing throws away what the design bought you.** The same numbers\ntested as if the players were different people give the same estimate, but the\ninterval is 3.2 wrong turns wide against\n1.9 for the paired test. In @fig-paired, players\nwho take many wrong turns in one build take many in the other: the correlation is\n0.67. The paired test\nremoves that player-to-player variation; the unpaired test has to allow for it.\n\n**Paired designs bring their own problems:** learning, order and fatigue effects.\nIf everyone plays Build A first, some of Build B's improvement is just practice.\nCounterbalancing fixes it, but `tidebreak_paired.csv` does not record which build\neach player played first, so this study cannot rule it out.\n\n---\n\n## Comparing Proportions\n\nNot every outcome is a number. \"Did the session end in a frustration quit?\" is yes\nor no, and the comparison is between two **proportions**:\n20 of 60 Build A sessions\n(33%) against 5 of\n60 in Build B (8%).\n\n`prop.test()` takes the counts of \"yes\" and the group sizes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrustrated <- tapply(sessions$quit_reason == \"Frustrated\", sessions$build, sum)\nsessions_n <- table(sessions$build)\nprop.test(frustrated, sessions_n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  frustrated out of sessions_n\nX-squared = 9.9032, df = 1, p-value = 0.00165\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.09506413 0.40493587\nsample estimates:\n    prop 1     prop 2 \n0.33333333 0.08333333 \n```\n\n\n:::\n:::\n\n\nThe difference is 25\npercentage points, with a 95% interval from\n10 to 40 points,\np = 0.002. Build A's frustration rate is higher, and even the low\nend of the interval is a difference a designer would care about. The same logic as\nthe t-test, for a yes/no outcome.\n\n---\n\n## Checking the Assumptions\n\nA t-test is reliable when these hold closely enough. None needs a formal test; each\nneeds a look.\n\n| Assumption | What it means | How to check | *Tidebreak* |\n| :- | :- | :- | :- |\n| **Independence** | One observation does not influence another | Think about how the data was collected | Each player contributed 4 sessions, so the 120 sessions are really 30 players |\n| **No strong outliers** | No few values dominate the means | Boxplots | 3 flagged wrong-turn counts across 120 sessions |\n| **Approximate normality** | The means are roughly normal; with small groups, the data should be too | A Q-Q plot | Close enough; counts are whole numbers, which shows as steps |\n| **Appropriate design** | Independent test for separate groups, paired test for the same people | How the playtest was run | Sessions: independent. Paired file: paired |\n\n**A Q-Q plot** places each value against where it would sit if the data were\nperfectly normal. Close to the line means close to normal:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nop <- par(mfrow = c(1, 2), mar = c(4, 4, 2, 1))\nqqnorm(sessions$wrong_turns, main = \"Wrong turns\", pch = 19, cex = 0.6,\n       col = pal$line)\nqqline(sessions$wrong_turns, col = pal$highlight, lwd = 2)\nb_ms <- frames$ms[frames$build == \"B\"]\nqqnorm(b_ms, main = \"Build B frame times\", pch = 19, cex = 0.4, col = pal$line)\nqqline(b_ms, col = pal$highlight, lwd = 2)\npar(op)\n```\n\n::: {.cell-output-display}\n![Q-Q plots. Wrong turns (left) follow the line in steps, because they are whole numbers. Build B's frame times (right) bend sharply away at the top: a long tail of slow frames.](08-comparing-groups_files/figure-html/fig-qq-1.png){#fig-qq fig-alt='Two Q-Q plots. Left: wrong turns, with points in horizontal steps lying along the diagonal reference line. Right: Build B frame times, with points along the line in the middle but curving steeply upward at the right end.' width=768}\n:::\n:::\n\n\nWrong turns are fine for a t-test. Frame times are not: a t-test compares means,\nand the mean is the wrong summary for that tail, as\n[Distributions and Shape](05-distributions-and-shape.qmd#worked-example) showed.\n\n**With a few dozen players per group, normality matters least**, thanks to the\ncentral limit theorem. Strong outliers and a mismatched design matter far more,\nand no amount of data fixes the wrong design.\n\n**The independence problem has a simple check.** Average each player's sessions\ninto one value, then compare players rather than sessions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nper_player <- aggregate(wrong_turns ~ player_id + build,\n                        data = sessions, FUN = mean)\nnrow(per_player)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(wrong_turns ~ build, data = per_player)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.361153 4.438847\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n`aggregate()` averages each player's sessions into one row, leaving\n30 players instead of 120 sessions. The difference\nis the same and the interval is a little wider, 2.4 to 4.4,\nbecause there are fewer independent observations. The conclusion survives.\n\n---\n\n## Testing Many Things at Once\n\nAt α = 0.05, each test on a difference that is not real has a 5% chance of a false\nalarm. Run several and the chances add up. With eight independent tests, the chance\nthat **at least one** comes up significant by luck alone is\n1 − 0.95^8 = 34%.\n\nThe *Tidebreak* survey has 8 items. Testing each one by build:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsv <- merge(survey, sessions[, c(\"session_id\", \"build\")])\nround(sort(sapply(names(survey)[-1],\n                  function(i) t.test(sv[[i]] ~ sv$build)$p.value)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    objective_clear controls_responsive    death_understood        match_length \n              0.000               0.150               0.257               0.273 \n    difficulty_fair     level_navigable        visual_style    would_play_again \n              0.724               0.854               0.884               1.000 \n```\n\n\n:::\n:::\n\n\nOne item, `objective_clear`, is significant. Is it real, or the one-in-three false\nalarm? Three things say real. It survives the simplest correction, **Bonferroni**:\ndivide α by the number of tests, here 0.05 / 8 =\n0.0063, and its p-value is still below that. It was the\nitem the team expected to move, written down before the test. And it agrees with\nthe telemetry: Build A had the frustration quits.\n\n**The defence is to decide in advance.** Name the comparisons that answer your\nquestion before you run any of them. A result you went looking for after scanning\ntwenty tests needs a second playtest before anyone acts on it\n([rule 1](ten-rules.qmd)).\n\n---\n\n## Which Test?\n\n```{mermaid}\n%%| label: fig-which-test\n%%| fig-cap: \"Choosing a test for comparing two groups. Always look at the data first.\"\nflowchart TD\n  S[\"Two groups to compare<br/>(after looking at the data)\"] --> Q1{\"What kind of outcome?\"}\n  Q1 -->|\"Yes / no<br/>e.g. frustration quit\"| P[\"prop.test()<br/>two proportions\"]\n  Q1 -->|\"A number<br/>e.g. wrong turns\"| Q2{\"Same players<br/>in both groups?\"}\n  Q2 -->|\"Yes\"| PT[\"t.test(x, y, paired = TRUE)<br/>paired t-test\"]\n  Q2 -->|\"No\"| Q3{\"Is the mean the<br/>right summary?\"}\n  Q3 -->|\"Yes: roughly symmetric,<br/>no extreme tail\"| IT[\"t.test(y ~ group)<br/>independent t-test\"]\n  Q3 -->|\"No: heavy tail,<br/>e.g. frame times\"| PM[\"Compare the summary that matters,<br/>e.g. 99th percentile,<br/>with a permutation test\"]\n  classDef q fill:#f8f9fa,stroke:#6c757d,color:#212529\n  classDef t fill:#fbeaea,stroke:#b22222,color:#212529\n  class S q\n  class P,PT,IT,PM t\n```\n\nThe permutation test works for any summary: replace `mean()` in the shuffle with\n`median()` or `quantile(x, 0.99)` and the logic is unchanged. That is what makes it\nthe fallback when a mean is the wrong thing to compare.\n\n---\n\n## Worked Example\n\n**Did the signposting reduce wrong turns?** The six steps, in order.\n\n*Visualise.* @fig-wt-look: Build B's box sits lower. The boxplot flags\n3 outlying sessions in Build A and 0 in Build B, too\nfew to dominate either mean.\n\n*Describe.* Build A's median is 9 wrong turns and Build B's is\n5. Build B's spread is wider: an IQR of 4.25 against\n2.\n\n*Estimate the difference.* 8.9 against\n5.5: a difference of 3.4.\n\n*Confidence interval.* 2.5 to 4.3 wrong turns. Nowhere near zero.\n\n*Test.* p < 0.001, and no shuffle in ten thousand came close.\n\n*Interpret.* The signposting reduced wrong turns, and the smallest plausible\nreduction, 2.5 per session, is still large enough for a\nplayer to feel. The result survives counting each player once, and the separate\npaired study points the same way. Keep the signposting.\n\n**Was Build B harder?** The same steps on the 1–7 difficulty rating give a second\nsignificant result. Build B was rated 0.42 points harder,\np = 0.032, with a confidence interval from 0.04 to 0.8\npoints.\n\nThree things say not to act on it. The size is small: under half a point on a\nseven-point scale. The interval's lower end, 0.04, is a\ndifference no player would report. And the play data does not back it up: deaths\ndid not differ between the builds (p = 0.679). Statistically\nsignificant, practically marginal, and unsupported by what players actually did.\nNote it, and check it in the next playtest.\n\n---\n\n## Interpretation Guidance\n\n**What the data shows.** In this playtest, Build B's players averaged\n3.4 fewer wrong turns per session than Build A's (95% CI\n2.5 to 4.3, p < 0.001). In a separate study where\n30 players played both builds, they took\n2.8 fewer in Build B (95% CI\n1.8 to 3.7).\n\n**What the analysis suggests.** The signposting helps players find their way, and\nby enough to matter. Two different designs, with different players, point the same\nway.\n\n**What can legitimately be concluded.** The reduction is very unlikely to be\nchance, and even its smallest plausible size is a noticeable improvement. The\npaired study cannot separate the signposting from practice, because play order was\nnot recorded; the independent study does not have that problem, which is why the\ntwo together are stronger than either alone.\n\n**Write the result as a sentence a designer can use.** Lead with the size, give\nthe interval, then the p-value:\n\n> Build B's players took 3.4 fewer wrong turns per session on\n> average (95% CI 2.5 to 4.3, p < 0.001).\n\n\"The result was significant\" is not a finding. It names no size and no action\n([rule 10](ten-rules.qmd)).\n\n---\n\n## Common Mistakes\n\n**Reading the p-value as the chance the null is true.** It is the chance of data\nthis extreme *if* the null is true.\n\n**Reading \"not significant\" as \"no difference\".** It means this sample could not\ntell. Check the confidence interval: narrow and around zero is evidence of no\nmeaningful difference; wide is a sample too small to say.\n\n**Reading \"significant\" as \"important\".** The Atrium frame times are among the\nmost significant results in the whole playtest and among the least important.\n\n**Testing before looking.** A t-test on data you have not drawn can hide outliers,\nskew or two groups mixed together. Visualise first, every time.\n\n**Using the independent test on paired data.** It gives an interval far wider than\nthe data supports. Match the test to the design.\n\n**Testing every column and reporting what came up.** With eight tests, a false alarm\nsomewhere is likely. Decide which comparisons answer your question first.\n\n**Running too small a playtest and concluding \"no effect\".** With five sessions per\nbuild, even the large signposting effect is missed more than half the time.\n\n**Comparing means when the mean is the wrong summary.** A t-test on frame times\nasks the wrong question. Compare the percentile that matters.\n\n**Counting sessions as players.** Check that the result survives when each player\ncounts once.\n\n---\n\n## Practice\n\nEach takes two or three minutes.\n\n**1. Predict.** If you shuffled the build labels and recomputed the gap in mean\n*enjoyment*, would the real gap stand out from the shuffles? Then run the t-test and\nuse the confidence interval to answer: did the signposting cost enjoyment?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(enjoyment ~ build, data = sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  enjoyment by build\nt = 0, df = 113.42, p-value = 1\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n -0.3483742  0.3483742\nsample estimates:\nmean in group A mean in group B \n       3.933333        3.933333 \n```\n\n\n:::\n:::\n\n\nNo: the p-value is 1, so the real gap looks exactly like\nthe shuffles. The interval says more: it runs from -0.35 to 0.35\npoints on a seven-point scale, so any true difference is smaller than half a point\neither way. That is evidence the signposting did not cost enjoyment, a stronger\nstatement than \"not significant\".\n:::\n\n**2. Compute.** Run the paired data through both the paired and the unpaired\nt-test. Why is the paired interval narrower?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(paired$wrong_turns_a, paired$wrong_turns_b, paired = TRUE)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.838014 3.695319\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(paired$wrong_turns_a, paired$wrong_turns_b)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.180570 4.352763\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\nPlayers who take many wrong turns in one build take many in the other. The paired\ntest compares each player with themselves, so that player-to-player variation drops\nout. The unpaired test leaves it in and has to allow for it.\n:::\n\n**3. Decide.** Build B's sessions were longer on average. Run the test on\n`session_minutes`. Is the difference statistically significant? Is it practically\nsignificant?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(session_minutes ~ build, data = sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  session_minutes by build\nt = -2.1091, df = 114.42, p-value = 0.03711\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n -5.7142078 -0.1791255\nsample estimates:\nmean in group A mean in group B \n       21.29500        24.24167 \n```\n\n\n:::\n:::\n\n\n\n\nStatistically, yes: p = 0.037. Practically, it is hard to say. The\ninterval says Build B's sessions were 0.2 to 5.7 minutes longer: anywhere\nfrom 11 seconds to 5.7 minutes. The\ndirection is clear and the size is not, which is a case for a larger playtest\nrather than a decision. (Session length is also two-humped in Build A, so a\ndifference in means hides *how* the builds differ; the retention curve in\n[Distributions and Shape](05-distributions-and-shape.qmd#the-retention-curve) shows\nit.)\n:::\n\n**4. Critique.** A team tested 12 players, 6 per build, found p = 0.4 for wrong\nturns, and concluded: \"The new signposting has no effect.\" What would you tell\nthem?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\nWith 5 sessions per build, even an effect as large as *Tidebreak*'s is detected\nonly 44% of the time (the power table above), and 6 is not\nmuch better. So p = 0.4 is what you would often see whether or not the signposting\nworks. \"No effect\" is not supported. They\nshould report the difference and its confidence interval, which will be wide, and\nrun a larger or paired playtest.\n:::\n\n---\n\n## Summary\n\n- Work in order: visualise, describe, estimate the difference, compute the\n  confidence interval, test, interpret.\n- A permutation test shuffles the group labels to see what chance produces. The\n  p-value is the share of shuffles at least as extreme as the real result.\n- A p-value is how surprising the data would be if there were no difference. It is\n  not the probability that there is no difference.\n- A Type I error is a false alarm (rate α); a Type II error is a missed effect.\n  Power, the chance of detecting a real effect, grows with sample size.\n- The t-test is the shortcut for comparing means: independent for different\n  players, paired for the same players. `prop.test()` compares two proportions.\n- Lead with the size of the difference and its interval. Statistically significant\n  means unlikely to be chance; practically significant means big enough to act on.\n- Testing many things produces false alarms. Decide the comparisons in advance.\n\n| Key term | Meaning |\n| :- | :- |\n| **Observed difference** | The gap between the groups in your sample |\n| **Permutation test** | Shuffling group labels to see what differences chance produces |\n| **Null hypothesis** | The claim of no difference |\n| **p-value** | The chance of a difference at least this large if the null were true |\n| **Significance level (α)** | The p-value threshold chosen in advance, usually 0.05 |\n| **Type I error** | Concluding there is a difference when there is none |\n| **Type II error** | Missing a difference that is there |\n| **Power** | The chance a test detects a real effect of a given size |\n| **Effect size** | How big the difference is, in units or standardised |\n| **t-test** | The standard test for a difference in means |\n| **Paired design** | The same players measured under both conditions |\n| **Practical significance** | Whether a difference is big enough to change a decision |\n| **Multiple comparisons** | Running many tests, which inflates the chance of a false alarm |\n\n---\n\n## Links\n\n- [Ten Rules](ten-rules.qmd): rule 1 (decide what would change your mind before you\n  look), rule 7 (compare distributions, not averages), rule 8 (small samples lie\n  confidently) and rule 10 (a finding that does not name an action is not\n  finished)\n- [Statistics Reference: testing a difference](../reference/reference-statistics.qmd#testing-a-difference)\n- [R and Quarto Reference: relationships and tests](../reference/r-quarto-reference.qmd#relationships-and-tests)\n- [Lab 02: Comparing Builds](../labs/comparing-builds.qmd#part-b-is-the-difference-real-and-does-it-matter),\n  Part B\n- [Week 2 demo](../demos/week-2.qmd)\n- Next: [Visualising with ggplot2](09-visualising-with-ggplot2.qmd)\n\n---\n\n## Reflective Questions\n\n- Build B's difficulty rating was significantly higher, but deaths did not change.\n  What would you need to see in the next playtest to take the difficulty result\n  seriously?\n- A colleague says the paired study proves the signposting works because its\n  p-value is smaller. What is wrong with that argument, and what does the paired\n  study add that the sessions data does not?\n- You can afford 30 testers for the next build comparison. Would you run them as\n  two independent groups of 15 or as one paired group of 30? What would you have to\n  control in the paired design?\n- Which is worse for your project: a false alarm that costs a week of rework, or a\n  missed problem that ships? How should that change the α you choose?\n",
    "supporting": [
      "08-comparing-groups_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}