{
  "hash": "060cbb1cc87d0a168dce301cbd7c7c97",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 01 — Reading Data\"\nsubtitle: \"Stage 1: vectors, missing values, loading a playtest, and describing what happened\"\n---\n\n::: {.callout-note appearance=\"simple\" icon=\"false\" title=\"Get the files\"}\n- **Data:** [tidebreak_sessions.csv](../data/tidebreak_sessions.csv){download=\"tidebreak_sessions.csv\"}. Save them in the `data/` folder of your project.\n:::\n\n# Overview\n\nThis lab is your first hands-on session with R. You are not expected to have\nwritten a line of it before, but read\n[R from First Principles](../notes/02-r-first-principles.qmd) first: every idea in\nPart A is introduced there.\n\nThe work is deliberately unglamorous. Before you can find anything interesting in\na playtest you have to be able to **load the data, look at it, and describe it**\nwithout making a fool of yourself. That is what this lab trains. By the end you\nwill have answered the Stage 1 question, *what happened?*, for a real playtest, and\nsaid what it means for the game.\n\n| Function | What it does |\n| :- | :- |\n| `c()`, `length()`, `class()` | Build a vector; how many values, and what type |\n| `is.na()`, `na.rm = TRUE` | Find missing values; leave them out of a calculation |\n| `read_csv()`, `glimpse()` | Read a CSV; look at it without printing every row |\n| `$` | Pull out one column as a vector |\n| `count()` | Count each value of a categorical variable |\n| `mean()`, `median()`, `sd()`, `IQR()`, `quantile()` | Describe a numeric variable |\n| `group_by()`, `summarise()`, `n()`, `\\|>` | The same summaries, once per group |\n| `hist()`, `boxplot()` | See the shape of a variable |\n\n# Learning outcomes\n\nBy the end of this lab you can:\n\n- create and index vectors, and explain what `NA` does to a calculation\n- load a CSV and inspect it without printing 120 rows\n- classify any column as **nominal**, **ordinal**, **discrete** or **continuous**\n- describe a numeric variable with an appropriate centre and spread, and draw it\n- summarise a variable for each group with `group_by()` and `summarise()`\n- read a retention curve, and say in one sentence when the mean is the wrong\n  summary and why\n\n# Ground rules\n\n- Keep the CSV files in the `data/` folder of the project.\n- Type the code. Do not copy and paste from the solutions until you have tried.\n- Open the solution **after** your attempt, even when your attempt worked. The\n  solution sometimes does it a better way.\n- Every exercise ends with a short written answer. Write it. The writing is the\n  part that matters; the code is how you get there.\n- If a line of code fails, read the error before doing anything else. Most R\n  errors name the exact problem.\n\n# Setup (run this first)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)   # read_csv()\nlibrary(dplyr)   # count(), group_by(), summarise() and the rest\n\ncsv_file <- \"data/tidebreak_sessions.csv\"\n\nif (!file.exists(csv_file))\n  stop(\"CSV not found: \", csv_file,\n       \"\\nCheck that the file sits in the data/ folder of the project.\")\n\nsessions <- read_csv(csv_file, show_col_types = FALSE)\n\nnrow(sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n:::\n\n\n---\n\n# Part A — Values, vectors and missing data\n\nNotes for this part: [Planning a Playtest](../notes/01-planning-a-playtest.qmd),\n[R from First Principles](../notes/02-r-first-principles.qmd) and\n[Data, Variables and Types](../notes/03-data-and-types.qmd). Keep the\n[R and Quarto Reference](../reference/r-quarto-reference.qmd) open while you work.\n\n## Exercise 01 — Build a vector and look at it `[Do]`\n\nCreate a vector called `deaths` holding the death counts from six playtest\nsessions: 4, 2, 7, 3, 0, 5.\n\nReport how many values it holds and what type R thinks it is.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths <- c(4, 2, 7, 3, 0, 5)\n\ndeaths\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4 2 7 3 0 5\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(deaths)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(deaths)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n:::\n\n\nR stores plain numbers as numeric, whether or not they have a decimal point.\n:::\n\n**Write 1 sentence:** why does a vector have to hold values of a single type?\n\n## Exercise 02 — Pull values out by position `[Do]`\n\nUsing `deaths` from Exercise 01, extract the first value, then the third and fifth\nvalues together.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\ndeaths[c(3, 5)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7 0\n```\n\n\n:::\n:::\n\n\nSquare brackets take a position, or a vector of positions built with `c()`.\n:::\n\n**Write 1 sentence:** R counts from 1, not 0. If you have written C# or C++, what\nis the one mistake this will cause you?\n\n## Exercise 03 — A missing value poisons the arithmetic `[Do]`\n\nA seventh tester's death count was not recorded. Add `NA` to the end of `deaths`\nand take the mean. Then take it again so that the result is a number.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths <- c(deaths, NA)\n\nmean(deaths)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(deaths, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.5\n```\n\n\n:::\n:::\n\n\n`NA` is not zero and it is not \"empty\". It means *unknown*, and the mean of a set\ncontaining an unknown value is itself unknown. R tells you that rather than\nquietly guessing.\n:::\n\n**Write 2 sentences:** `na.rm = TRUE` makes the `NA` go away. Explain why that is\nnot the same thing as fixing the problem.\n\n## Exercise 04 — Count with a condition `[Apply]`\n\nUsing the seven-value `deaths` vector, produce a TRUE/FALSE vector showing which\nsessions had more than 3 deaths, use it to extract those death counts, then count\nhow many sessions that is and what proportion of the recorded sessions it is.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths > 3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  TRUE FALSE  TRUE FALSE FALSE  TRUE    NA\n```\n\n\n:::\n\n```{.r .cell-code}\ndeaths[deaths > 3]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  4  7  5 NA\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(deaths > 3, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(deaths > 3, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5\n```\n\n\n:::\n:::\n\n\nTwo things worth noticing. `deaths[deaths > 3]` keeps the `NA`, because R does not\nknow whether the unknown value is above 3 or not. And `sum()` on a TRUE/FALSE\nvector counts the TRUEs, because TRUE is 1 and FALSE is 0, so `mean()` gives the\nproportion.\n:::\n\n**Write 1–2 sentences:** why is `sum(x > 3)` a count rather than a total?\n\n## Exercise 05 — Build a small table of related vectors `[Apply]`\n\nCreate two more vectors the same length as `deaths`: `player` (P01 to P07) and\n`build` (alternating `\"A\"` and `\"B\"`, starting with A). Combine all three into a\ndata frame called `mini`, then look at it with `glimpse()`.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplayer <- c(\"P01\", \"P02\", \"P03\", \"P04\", \"P05\", \"P06\", \"P07\")\nbuild  <- c(\"A\", \"B\", \"A\", \"B\", \"A\", \"B\", \"A\")\n\nmini <- data.frame(player, build, deaths)\n\nglimpse(mini)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 7\nColumns: 3\n$ player <chr> \"P01\", \"P02\", \"P03\", \"P04\", \"P05\", \"P06\", \"P07\"\n$ build  <chr> \"A\", \"B\", \"A\", \"B\", \"A\", \"B\", \"A\"\n$ deaths <dbl> 4, 2, 7, 3, 0, 5, NA\n```\n\n\n:::\n:::\n\n\nEach vector becomes a column, and the column takes the vector's name. They must\nall be the same length: one value per session.\n:::\n\n**Write 1 sentence:** what does a data frame give you that three separate vectors\ndo not?\n\n---\n\n# Part B — Loading and describing real data\n\nNotes for this part: [Describing Variables](../notes/04-describing-variables.qmd)\nand [Distributions and Shape](../notes/05-distributions-and-shape.qmd).\n\nFrom here on you are working with `sessions`, loaded in the Setup block: 120\nplaytest sessions from the *Tidebreak* arena.\n\n## Exercise 06 — Look at a data frame without drowning in it `[Do]`\n\nAnswer these without printing the whole table: how many rows and columns, what the\ncolumns are called, and what type each one is.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(sessions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 120\nColumns: 26\n$ session_id        <chr> \"S001\", \"S002\", \"S003\", \"S004\", \"S005\", \"S006\", \"S00…\n$ player_id         <chr> \"P01\", \"P02\", \"P03\", \"P04\", \"P05\", \"P06\", \"P07\", \"P0…\n$ cohort            <chr> \"Regular\", \"Veteran\", \"Regular\", \"Novice\", \"Veteran\"…\n$ archetype         <chr> \"Scout\", \"Scout\", \"Scout\", \"Scout\", \"Scout\", \"Scout\"…\n$ build             <chr> \"A\", \"B\", \"A\", \"B\", \"A\", \"B\", \"A\", \"B\", \"A\", \"B\", \"A…\n$ accuracy          <dbl> 55, 54, 48, 35, 67, 51, 57, 42, 51, 47, 56, 40, 60, …\n$ mobility          <dbl> 84, 91, 89, 80, 97, 90, 95, 73, 86, 86, 84, 83, 92, …\n$ survivability     <dbl> 48, 52, 42, 35, 56, 41, 45, 30, 35, 40, 49, 27, 46, …\n$ objective_control <dbl> 39, 66, 43, 47, 55, 45, 53, 39, 51, 49, 52, 35, 52, …\n$ support           <dbl> 52, 46, 52, 28, 38, 56, 47, 46, 34, 51, 55, 40, 53, …\n$ awareness         <dbl> 77, 91, 74, 74, 95, 87, 83, 67, 79, 82, 88, 67, 88, …\n$ score             <dbl> 1370, 1795, 1690, 1544, 2019, 1614, 1652, 1331, 1632…\n$ kills             <dbl> 7, 5, 5, 7, 12, 7, 6, 7, 7, 10, 9, 5, 10, 10, 5, 8, …\n$ deaths            <dbl> 4, 2, 2, 4, 3, 5, 4, 4, 3, 4, 3, 5, 5, 5, 5, 4, 4, 2…\n$ objectives        <dbl> 0, 2, 4, 2, 4, 4, 3, 2, 3, 3, 4, 1, 1, 1, 2, 4, 1, 2…\n$ shots_fired       <dbl> 148, 140, 190, 92, 143, 149, 143, 126, 138, 137, 118…\n$ time_alive_s      <dbl> 98, 105, 115, 80, 121, 115, 118, 99, 103, 71, 143, 7…\n$ distance_m        <dbl> 571, 520, 533, 349, 542, 566, 572, 308, 560, 451, 40…\n$ session_minutes   <dbl> 12.9, 24.6, 12.5, 18.8, 18.7, 25.3, 11.5, 27.0, 14.4…\n$ quit_reason       <chr> \"Frustrated\", \"Lost interest\", \"Frustrated\", \"Lost i…\n$ wrong_turns       <dbl> 8, 4, 9, 7, 10, 9, 9, 2, 11, 2, 3, 7, 5, 6, 8, 2, 8,…\n$ items_collected   <dbl> 3, 5, 2, 3, 4, 0, 5, 6, 7, 5, 2, 6, 3, 0, 0, 6, 3, 7…\n$ completed         <lgl> TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FAL…\n$ difficulty        <dbl> 4, 4, 3, 3, 3, 5, 4, 5, 4, 5, 3, 6, 5, 5, 6, 5, 4, 4…\n$ enjoyment         <dbl> 2, 5, 6, 4, 3, 3, 4, 3, 4, 3, 5, 3, 4, 4, 3, 4, 3, 3…\n$ comment           <chr> \"Could not tell where I was meant to go.\", \"The sign…\n```\n\n\n:::\n:::\n\n\n`glimpse()` gives you the size, every column's name, its type and its first few\nvalues in one go. It is the first thing to run on any new data.\n:::\n\n**Write 1 sentence:** why is printing a whole data frame a bad habit, even when it\nis small?\n\n## Exercise 07 — Get at a single column `[Do]`\n\nPull out the `score` column with `$`. How many values does it hold, and what are\nthe lowest and highest scores?\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n\n```{.r .cell-code}\nmin(sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 541\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2019\n```\n\n\n:::\n:::\n\n\n`sessions$score` is an ordinary vector, so everything from Part A works on it. You\nwill also see `sessions[[\"score\"]]` in other people's code; it does the same job.\n:::\n\n**Write 1 sentence:** the lowest score is far below the rest. What would you want\nto know about that session before you trusted any average of `score`?\n\n## Exercise 08 — Classify every column `[Apply]`\n\nFor each of these columns, state whether it is **nominal**, **ordinal**,\n**discrete** or **continuous** (see\n[Data, Variables and Types](../notes/03-data-and-types.qmd#types-of-data)):\n`cohort`, `archetype`, `build`, `score`, `kills`, `deaths`, `session_minutes`,\n`quit_reason`.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n| Column | Type | Why |\n| :- | :- | :- |\n| `cohort` | Ordinal | Novice → Regular → Veteran has a real order |\n| `archetype` | Nominal | Scout is not more or less than Sentinel |\n| `build` | Nominal | Two labels, no order |\n| `score` | Discrete | Whole points, though large enough to treat as continuous |\n| `kills` | Discrete | A count |\n| `deaths` | Discrete | A count |\n| `session_minutes` | Continuous | Measured time, one decimal place |\n| `quit_reason` | Nominal | Four labels, no order |\n\nThe interesting one is `cohort`. R has loaded it as `chr`, plain text, and will\nsort it alphabetically as Novice, Regular, Veteran, which happens to be the right\norder by accident. Never rely on that.\n:::\n\n**Write 2 sentences:** pick one column above and explain what would go wrong if you\ntreated it as the wrong type.\n\n## Exercise 09 — \"Only one in five\" `[Decide]`\n\n\n\nThe producer counts the quit reasons and says: *\"Only one in five players quit in\nfrustration. Most players are fine, so frustration is not a priority.\"* Count\n`quit_reason`, then find the share of frustration quits in each build, and decide\nwhether the producer's reading is defensible.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |> count(quit_reason)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  quit_reason         n\n  <chr>           <int>\n1 Completed test     69\n2 Frustrated         25\n3 Lost interest      21\n4 Technical fault     5\n```\n\n\n:::\n\n```{.r .cell-code}\nsessions |>\n  group_by(build) |>\n  summarise(n = n(),\n            frustrated = mean(quit_reason == \"Frustrated\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  build     n frustrated\n  <chr> <int>      <dbl>\n1 A        60     0.333 \n2 B        60     0.0833\n```\n\n\n:::\n:::\n\n\n**One defensible answer: no, because \"one in five\" averages two different\ngames.** Overall, 25 of 120 sessions ended in frustration,\n21%. Split by build, that is 20 of\n60 in Build A (33%) and 5 of 60 in\nBuild B (8%). One build loses a third of its players to\nfrustration; the other hardly any. The overall figure describes neither.\n\n**What makes it defensible.** It breaks the count down by the one thing the\nplaytest was designed to compare before judging it, and it reads the numbers as\na difference between builds rather than a verdict on the game.\n\n**What would make it indefensible.** Accepting \"one in five\" because it is smaller\nthan the number who completed the test, without asking where the one in five came\nfrom. Or going the other way and calling the whole game frustrating, when Build B\nbarely is.\n:::\n\n**Write 2 sentences:** what would you say to the producer instead, and what would\nyou want to check next?\n\n## Exercise 10 — Describe a numeric variable properly `[Apply]`\n\nFor `score` and for `session_minutes`, compute the mean, median, standard\ndeviation, quartiles and IQR.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1428.767\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1470\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 319.2236\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     0%     25%     50%     75%    100% \n 541.00 1270.00 1470.00 1628.75 2019.00 \n```\n\n\n:::\n\n```{.r .cell-code}\nIQR(sessions$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 358.75\n```\n\n\n:::\n\n```{.r .cell-code}\nsessions |>\n  summarise(mean   = mean(session_minutes),\n            median = median(session_minutes),\n            sd     = sd(session_minutes),\n            iqr    = IQR(session_minutes))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n   mean median    sd   iqr\n  <dbl>  <dbl> <dbl> <dbl>\n1  22.8   26.2  7.76  13.8\n```\n\n\n:::\n:::\n\n\nBoth ways work. The first is quick for one variable; `summarise()` puts every\nsummary in one table, which is what you want once there is more than one.\n`quantile()` with no second argument gives the five-number summary.\n:::\n\n**Write 2 sentences:** express the gap between mean and median as a percentage of\nthe median, for both variables. Which one is more skewed, and does its tail run\nleft or right?\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show answer\"}\n\n\n::: {.cell}\n\n:::\n\n\nScore's mean sits 2.8% below its median. Session\nminutes sits 12.9% below. Both are **left-skewed**:\nthe mean falls below the median because a group of low values drags it down. But\nsession minutes is far more so.\n\nComparing the raw gaps (-41\npoints against -3.4\nminutes) would have told you the opposite, which is why the scale of the variable\nalways has to come into it.\n:::\n\n## Exercise 11 — See the shape `[Apply]`\n\nDraw a histogram of `score` and a boxplot of `session_minutes`. Give both a title\nand a sensible axis label.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(sessions$score,\n     breaks = 20,\n     main   = \"Distribution of session score\",\n     xlab   = \"Score\",\n     col    = \"grey85\",\n     border = \"white\")\n```\n\n::: {.cell-output-display}\n![](reading-data_files/figure-html/ex11-1.png){fig-alt='Histogram titled Distribution of session score: most sessions between 1,200 and 1,800, with a separate small group around 500 to 700.' width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(sessions$session_minutes,\n        main       = \"How long testers played\",\n        xlab       = \"Minutes\",\n        horizontal = TRUE,\n        col        = \"grey85\")\n```\n\n::: {.cell-output-display}\n![](reading-data_files/figure-html/ex11b-1.png){fig-alt='Horizontal boxplot titled How long testers played, running from about 8 to 32 minutes, with the median near 26 and a long lower whisker.' width=768}\n:::\n:::\n\n\n:::\n\n**Write 2 sentences:** set `breaks = 5` and then `breaks = 40`, and describe what\nhappens to the story the histogram tells. See [rule 4](../notes/ten-rules.qmd).\n\n## Exercise 12 — Split a numeric variable by a group `[Apply]`\n\nIs one archetype's score less predictable than the others? Summarise `score` for\neach archetype (n, median, IQR and SD), then draw boxplots of `score` split by\n`archetype`, in one plot.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  group_by(archetype) |>\n  summarise(n      = n(),\n            median = median(score),\n            iqr    = IQR(score),\n            sd     = round(sd(score)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  archetype     n median   iqr    sd\n  <chr>     <int>  <dbl> <dbl> <dbl>\n1 Duelist      30  1426.  346.   225\n2 Engineer     30  1472.  310.   259\n3 Scout        30  1546   288.   248\n4 Sentinel     30  1528.  647.   455\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(score ~ archetype,\n        data = sessions,\n        main = \"Score by archetype\",\n        ylab = \"Score\",\n        col  = \"grey85\")\n```\n\n::: {.cell-output-display}\n![](reading-data_files/figure-html/ex12b-1.png){fig-alt='Four boxplots of score by archetype. Sentinel\\'s box is much taller than the other three and stretches down to about 950.' width=768}\n:::\n:::\n\n\n`group_by()` splits the table by archetype and `summarise()` computes each summary\nonce per piece. In the boxplot, `score ~ archetype` reads as \"score, split by\narchetype\".\n:::\n\n**Write 2 sentences:** one archetype has a much larger spread than the others.\nWhich one, and why is \"larger spread\" a more useful observation here than \"lower\naverage\"?\n\n## Exercise 13 — Which build keeps players longer? `[Apply]`\n\nSummarise `session_minutes` for each build: the number of sessions, the median, the\nIQR and the share of sessions that lasted at least 20 minutes. Then draw the two\nbuilds' session lengths as side-by-side boxplots.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions |>\n  group_by(build) |>\n  summarise(n              = n(),\n            median_minutes = median(session_minutes),\n            iqr_minutes    = IQR(session_minutes),\n            share_20_plus  = mean(session_minutes >= 20))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  build     n median_minutes iqr_minutes share_20_plus\n  <chr> <int>          <dbl>       <dbl>         <dbl>\n1 A        60           23.2        16.3         0.567\n2 B        60           27.1        10.9         0.683\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(session_minutes ~ build, data = sessions,\n        main = \"Session length by build\", ylab = \"Minutes\", col = \"grey85\")\n```\n\n::: {.cell-output-display}\n![](reading-data_files/figure-html/ex13b-1.png){fig-alt='Two boxplots of session length. Build A\\'s box is wider and lower than Build B\\'s.' width=768}\n:::\n:::\n\n\n`mean(session_minutes >= 20)` is the proportion trick from Part A, run once per\nbuild inside `summarise()`.\n:::\n\n**Write 2 sentences:** what does the IQR tell you about Build A that the median\ndoes not? Which number would you put in front of the design lead?\n\n## Exercise 14 — When do we lose them? `[Decide]`\n\n\n\nThe producer has the two mean session lengths, 21.3 minutes\nfor Build A and 24.2 for Build B, and says: *\"Build A\nsessions are about three minutes shorter. Players drift off a bit sooner, that's\nall.\"*\n\nA **retention curve** shows the share of sessions still going at every minute. Run\nthis code to draw one for each build; you do not need to be able to write it. Then\ndecide whether \"drift off a bit sooner\" is a fair description.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmins_a <- sessions$session_minutes[sessions$build == \"A\"]\nmins_b <- sessions$session_minutes[sessions$build == \"B\"]\n\nminute  <- 0:32\nstill_a <- sapply(minute, function(m) mean(mins_a >= m))\nstill_b <- sapply(minute, function(m) mean(mins_b >= m))\n\nplot(minute, still_a, type = \"s\", lwd = 2, col = \"grey40\", ylim = c(0, 1),\n     main = \"Share of sessions still playing\",\n     xlab = \"Minute\", ylab = \"Share still playing\")\nlines(minute, still_b, type = \"s\", lwd = 2, col = \"firebrick\")\nlegend(\"bottomleft\", legend = c(\"Build A\", \"Build B\"), lwd = 2,\n       col = c(\"grey40\", \"firebrick\"), bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](reading-data_files/figure-html/ex14-curve-1.png){fig-alt='Two step lines showing the share of sessions still playing at each minute. Build A\\'s grey line drops sharply between minutes 11 and 13; Build B\\'s red line stays higher until the late twenties.' width=768}\n:::\n:::\n\n\n`mean(mins_a >= m)` is the share of Build A sessions that lasted at least `m`\nminutes, the proportion trick again; `sapply()` repeats it for every minute.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n**One defensible answer: no. Build A does not drift; it drops.** Between minutes\n11 and 13, Build A loses 20% of its sessions; Build B loses\n7% over the same two minutes. Something in the first dozen\nminutes of Build A drives a block of players out at once, and Exercise 09 already\nshowed those quits are frustration. The investigation should start at minute 11 of\nBuild A: watch the replays, check where those players were.\n\n**What makes it defensible.** It looks at *when* players left, not just the\naverage, and names a specific moment someone can investigate.\n\n**What would make it indefensible.** Comparing the two means, agreeing that the\ndifference is \"a bit\", and moving on. The mean folds a sharp exit at minute 12 and\na long tail of full sessions into one number that describes neither\n([rule 9](../notes/ten-rules.qmd)).\n:::\n\n**Write 2 sentences:** what would you ask the level designer to check first, and\nwhat number would tell you, in the next playtest, that the fix worked?\n\n---\n\n# Challenge — Which cohort is the game actually built for? `[Decide]`\n\nYou have been asked a real question by the design lead: **is Tidebreak too hard\nfor novice players?**\n\nUsing only what is in this lab, produce the evidence you would take into that\nconversation. There is no single correct answer. There is a defensible one and an\nindefensible one.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show solution\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One table: size, score, deaths, session length and frustration, per cohort\nsessions |>\n  group_by(cohort) |>\n  summarise(n              = n(),\n            mean_score     = round(mean(score)),\n            mean_deaths    = round(mean(deaths), 2),\n            median_minutes = median(session_minutes),\n            frustrated     = round(mean(quit_reason == \"Frustrated\"), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  cohort      n mean_score mean_deaths median_minutes frustrated\n  <chr>   <int>      <dbl>       <dbl>          <dbl>      <dbl>\n1 Novice     33       1253        3.24           27.1       0.18\n2 Regular    53       1414        3.09           24.2       0.26\n3 Veteran    34       1622        2.65           24.8       0.15\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show the shape, not just the numbers\nboxplot(score ~ cohort, data = sessions,\n        main = \"Score by player cohort\", ylab = \"Score\", col = \"grey85\")\n```\n\n::: {.cell-output-display}\n![](reading-data_files/figure-html/challenge-plot-1.png){fig-alt='Three boxplots of score by cohort, rising from Novice to Regular to Veteran, with a few low outliers in the Regular and Veteran groups.' width=768}\n:::\n:::\n\n\n**What the evidence shows.** Novices do score lower, and that is the finding\neveryone expects. On its own it looks like a difficulty problem.\n\nEvery other measure contradicts it. Novices die at almost exactly the same rate as\neveryone else, they play for *longer* than either other cohort, and they are less\nlikely to quit in frustration than regular players. A game that was too hard for\nnovices would show them dying more and leaving sooner. This one does not.\n\n**So the defensible answer is: no.** The score gap looks like inexperience rather\nthan difficulty: novices are playing the game safely and slowly and scoring less\nfor it. The genuinely odd number in that table is the frustration rate among\n*regular* players, which nobody asked about and which is the thing worth chasing\nnext.\n\n**What would make it indefensible.** Comparing three mean scores, announcing that\nnovices are struggling, and recommending a difficulty change. The number is real\nand the conclusion does not follow from it.\n:::\n\n**Write 3–4 sentences**, using **What → Pattern → Meaning → Action**:\n\n- **What** did you measure?\n- **Pattern**: what does the evidence show?\n- **Meaning**: what might that mean for the design?\n- **Action**: what is the one change or the one further test you would recommend?\n\n**Going further:** Distributions and Shape says a normal distribution puts about\n68% of values within 1 SD of the mean. If you want to check that against real\ncolumns, try the exercise at the end of\n[Is It Normal Enough?](../going-further/normality.qmd).\n\n---\n\n# Appendix — Mini dataset for Part A\n\nIf the CSV files are not available, use this in place of `sessions`.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show the mini dataset\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmini_sessions <- data.frame(\n  player_id       = c(\"P01\", \"P02\", \"P03\", \"P04\", \"P05\", \"P06\", \"P07\", \"P08\"),\n  cohort          = c(\"Novice\", \"Veteran\", \"Regular\", \"Novice\",\n                      \"Regular\", \"Veteran\", \"Regular\", \"Novice\"),\n  build           = c(\"A\", \"B\", \"A\", \"B\", \"A\", \"B\", \"A\", \"B\"),\n  score           = c(1370, 1795, 1690, 1544, 2019, 1614, 1652, 1331),\n  kills           = c(7, 5, 5, 7, 12, 7, 6, 7),\n  deaths          = c(4, 2, 2, 4, 3, 5, 4, NA),\n  session_minutes = c(12.9, 24.6, 12.5, 18.8, 18.7, 29.4, 11.2, 27.0),\n  quit_reason     = c(\"Frustrated\", \"Lost interest\", \"Frustrated\",\n                      \"Completed test\", \"Completed test\", \"Completed test\",\n                      \"Frustrated\", \"Technical fault\")\n)\n\nglimpse(mini_sessions)\n```\n:::\n\n\n:::\n\n# Appendix — Common first-week errors\n\n::: {.callout-warning collapse=\"true\" title=\"Show the error guide\"}\n\n| Message | What it usually means |\n| :- | :- |\n| `could not find function \"read_csv\"` | You forgot `library(readr)` |\n| `could not find function \"count\"` (or `group_by`, `summarise`, `glimpse`) | You forgot `library(dplyr)` |\n| `object 'sessions' not found` | You have not run the Setup block, or you restarted R |\n| `object 'Score' not found` | Wrong capitalisation. R is case-sensitive |\n| `$ operator is invalid for atomic vectors` | You used `$` on a vector instead of a data frame |\n| `argument \"x\" is missing, with no default` | You called a function with no argument, usually a stray `()` |\n| `unexpected symbol` / `unexpected ')'` | A typo: nearly always a missing comma or an unclosed bracket on the line above |\n| The console shows `+` instead of `>` | R is waiting for you to finish an expression, often a pipe `\\|>` at the end of the last line. Press **Esc** |\n\n:::\n",
    "supporting": [
      "reading-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}