{
  "hash": "bb0c617181c11c22b5cb2c88ae144a67",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regression\"\nsubtitle: \"The line through a scatterplot: slope, R² and residuals\"\n---\n\n\n\n> **Going further.** This page extends\n> [Relationships and Correlation](../notes/10-relationships-and-correlation.qmd).\n> Nothing here is needed for the labs or the assessment. Read it if your team wants\n> to say *how much* one measure changes with another, or if a residual might be\n> hiding your finding.\n\n---\n\n## Simple Linear Regression\n\nCorrelation says how tightly two variables follow a line. **Simple linear\nregression** finds that line, and so answers a more useful question: *how much does\none variable change, on average, for each unit of the other?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(score ~ awareness, data = sessions)\ncoef(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   awareness \n  426.13072    15.15319 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 %    97.5 %\n(Intercept) 172.1697 680.09176\nawareness    11.3806  18.92578\n```\n\n\n:::\n:::\n\n\n`lm()` stands for *linear model*. `score ~ awareness` reads \"score as explained by\nawareness\", the same formula style as `boxplot(y ~ group)`. The result describes a\nstraight line:\n\n$$\\text{predicted score} = 426 + 15.2 \\times \\text{awareness}$$\n\n**The slope** is the number that matters: each extra point of awareness goes with\n15.2 more points of score, on average (95% CI\n11.4 to 18.9). It is in the units of the\nquestion, so a designer can use it: the\n18-point gap in average\nawareness between Novices and Veterans goes with about\n280 points of\nscore.\n\n**The intercept** is the predicted score at awareness zero: 426. No player\nhas an awareness anywhere near zero (the lowest is 38), so\nit means nothing on its own; it just anchors the line.\n\n---\n\n## Residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions$predicted <- fitted(fit)\nsessions$residual  <- resid(fit)\nggplot(sessions, aes(awareness, score)) +\n  geom_segment(aes(xend = awareness, yend = predicted), colour = \"grey75\") +\n  geom_point(aes(colour = residual < -600), size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, colour = pal$highlight) +\n  scale_colour_manual(values = c(`FALSE` = pal$line, `TRUE` = \"#8a5a9c\"),\n                      labels = c(\"Other sessions\", \"Residual below −600\"), name = NULL) +\n  labs(x = \"Awareness rating\", y = \"Score\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Score against awareness, with the regression line. Each grey segment is a residual; the sessions furthest below the line are mostly Sentinel collapses.](regression_files/figure-html/fig-regression-1.png){#fig-regression fig-alt='Scatterplot of score against awareness with a rising red line. Short grey vertical segments join each point to the line. A handful of points sit far below the line at the bottom, with long segments, coloured differently from the rest.' width=768}\n:::\n:::\n\n\n**A residual** is the gap between what actually happened and what the line\npredicted: actual minus predicted. The line is chosen to make the residuals, taken\ntogether, as small as possible (it minimises the sum of their squares, hence\n\"least squares\"). `geom_smooth(method = \"lm\")` draws the same line.\n\n**Residuals are where the findings hide.** The seven sessions furthest *below* the\nline, the ones that scored far less than their awareness predicted, include\n6 Sentinels. The regression has found the Sentinel\ncollapses from [Describing Variables](../notes/04-describing-variables.qmd#worked-example)\non its own: those games are not explained by awareness at all.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessions[order(resid(fit))[1:7], c(\"session_id\", \"archetype\", \"awareness\", \"score\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 4\n  session_id archetype awareness score\n  <chr>      <chr>         <dbl> <dbl>\n1 S059       Sentinel         78   587\n2 S045       Sentinel         63   597\n3 S034       Sentinel         61   584\n4 S052       Sentinel         54   541\n5 S046       Sentinel         55   579\n6 S047       Sentinel         59   643\n7 S012       Scout            67   934\n```\n\n\n:::\n:::\n\n\n---\n\n## R²\n\n**R²**, the **coefficient of determination**, is the share of the variation in\nscore that the line accounts for: 0.35, or 35%. For a simple\nregression it is exactly the correlation squared\n(0.59² = 0.35). Awareness accounts for about a third of the\ndifferences in score; the other two thirds are everything else.\n\n---\n\n## Predicting, Carefully\n\nThe line predicts a score of about\n1640 for awareness 80. That\nprediction is an average for players like that, not a promise for any one player,\nwhose residual could easily be 260 points either way. And\n**never predict outside the data**: the line knows nothing about awareness below\n38 or above 95. Using it there is\n**extrapolation**, and the straight line may not continue.\n\n**A regression is still a correlation.** A steep, significant slope says awareness\nand score move together, by this much. It does not say that raising a player's\nawareness would raise their score. Every warning about confounding applies\nunchanged.\n\n---\n\n## Reading the Full Summary\n\n`summary(fit)` prints everything at once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = score ~ awareness, data = sessions)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1021.08   -97.01    18.49   183.27   436.30 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  426.131    128.246   3.323  0.00119 ** \nawareness     15.153      1.905   7.954 1.22e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 258.6 on 118 degrees of freedom\nMultiple R-squared:  0.349,\tAdjusted R-squared:  0.3435 \nF-statistic: 63.27 on 1 and 118 DF,  p-value: 1.223e-12\n```\n\n\n:::\n:::\n\n\nThe `awareness` row of the **Coefficients** table gives the slope, its standard\nerror and a p-value testing whether the true slope could be zero. **Multiple\nR-squared** is R². Regression with several predictors at once (multiple\nregression) can adjust for a confounder such as cohort, but it is beyond this\ncourse, and adjusting for the confounders you measured does not protect you from\nthe ones you did not.\n\n---\n\n## Try It\n\n1. Fit a regression of `score` on `deaths`. Interpret the slope in one sentence a\n   designer could use, and compare its R² with awareness's.\n2. A designer reads the awareness regression and says: \"If we raise a Novice's\n   awareness by 20 points, they will score about 300 more.\" Give\n   two reasons to doubt it.\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\" icon=\"false\" title=\"Show answers\"}\n**1.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_d <- lm(score ~ deaths, data = sessions)\ncoef(fit_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      deaths \n  1779.8824   -116.7144 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_d)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3156496\n```\n\n\n:::\n:::\n\n\nEach extra death goes with about\n117 fewer points of score,\non average. R² is 0.32,\na little below awareness's 0.35. The same caution applies: dying more\nand scoring less may both come from being outplayed.\n\n**2.** First, the slope is an association across players, not the effect of\nchanging one player: awareness ratings may reflect skill rather than cause it.\nSecond, it is an average: individual players scatter around the line by about\n260 points. A third reason, if the Novice starts low: their\nraised awareness may still be in a range where the data is thin.\n:::\n",
    "supporting": [
      "regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}