{
  "hash": "06f2c445782a89bb668c579e71512ac8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Distributions and Variation\"\nsubtitle: \"Why the average is never the whole story\"\n---\n\n> Week 1, second cycle, for everyone, before Part B of Lab 01. It moves on from\n> a single typical value to the whole spread of players: how much they differ,\n> what shape that difference takes, and which values sit outside it. The worked\n> example is the one to remember: two builds with the same frame rate, one of\n> which stutters.\n\n---\n\n## Learning Outcomes\n\nBy the end of these notes you can:\n\n- explain why an average on its own cannot describe a playtest;\n- read a standard deviation as the typical distance of a player from the mean;\n- describe a distribution by its centre, spread, skew and outliers;\n- say whether an outlier is an error, an extreme player or the finding itself;\n- read the mean, median, standard deviation and high percentiles together and say\n  what each adds;\n- draw `hist()`, `boxplot()`, `barplot()` and `plot()` in base R and say what each\n  one is for.\n\n---\n\n## Why This Matters for Playtesting\n\nEvery design question is really a question about players, plural, and players\ndiffer. A level that takes eight minutes on average can be a level everyone\nfinishes in eight minutes, or a level half the testers finish in four and the other\nhalf abandon. Those are different games with different fixes, and the average\ncannot tell them apart.\n\n**The players you design for are rarely the average player.** The ones who quit,\nthe ones who get stuck, the ones whose machine stutters: they live in the edges of\nthe distribution, and the edges are exactly what a mean averages away.\n\n**Variation is information, not noise.** When two builds differ in how spread out\ntheir players are, that difference is often the finding. A build that tightens the\nspread has made the experience more consistent, even if the average has not moved.\n\n---\n\n## Variation Between Players\n\nThe **variation** in a variable is how much its values differ from one another.\nSome of it is the game: a harder route produces more deaths. Some of it is the\nplayer: skill, experience and patience vary before anyone touches your build. You\ncannot remove the second kind, so you have to measure it.\n\nThe **standard deviation** is the typical distance of a value from the mean. A\nsmall standard deviation means players cluster tightly around the average; a large\none means the average is a poor guide to any individual. It is in the same units as\nthe data, so a standard deviation of 3 ms on a frame time is directly comparable to\nthe 16.7 ms a 60 FPS frame is allowed.\n\n**Standard deviation belongs to the mean.** It measures distance from the mean, so\nit inherits the mean's weakness: a few extreme values inflate it. For skewed data,\nthe interquartile range from the previous notes is the better description of\nspread.\n\n---\n\n## Distributions and Skew\n\nA **distribution** is the full pattern of values: which ones occur, and how often.\nA histogram draws it. Every summary statistic is an attempt to describe a\ndistribution in one number, and every one of them fails for some distribution.\n\n**Skew** is a distribution leaning to one side. A **right skew** has a long tail of\nlarge values: most frames are quick, a few are very slow. A **left skew** has a\nlong tail of small values: most players stay for the full session, a few leave\nearly. The mean is pulled towards the tail; the median is not. That is why the gap\nbetween them tells you which way the data leans.\n\n**Game data is rarely symmetric.** Times have a floor and no ceiling. Match lengths\nhave a ceiling set by the timer. Ratings bunch against the ends of the scale. Expect\nskew and check for it, rather than assuming the bell shape from school statistics.\n\n---\n\n## Outliers\n\nAn **outlier** is a value far from the rest. The boxplot's convention is any point\nmore than one and a half box-widths beyond the edge of the box, and R draws those\npoints individually. That rule is a prompt to look, not a verdict.\n\nAn outlier is one of three things, and the response to each is different:\n\n| The outlier is | Example | What you do |\n| :- | :- | :- |\n| An error | A session length of −3 minutes; a rating of 7 on a 1–5 scale | Fix it or remove it, and record that you did |\n| An extreme but ordinary player | One tester who never died | Keep it; report the median rather than the mean |\n| The finding | A cluster of games that collapse early | Keep it and investigate it; it is why you ran the test |\n\n**Never delete an outlier because it is inconvenient.** Every row you drop is a\ndecision with a consequence ([rule 6](ten-rules.qmd)), and the value most tempting\nto drop is often the one the playtest was run to find ([rule 9](ten-rules.qmd)).\n\n---\n\n## Reading Several Summaries Together\n\nNo single statistic describes a distribution, but a small set of them, read\ntogether, usually does.\n\n| Summary | What it tells you | What it misses |\n| :- | :- | :- |\n| Mean | The total spread evenly across players | Skew, clusters, tails |\n| Median | The middle player | How extreme the extremes are |\n| Standard deviation | Typical distance from the mean | Which direction the spread goes |\n| IQR | Width of the middle half | Everything outside the middle half |\n| 95th or 99th percentile | How bad the worst few per cent get | The typical case |\n\n**Where the summaries disagree, look at the picture.** Mean and median apart means\nskew. A large standard deviation with a small IQR means a few extreme values. A\nnormal median with a bad 99th percentile means a rare problem that the average will\nnever show. Each disagreement is a pointer to a specific shape, and the histogram\nconfirms which one ([rule 4](ten-rules.qmd)).\n\n---\n\n## Worked Examples\n\n\n\n**Which build runs better?** The *Tidebreak* team captured 4500 frames\nfrom each build, split across 3 level zones. The frame-rate counter reports\nBuild A at 58.8 FPS and Build B at 59 FPS. By the number everyone\nquotes, Build B is marginally the faster build.\n\nThe median agrees: 16.99 ms per frame for Build A,\n16.63 ms for Build B. So does the 95th percentile:\n18.8 ms against 18.4 ms. Three summaries, one verdict.\n\nThe 99th percentile disagrees. Build A's is 19.5 ms; Build B's is\n39.4 ms, 2.0 times\nas long. The standard deviation says the same thing more quietly:\n1.05 ms for Build A, 3.4 ms for Build B.\n\nCount the frames slower than 30 FPS (33.3 ms). Build A has\n0. Build B has 60, every one of them in the Corridor\nzone, and exactly 25 frames apart: at 60 FPS, a hitch\n2.4 times a second for as long as the player is in the corridor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorridor_a <- frames$ms[frames$build == \"A\" & frames$zone == \"Corridor\"]\n\nplot(corridor_b[1:200], type = \"l\", col = \"firebrick\",\n     ylim = c(10, 65),\n     main = \"Corridor frame times, first 200 frames\",\n     xlab = \"Frame\", ylab = \"Frame time (ms)\")\nlines(corridor_a[1:200], col = \"grey40\")\nabline(h = 1000 / 60, lty = 2)\nlegend(\"top\", legend = c(\"Build A\", \"Build B\"), horiz = TRUE,\n       col = c(\"grey40\", \"firebrick\"), lty = 1, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](distributions-and-variation_files/figure-html/worked-frame-trace-1.png){width=768}\n:::\n:::\n\n\n**Why the mean cannot see it.** The slow frames are\n1.3% of Build B's total. Spread across\nevery frame of the capture, they barely move the mean, and Build B's faster frames\nelsewhere more than make up for them. The 95th percentile sits below the problem\nbecause the problem is rarer than one frame in twenty. Only a summary aimed at the\nworst one per cent can see it, which is why the 99th percentile is the standard\nfigure in performance capture. The mean is not approximately wrong here. It is\nstructurally incapable of showing the thing players experience.\n\n---\n\n## R Demonstrations\n\nBase R first, then the tidyverse equivalent for the grouped summary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(dplyr)\n\nsessions <- read_csv(\"data/tidebreak_sessions.csv\", show_col_types = FALSE)\nframes   <- read_csv(\"data/tidebreak_frame_times.csv\", show_col_types = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(sessions$session_minutes, breaks = 20,\n     main = \"Session length\", xlab = \"Minutes\",\n     col = \"grey85\", border = \"white\")\n```\n\n::: {.cell-output-display}\n![](distributions-and-variation_files/figure-html/demo-hist-1.png){width=768}\n:::\n:::\n\n\n`hist()` draws the distribution of one numeric variable. Look for the bulk, the\ntails, and any second hump.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(session_minutes ~ build, data = sessions,\n        main = \"Session length by build\", ylab = \"Minutes\", col = \"grey85\")\n```\n\n::: {.cell-output-display}\n![](distributions-and-variation_files/figure-html/demo-box-build-1.png){width=768}\n:::\n\n```{.r .cell-code}\ntapply(sessions$session_minutes, sessions$build, sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       A        B \n8.301448 6.942605 \n```\n\n\n:::\n\n```{.r .cell-code}\ntapply(sessions$session_minutes, sessions$build, IQR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    A     B \n16.25 10.95 \n```\n\n\n:::\n:::\n\n\n`boxplot()` with `y ~ group` puts one box per group on the same axis, which is the\nquickest way to compare distributions. Build A's box is wider: its IQR is\n16.3 minutes against\n10.9 for Build B.\n88% of\nBuild A sessions were still going at minute 11, and\n68% at\nminute 13. The spread is where Build A loses its players.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(table(sessions$quit_reason),\n        main = \"How sessions ended\", ylab = \"Sessions\", col = \"grey85\")\n```\n\n::: {.cell-output-display}\n![](distributions-and-variation_files/figure-html/demo-barplot-1.png){width=768}\n:::\n:::\n\n\n`barplot()` draws counts of a categorical variable. Give it the output of\n`table()`, not the raw column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(sessions$deaths, sessions$score,\n     main = \"Deaths against score\", xlab = \"Deaths\", ylab = \"Score\",\n     pch = 19, col = \"grey40\")\n```\n\n::: {.cell-output-display}\n![](distributions-and-variation_files/figure-html/demo-scatter-1.png){width=768}\n:::\n:::\n\n\n`plot()` with two numeric variables draws a scatterplot: one point per session.\nRead it for direction and for scatter. How strongly two variables are related is\nWeek 3's subject.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(frames$ms[frames$build == \"B\"], c(0.5, 0.95, 0.99))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    50%     95%     99% \n16.6300 18.4300 39.3708 \n```\n\n\n:::\n:::\n\n\n`quantile()` with a vector of proportions returns any percentiles you ask for. For\nperformance data, always ask for the 99th.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nframes %>%\n  group_by(build) %>%\n  summarise(mean_ms   = mean(ms),\n            median_ms = median(ms),\n            sd_ms     = sd(ms),\n            p99_ms    = quantile(ms, 0.99),\n            fps       = 1000 / mean(ms))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  build mean_ms median_ms sd_ms p99_ms   fps\n  <chr>   <dbl>     <dbl> <dbl>  <dbl> <dbl>\n1 A        17.0      17.0  1.05   19.5  58.8\n2 B        16.9      16.6  3.40   39.4  59.0\n```\n\n\n:::\n:::\n\n\n`group_by()` splits the data and `summarise()` computes one row of summaries per\ngroup. This is the several-summaries-together table from the worked example in six\nlines, and it is the base R `tapply()` repeated five times.\n\n---\n\n## Interpretation Guidance\n\n**What the data shows.** Build A and Build B have near-identical mean frame times.\nBuild B has 60 frames slower than 30 FPS, all in the Corridor, and\nBuild A has 0.\n\n**What the analysis suggests.** Something in Build B's Corridor costs a frame at a\nfixed interval. The regular spacing points at a periodic job, such as streaming,\ngarbage collection or a timed effect, rather than at scene complexity.\n\n**What can legitimately be concluded.** Build B introduced a hitch confined to the\nCorridor, and a report that quotes average FPS alone would have shipped it. The\ncause is not established by frame times; that needs a profiler.\n\n**Quote the tail with the centre.** For anything where the worst case is what\nplayers remember, such as frame time, load time or matchmaking wait, report the\nmedian and a high percentile together. \"Median 16.6 ms, 99th\npercentile 39 ms\" is a performance report.\n\"59 FPS\" is a slogan.\n\n---\n\n## Common Mistakes\n\n**Reporting average FPS as the performance result.** It is the number the engine\nshows and the number least able to show a hitch.\n\n**Comparing groups by their means alone.** Two builds with the same mean can be\ndifferent games ([rule 7](ten-rules.qmd)). Draw the boxplots side by side.\n\n**Deleting outliers to clean the chart.** Find out which of the three kinds each one\nis first. The Sentinel's low scores in\n[Describing What You Have](describing-what-you-have.qmd) are the finding, not the\nnoise.\n\n**Quoting a standard deviation for skewed data.** It measures distance from the\nmean, and on skewed data the mean is in the wrong place. Use the IQR.\n\n**Stopping at the 95th percentile.** A problem affecting one frame in a hundred is\ninvisible at the 95th. Match the percentile to how rare the problem could be.\n\n**Reading a scatterplot as proof.** A downward cloud of points shows that two things\nmove together in this sample. It does not say which one causes the other.\n\n---\n\n## Short Practice Activities\n\nEach takes two or three minutes.\n\n**1.** Compute the 99th percentile of frame time for each zone in Build B. Which\nzone is responsible?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nframes_b <- frames[frames$build == \"B\", ]\ntapply(frames_b$ms, frames_b$zone, quantile, 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Atrium Corridor   Gantry \n 18.9300  48.5451  19.1502 \n```\n\n\n:::\n:::\n\n\nThe Corridor, at 48.5 ms. The other two\nzones are at most\n19.2 ms. Splitting a summary by where it happened turns \"Build B stutters\"\ninto \"Build B stutters in one place\", which is a ticket someone can fix.\n:::\n\n**2.** Redraw the quit-reason bar chart with one bar per build side by side. What\ndoes it add to the single bar chart?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(table(sessions$build, sessions$quit_reason),\n        beside = TRUE, legend.text = TRUE,\n        main = \"How sessions ended, by build\", ylab = \"Sessions\")\n```\n\n::: {.cell-output-display}\n![](distributions-and-variation_files/figure-html/practice-quit-build-1.png){width=768}\n:::\n:::\n\n\n20 Build A\nsessions ended in frustration against\n5 in Build B.\nThe single chart showed how often players left frustrated; the split shows which\nbuild they left.\n:::\n\n**3.** Using `tapply()`, find the median score for each number of deaths. Does the\npattern in the scatterplot hold up?\n\n::: {.callout-note collapse=\"true\" title=\"Check your answer\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(sessions$score, sessions$deaths, median)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     0      1      2      3      4      5      6      7 \n1627.0 1659.0 1496.0 1572.0 1370.0 1222.5  924.0  804.5 \n```\n\n\n:::\n:::\n\n\nBroadly, yes: sessions with no deaths have a median score of\n1627, and sessions with\n7 deaths have\n804.5. Check how\nmany sessions sit behind each median with `table(sessions$deaths)` before trusting\nthe ends of that list ([rule 8](ten-rules.qmd)).\n:::\n\n---\n\n## Summary\n\n- An average describes a group; it does not describe any player in it.\n- The standard deviation is the typical distance from the mean. Use the IQR when\n  the data is skewed.\n- Skew pulls the mean towards the tail. Game data is rarely symmetric.\n- An outlier is an error, an extreme player or the finding. Work out which before\n  doing anything to it.\n- Read several summaries together, and where they disagree, draw the picture.\n- For performance data, quote a high percentile. Both builds run at about\n  59 FPS, and only one of them stutters.\n\n---\n\n## Links to Relevant Reference Material\n\n- [Ten Rules](ten-rules.qmd): rule 4 (look at the shape before you quote the\n  average), rule 7 (compare distributions, not averages) and rule 9 (sometimes the\n  rare value is the whole story)\n- [Describing What You Have](describing-what-you-have.qmd): centre, spread and the\n  mean against the median\n- [R and Quarto Reference: describing one variable](../reference/r-quarto-reference.qmd#describing-one-variable),\n  [describing by group](../reference/r-quarto-reference.qmd#describing-by-group)\n  and [plots](../reference/r-quarto-reference.qmd#plots)\n- [Lab 01: exploring playtest data](../labs/reading-data.qmd), Part B\n\n---\n\n## Reflective Questions\n\n- A producer asks for \"one number\" to show the build's performance has improved.\n  Which number do you give, and what do you say about the numbers you left out?\n- Build A's session lengths are more spread out than Build B's. Is a narrower spread\n  always better for a game? Give a case where it would not be.\n- You find three sessions with a score of zero. What would you check before\n  deciding they are errors, and what would change your mind?\n- The Corridor hitch affects\n  1.3% of Build B's frames. At what point does a rare\n  problem stop being worth fixing, and who should decide?\n\n---\n",
    "supporting": [
      "distributions-and-variation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}